/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by scripts/gen_amp_window.py from metadata/socs/renesas/rzv2n/n44.json
 * (`openamp_carveout`) -- do not edit; regenerate.
 *
 * The CM33 OpenAMP shared window as the A55 sees it.  The beacon words
 * sit in the last ALP_AMP_BEACON_SIZE bytes of the rsctbl page, laid out
 * by include/alp/protocol/amp_beacon.h.
 */

#ifndef ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H
#define ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H

#define ALP_AMP_A55_BASE     0x4f700000u
#define ALP_AMP_SIZE         0x900000u
#define ALP_AMP_RSCTBL_SIZE  0x1000u
#define ALP_AMP_MHU_SHM_BASE 0x4f701000u
#define ALP_AMP_CM33_NS_BASE 0x9f700000u
/* CM33-NS address = A55 address + this. */
#define ALP_AMP_A55_TO_CM33_NS_OFFSET 0x50000000u
/* A55 address of the liveness beacon. */
#define ALP_AMP_BEACON_A55_ADDR 0x4f700ff0u

/* sysfs names of the generic-uio nodes: "<unit-address>.<node-name>". */
#define ALP_AMP_UIO_RSCTBL_NAME  "4f700000.rsctbl"
#define ALP_AMP_UIO_MHU_SHM_NAME "4f701000.mhu-shm"

#endif /* ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H */
