/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by scripts/gen_amp_window.py from metadata/socs/renesas/rzv2n/n44.json
 * (`openamp_carveout`) -- do not edit; regenerate.
 *
 * The CM33 OpenAMP shared window as the A55 sees it: each sub-region's
 * A55 base and size, and the sysfs name of its generic-uio node
 * ("<unit-address>.<node-name>").  The beacon words sit in the last
 * ALP_AMP_BEACON_SIZE bytes of the rsctbl page, laid out by
 * include/alp/protocol/amp_beacon.h.  CM33-NS address = A55 address +
 * ALP_AMP_A55_TO_CM33_NS_OFFSET.
 */

#ifndef ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H
#define ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H

#define ALP_AMP_A55_TO_CM33_NS_OFFSET 0x50000000u
#define ALP_AMP_RSCTBL_A55_BASE       0x4f700000u
#define ALP_AMP_RSCTBL_SIZE           0x1000u
#define ALP_AMP_UIO_RSCTBL_NAME       "4f700000.rsctbl"
#define ALP_AMP_MHU_SHM_A55_BASE      0x4f701000u
#define ALP_AMP_MHU_SHM_SIZE          0x1000u
#define ALP_AMP_UIO_MHU_SHM_NAME      "4f701000.mhu-shm"
#define ALP_AMP_VRING_CTL0_A55_BASE   0x4f800000u
#define ALP_AMP_VRING_CTL0_SIZE       0x50000u
#define ALP_AMP_UIO_VRING_CTL0_NAME   "4f800000.vring-ctl0"
#define ALP_AMP_VRING_CTL1_A55_BASE   0x4f850000u
#define ALP_AMP_VRING_CTL1_SIZE       0x50000u
#define ALP_AMP_UIO_VRING_CTL1_NAME   "4f850000.vring-ctl1"
#define ALP_AMP_VRING_SHM0_A55_BASE   0x4f900000u
#define ALP_AMP_VRING_SHM0_SIZE       0x300000u
#define ALP_AMP_UIO_VRING_SHM0_NAME   "4f900000.vring-shm0"
#define ALP_AMP_VRING_SHM1_A55_BASE   0x4fc00000u
#define ALP_AMP_VRING_SHM1_SIZE       0x300000u
#define ALP_AMP_UIO_VRING_SHM1_NAME   "4fc00000.vring-shm1"

#endif /* ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H */
