/* tests/host/test_pose_clip.c -- replays a REAL MoveNet keypoint trace
 * (tr_pose_clip.h, generated by tools/npu_body_proto.py: MoveNet Lightning
 * int8 on a synthetic 640x400 GREY8 clip of two public-domain photographs)
 * through pose.c + track.c exactly as the HE will: stillness arms
 * calibration, then one tr_track_update() per frame. Frame ranges are the
 * tool's script(). */
#include <assert.h>
#include <stdio.h>

#include "tr_pose_clip.h"

#define FW 640
#define FH 400

typedef struct {
	int lane, jumps, ducks, acted;
} tally_t;

static tr_intent_t g_in[TR_POSE_CLIP_FRAMES];

static tally_t span(int a, int b)
{
	tally_t s = { 0, 0, 0, 0 };
	for (int n = a; n <= b; n++) {
		s.lane += g_in[n].lane_delta;
		s.jumps += g_in[n].jump;
		s.ducks += g_in[n].duck;
		s.acted += g_in[n].source == TR_INPUT_VISION;
	}
	return s;
}

int main(void)
{
	tr_track_t t;
	tr_still_t still;
	int        calibrated_at = -1;
	bool       lost_at_end   = false;

	tr_track_init(&t, FW, FH);
	tr_still_reset(&still);
	for (int n = 0; n < TR_POSE_CLIP_FRAMES; n++) {
		tr_box_t b = tr_pose_box(&tr_pose_clip[n]);

		g_in[n] = tr_intent_none();
		if (!t.calibrated) {
			if (tr_still_step(&still, b)) {
				tr_track_calibrate(&t, b, FW);
				calibrated_at = n;
			}
			continue;
		}
		g_in[n] = tr_track_update(&t, b);
		printf("%3d box=%s x=%4d y=%4d w=%3d h=%3d c=%3d  lane%+d%s%s\n", n, b.valid ? "Y" : "-", b.x, b.y,
		       b.w, b.h, b.confidence, g_in[n].lane_delta, g_in[n].jump ? " JUMP" : "",
		       g_in[n].duck ? " DUCK" : "");
		if (n == TR_POSE_CLIP_FRAMES - 1) {
			lost_at_end = tr_track_player_lost(&t);
		}
	}
	printf("calibrated at frame %d\n", calibrated_at);

	/* Empty booth: no body. */
	for (int n = 0; n < 10; n++) {
		assert(!tr_pose_box(&tr_pose_clip[n]).valid);
	}
	/* Calibrates during the stand (the walk-in reaches the centre at frame 19,
	 * then 20..59 stand), after a full second still. */
	assert(calibrated_at >= 19 + TR_STILL_FRAMES - 1 && calibrated_at <= 59);

	tally_t s;
	s = span(calibrated_at + 1, 59); /* standing still: nothing */
	assert(s.lane == 0 && s.jumps == 0 && s.ducks == 0);
	s = span(60, 89); /* steps left */
	assert(s.lane == -1 && s.jumps == 0 && s.ducks == 0);
	s = span(90, 129); /* steps right two lanes */
	assert(s.lane == +2 && s.jumps == 0 && s.ducks == 0);
	s = span(130, 159); /* back to centre */
	assert(s.lane == -1 && s.jumps == 0 && s.ducks == 0);
	s = span(160, 173); /* jump */
	assert(s.jumps >= 1 && s.ducks == 0 && s.lane == 0);
	s = span(174, 197); /* standing */
	assert(s.jumps == 0 && s.ducks == 0 && s.lane == 0);
	s = span(198, 227); /* crouch, 30 frames */
	assert(s.ducks >= 25 && s.jumps == 0 && s.lane == 0);
	s = span(230, 251); /* standing again (2 frames to rise) */
	assert(s.ducks == 0 && s.jumps == 0 && s.lane == 0);
	s = span(270, TR_POSE_CLIP_FRAMES - 1); /* walked off: nothing acted on, player lost */
	assert(s.acted == 0);
	assert(lost_at_end);
	return 0;
}
