/*
 * Copyright 2026 ALP Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * rpmsg-v2n -- Cortex-M33 / Zephyr producer.
 *
 * Sister to ../../linux/src/main.c on the same V2N silicon.  Both
 * slices come from one board.yaml v2 and share the auto-generated
 * <alp/system_ipc.h> contract: same channel name, same endpoint
 * ids, same mailbox channel.  No address or id is typed by hand.
 *
 *   1. Open the framed RPC channel using the generated macros.
 *   2. Sample a sensor once per second via the portable <alp/peripheral.h>
 *      surface (placeholder synthetic counter under native_sim so the
 *      twister harness can latch the test).
 *   3. Send each sample as a `temperature` event to the A55 peer
 *      using alp_rpc_send().
 *
 * Under native_sim there is no real RPMsg device -- alp_rpc_open
 * returns NULL with ALP_ERR_NOT_READY and we exit with the harness
 * marker so the build-only test latches.
 */

#include <stdio.h>
#include <string.h>

#include <zephyr/kernel.h>

#include <alp/peripheral.h>
#include <alp/rpc.h>
#include <alp/system_ipc.h> /* generated by alp_orchestrate.py */

/* Capped burst keeps the native_sim run inside twister's timeout. */
#define SAMPLE_BURST 4u

int main(void)
{
    printf("[m33] rpmsg-v2n producer coming up\n");

    /* Spec §6.6 canonical open.  Every value here comes from the
     * generated header; the orchestrator computed them from the
     * project's `ipc:` block deterministically. */
    const alp_rpc_config_t cfg = {
        .name    = ALP_IPC_ALP_DEFAULT_RPMSG_NAME,
        .src_ept = ALP_IPC_ALP_DEFAULT_RPMSG_SRC_EPT,
        .dst_ept = ALP_IPC_ALP_DEFAULT_RPMSG_DST_EPT,
        .mbox_ch = ALP_IPC_ALP_DEFAULT_RPMSG_MBOX_CH,
    };
    alp_rpc_channel_t *ch = alp_rpc_open(&cfg);
    if (ch == NULL) {
        printf("[m33]   alp_rpc_open failed: last_err=%d\n", (int)alp_last_error());
        goto done;
    }

    /* Producer loop.  Synthetic counter on native_sim; on real
     * V2N silicon this would read alp_adc_read() / alp_i2c_xfer()
     * / alp_sensor_read() against the board's on-board sensor. */
    for (uint32_t i = 0; i < SAMPLE_BURST; ++i) {
        const float        sample = 22.5f + (float)i * 0.1f;
        const alp_status_t rv     = alp_rpc_send(ch, "temperature", &sample, sizeof(sample));
        if (rv != ALP_OK) {
            printf("[m33]   alp_rpc_send rv=%d at i=%u\n", (int)rv, (unsigned)i);
            break;
        }
        printf("[m33] sent temperature[%u]=%.1f\n", (unsigned)i, (double)sample);

#ifndef CONFIG_BOARD_NATIVE_SIM
        /* 1 Hz cadence on real silicon. */
        k_msleep(1000);
#endif
    }

    alp_rpc_close(ch);

done:
    printf("[rpmsg-v2n] done\n");
    return 0;
}
