/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * aen-eeprom-provision -- WRITE the 128-byte Alp hardware-info manifest into the
 * on-module 24C128 EEPROM on the E1M-AEN (Alif Ensemble) SoM, then read it back
 * and verify.  The write sibling of examples/aen/aen-eeprom-manifest, which only
 * reads.
 *
 * WHY THIS EXISTS.  Until this app, nothing in alp-sdk could put an identity on a
 * module.  scripts/program_eeprom.py packs the 128 bytes but never touches
 * hardware (its own docstring says so), and scripts/provision_som.py's EEPROM step
 * only *plans* the i2c write -- "--execute does not perform it (no backend exists
 * to)".  The documented fallback was a third-party USB-I2C adapter driven by its
 * own vendor tooling: an extra fixture, an extra tool, and a step no CI can check.
 *
 * The module's own M55 can reach the EEPROM over SoC I2C2, which the read sibling
 * proves on every run.  So the writer needs no fixture at all -- it is this app,
 * RAM-run over SWD (Flow C).  Nothing is written to MRAM, so provisioning leaves
 * no application behind and the module ships with whatever image the line intends.
 *
 * THE BYTES COME FROM THE HOST, NOT FROM HERE.  This app deliberately cannot
 * invent an identity.  The manifest blob is generated by scripts/program_eeprom.py
 * and baked in at build time via -DALP_MANIFEST_BIN=<path>; the build FAILS if it
 * is absent.  A default or placeholder identity silently written onto a module is
 * worse than a build error, because it is indistinguishable from a real one later.
 *
 * PROVISIONING IS REVERSIBLE.  The EEPROM is rewritable, unlike the CC3501E fuses.
 * A wrong manifest here is a re-run, not a scrapped part.  That is exactly why the
 * order in docs matters: do this step, and prove the module, BEFORE anything that
 * burns a fuse.
 */

#include <stdio.h>
#include <string.h>

#include <zephyr/kernel.h>

#include "alp/peripheral.h"
#include "alp/chips/eeprom_24c128.h"
#include "alp/hw_info.h"

/* The manifest bytes, generated at configure time from -DALP_MANIFEST_BIN.
 * Defines alp_manifest_blob[] and ALP_MANIFEST_BLOB_LEN.  Generated into the
 * build tree, never committed -- it carries one specific module's serial. */
#include "manifest_blob.h"

/* CRC-32 ISO-3309 (poly 0xEDB88320, init/xor-out 0xFFFFFFFF) -- matches
 * zlib.crc32, the algorithm scripts/program_eeprom.py uses to seal the blob.
 * Table-free bit-at-a-time form: the manifest is 128 bytes, so a lookup table
 * would only add flash footprint without a measurable speed win here.
 * Deliberately identical to the read sibling's copy: this app must compute the
 * CRC the same way the reader will, or a "verified" write still fails at boot. */
static uint32_t crc32_iso3309(const uint8_t *buf, size_t len)
{
	uint32_t crc = 0xFFFFFFFFu;
	for (size_t i = 0; i < len; ++i) {
		crc ^= (uint32_t)buf[i];
		for (unsigned b = 0; b < 8; ++b) {
			uint32_t mask = (uint32_t)-(int32_t)(crc & 1u);
			crc           = (crc >> 1) ^ (0xEDB88320u & mask);
		}
	}
	return ~crc;
}

/**
 * @brief Sanity-check the baked-in blob before it reaches the bus.
 *
 * Catches a mis-generated or truncated blob on the host side, where the cost is
 * a rebuild.  Writing an unchecked blob would leave the module holding bytes that
 * fail the reader's own checks, which looks identical to a bad EEPROM.
 *
 * @return true if the blob is the right length, carries the ALPH magic, the
 *         expected schema version, and a self-consistent CRC-32.
 */
static bool blob_is_sane(void)
{
	if (ALP_MANIFEST_BLOB_LEN != sizeof(alp_hw_info_eeprom_t)) {
		printf("[provision] blob is %u bytes, expected %u\n",
		       (unsigned)ALP_MANIFEST_BLOB_LEN,
		       (unsigned)sizeof(alp_hw_info_eeprom_t));
		return false;
	}

	const alp_hw_info_eeprom_t *m = (const alp_hw_info_eeprom_t *)alp_manifest_blob;

	if (m->magic != ALP_HW_INFO_MAGIC) {
		printf("[provision] blob magic = 0x%08x, expected 0x%08x\n",
		       (unsigned)m->magic,
		       (unsigned)ALP_HW_INFO_MAGIC);
		return false;
	}
	if (m->schema_version != ALP_HW_INFO_SCHEMA_VERSION) {
		printf("[provision] blob schema_version = %u, this build expects %u\n",
		       (unsigned)m->schema_version,
		       (unsigned)ALP_HW_INFO_SCHEMA_VERSION);
		return false;
	}

	/* The CRC covers everything up to but excluding the trailing crc32 field --
	 * the same span scripts/program_eeprom.py seals and the reader re-checks. */
	const size_t   covered = sizeof(*m) - sizeof(m->crc32);
	const uint32_t calc    = crc32_iso3309(alp_manifest_blob, covered);
	if (calc != m->crc32) {
		printf("[provision] blob crc32 = 0x%08x (stored) vs 0x%08x (computed)\n",
		       (unsigned)m->crc32,
		       (unsigned)calc);
		return false;
	}
	return true;
}

/** @brief Print the identity a blob carries, so the operator log records what was
 *         written without needing a separate read pass. */
static void print_identity(const alp_hw_info_eeprom_t *m, const char *tag)
{
	/* The char[] fields are not guaranteed NUL-terminated when full, so bound
	 * every print by its field width rather than trusting a terminator. */
	printf("[provision] %s family=%.*s sku=%.*s hw_rev=%.*s serial=%.*s mfg=%u-%02u-%02u\n",
	       tag,
	       (int)sizeof(m->family),
	       m->family,
	       (int)sizeof(m->sku),
	       m->sku,
	       (int)sizeof(m->hw_rev),
	       m->hw_rev,
	       (int)sizeof(m->serial),
	       m->serial,
	       (unsigned)m->mfg_year,
	       (unsigned)m->mfg_month,
	       (unsigned)m->mfg_day);
}

int main(void)
{
	printf("[provision] aen-eeprom-provision\n");

	if (!blob_is_sane()) {
		printf("RESULT FAIL: baked-in manifest blob failed its own checks\n");
		return 0;
	}
	print_identity((const alp_hw_info_eeprom_t *)alp_manifest_blob, "to write:");

	/* Portable bus 0 -> SoC I2C2 (the board overlay aliases alp-i2c0 to &i2c2 and
	 * supplies pinctrl_i2c2 on P5_6/P5_7).  100 kHz: the on-module bus has no
	 * fast-mode margin unless external pull-ups are stuffed. */
	alp_i2c_t *bus = alp_i2c_open(&(alp_i2c_config_t){
	    .bus_id     = 0u,
	    .bitrate_hz = 100000u,
	});
	if (bus == NULL) {
		printf("RESULT FAIL: alp_i2c_open -> NULL, err=%d\n", (int)alp_last_error());
		return 0;
	}

	eeprom_24c128_t ee;
	alp_status_t    s = eeprom_24c128_init(&ee, bus, 0x50u);
	if (s != ALP_OK) {
		printf("RESULT FAIL: eeprom_24c128_init -> %d\n", (int)s);
		return 0;
	}

	/* Refuse to overwrite an identity that is already there.  A module that
	 * already carries a valid manifest has a serial someone recorded; silently
	 * replacing it orphans that record.  Re-provisioning is legitimate (a
	 * mis-programmed unit, a schema migration) but it must be deliberate, so it
	 * needs -DALP_PROVISION_FORCE=1 at build time. */
	uint8_t existing[sizeof(alp_hw_info_eeprom_t)];
	s = eeprom_24c128_read(&ee, 0u, existing, sizeof(existing));
	if (s != ALP_OK) {
		printf("RESULT FAIL: pre-read -> %d\n", (int)s);
		return 0;
	}

	const alp_hw_info_eeprom_t *old = (const alp_hw_info_eeprom_t *)existing;
	if (old->magic == ALP_HW_INFO_MAGIC) {
		print_identity(old, "already present:");
#if !defined(ALP_PROVISION_FORCE) || (ALP_PROVISION_FORCE == 0)
		printf("[provision] module already carries a manifest -- refusing to "
		       "overwrite.  Rebuild with -DALP_PROVISION_FORCE=1 if this is "
		       "a deliberate re-provision, and record why.\n");
		printf("RESULT FAIL: refused to overwrite an existing manifest\n");
		return 0;
#else
		printf("[provision] ALP_PROVISION_FORCE set -- overwriting the above\n");
#endif
	}

	/* The driver splits at 64-byte page boundaries and ACK-polls each page, so a
	 * 128-byte write is two pages and two write cycles.  Nothing here needs to
	 * know that -- it is noted only because a bare i2c write of 128 bytes would
	 * silently wrap within one page and corrupt the manifest. */
	s = eeprom_24c128_write(&ee, 0u, alp_manifest_blob, ALP_MANIFEST_BLOB_LEN);
	if (s != ALP_OK) {
		printf("RESULT FAIL: eeprom_24c128_write -> %d\n", (int)s);
		return 0;
	}
	printf("[provision] wrote %u bytes at offset 0\n", (unsigned)ALP_MANIFEST_BLOB_LEN);

	/* Read back from the device, not from our own buffer.  The write returning OK
	 * only means the chip ACKed; it does not prove what landed. */
	uint8_t readback[sizeof(alp_hw_info_eeprom_t)];
	s = eeprom_24c128_read(&ee, 0u, readback, sizeof(readback));
	if (s != ALP_OK) {
		printf("RESULT FAIL: read-back -> %d\n", (int)s);
		return 0;
	}

	if (memcmp(readback, alp_manifest_blob, ALP_MANIFEST_BLOB_LEN) != 0) {
		printf("RESULT FAIL: read-back does not match what was written\n");
		return 0;
	}

	/* Re-derive the CRC from the bytes now on the device.  A byte-compare against
	 * our own buffer and a CRC over the device's bytes answer different questions;
	 * the second is what the boot-time reader will actually do. */
	const alp_hw_info_eeprom_t *back    = (const alp_hw_info_eeprom_t *)readback;
	const size_t                covered = sizeof(*back) - sizeof(back->crc32);
	const uint32_t              calc    = crc32_iso3309(readback, covered);
	if (calc != back->crc32) {
		printf("RESULT FAIL: on-device crc32 0x%08x != computed 0x%08x\n",
		       (unsigned)back->crc32,
		       (unsigned)calc);
		return 0;
	}

	print_identity(back, "verified on device:");
	printf("RESULT PASS: manifest written and verified on device\n");
	return 0;
}
