/**
 * @file cap.h
 * @brief Umbrella header for the ALP capability surface.
 *
 * Aggregates the SoC-level macros (from soc_caps.h) and the
 * instance-level types (from cap_instance.h) with the portable
 * runtime alp_has() / alp_cap_name() API into one include.
 *
 * Auto-generated by scripts/gen_soc_caps.py from
 * metadata/socs/{vendor}/{family}/{part}.json. DO NOT EDIT BY HAND --
 * regenerate with: python3 scripts/gen_soc_caps.py
 *
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * @par ABI status: [ABI-EXPERIMENTAL]
 *      Includes cap_instance.h which is v0.7 new and experimental.
 *      Marker is upgraded to [ABI-STABLE] when the underlying
 *      pieces stabilise.
 */

#ifndef ALP_CAP_H
#define ALP_CAP_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "soc_caps.h"
#include "cap_instance.h"

typedef enum {
	ALP_CAP_ID_HW_I2C,
	ALP_CAP_ID_HW_SPI,
	ALP_CAP_ID_HW_UART,
	ALP_CAP_ID_HW_I2S,
	ALP_CAP_ID_HW_PDM,
	ALP_CAP_ID_HW_ADC,
	ALP_CAP_ID_HW_DAC,
	ALP_CAP_ID_HW_CAN,
	ALP_CAP_ID_HW_CAN_FD,
	ALP_CAP_ID_HW_RTC,
	ALP_CAP_ID_HW_WDT,
	ALP_CAP_ID_HW_QENC,
	ALP_CAP_ID_HW_TIMER,
	ALP_CAP_ID_HW_PWM,
	ALP_CAP_ID_HW_ETHERNET,
	ALP_CAP_ID_HW_USB,
	ALP_CAP_ID_HW_MIPI_CSI,
	ALP_CAP_ID_HW_MIPI_DSI,
	ALP_CAP_ID_XSPI_DMA,
	ALP_CAP_ID_HEXSPI_DMA,
	ALP_CAP_ID_EMMC_DMA,
	ALP_CAP_ID_QUADSPI_DMA,
	ALP_CAP_ID_NPU_DRPAI,
	ALP_CAP_ID_HELIUM_MVE,
	ALP_CAP_ID_NEON,
	ALP_CAP_ID_GPU2D,
	ALP_CAP_ID_DAVE2D,
	ALP_CAP_ID_CRYPTOCELL,
	ALP_CAP_ID_INLINE_AES,
	ALP_CAP_ID_CAU,
	ALP_CAP_ID_DMA2D,
	ALP_CAP_ID_COUNT
} alp_cap_id_t;

/**
 * @brief Test whether the active SoC offers a hardware capability.
 * @param cap  Capability id from @ref alp_cap_id_t.
 * @return true if the capability is present, false otherwise.
 */
bool alp_has(alp_cap_id_t cap);

/**
 * @brief Return the symbolic name of a capability (e.g. "HW_I2C").
 * @param cap  Capability id; out-of-range returns NULL.
 * @return Pointer to a static string, or NULL.
 */
const char *alp_cap_name(alp_cap_id_t cap);

#ifdef __cplusplus
}
#endif

#endif /* ALP_CAP_H */
