/**
 * @file cap.h
 * @brief Umbrella header for the ALP capability surface.
 *
 * Aggregates the SoC-level macros (from soc_caps.h) and the
 * instance-level types (from cap_instance.h) with the portable
 * runtime alp_has() / alp_cap_name() API into one include.
 *
 * Auto-generated by scripts/gen_soc_caps.py from
 * metadata/socs/{vendor}/{family}/{part}.json. DO NOT EDIT BY HAND --
 * regenerate with: python3 scripts/gen_soc_caps.py
 *
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * @par ABI status: [ABI-EXPERIMENTAL]
 *      Includes cap_instance.h which is v0.7 new and experimental.
 *      Marker is upgraded to [ABI-STABLE] when the underlying
 *      pieces stabilise.
 */

#ifndef ALP_CAP_H
#define ALP_CAP_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "soc_caps.h"
#include "cap_instance.h"

/**
 * @brief SoC-level hardware capability identifiers.
 *
 * Pass one of these to @ref alp_has to test whether the active SoC
 * implements the corresponding hardware block.  These are SoC-level
 * ("does this silicon have an NPU at all?") -- distinct from the
 * per-instance flags in cap_instance.h.  @ref ALP_CAP_ID_COUNT is a
 * sentinel element count, not a real capability.
 */
typedef enum {
	ALP_CAP_ID_HW_I2C,      /**< Hardware I2C controller(s). */
	ALP_CAP_ID_HW_SPI,      /**< Hardware SPI controller(s). */
	ALP_CAP_ID_HW_UART,     /**< Hardware UART(s). */
	ALP_CAP_ID_HW_I2S,      /**< Hardware I2S audio serial port(s). */
	ALP_CAP_ID_HW_PDM,      /**< Hardware PDM microphone interface(s). */
	ALP_CAP_ID_HW_ADC,      /**< Hardware analog-to-digital converter(s). */
	ALP_CAP_ID_HW_DAC,      /**< Hardware digital-to-analog converter(s). */
	ALP_CAP_ID_HW_CAN,      /**< Classic CAN 2.0 controller(s). */
	ALP_CAP_ID_HW_CAN_FD,   /**< At least one CAN controller supports CAN-FD. */
	ALP_CAP_ID_HW_RTC,      /**< Real-time clock. */
	ALP_CAP_ID_HW_WDT,      /**< Watchdog timer(s). */
	ALP_CAP_ID_HW_QENC,     /**< Quadrature encoder interface(s). */
	ALP_CAP_ID_HW_TIMER,    /**< General-purpose timer(s). */
	ALP_CAP_ID_HW_PWM,      /**< PWM generator(s). */
	ALP_CAP_ID_HW_ETHERNET, /**< Ethernet MAC(s). */
	ALP_CAP_ID_HW_USB,      /**< USB controller(s). */
	ALP_CAP_ID_HW_MIPI_CSI, /**< MIPI CSI-2 camera receiver(s). */
	ALP_CAP_ID_HW_MIPI_DSI, /**< MIPI DSI display transmitter(s). */
	ALP_CAP_ID_XSPI_DMA,    /**< DMA-backed xSPI flash interface. */
	ALP_CAP_ID_HEXSPI_DMA,  /**< DMA-backed Hyper/Octal xSPI interface. */
	ALP_CAP_ID_EMMC_DMA,    /**< DMA-backed eMMC interface. */
	ALP_CAP_ID_QUADSPI_DMA, /**< DMA-backed Quad-SPI interface. */
	ALP_CAP_ID_NPU_DRPAI,   /**< Renesas DRP-AI neural accelerator. */
	ALP_CAP_ID_HELIUM_MVE,  /**< Arm Helium (M-profile vector extension). */
	ALP_CAP_ID_NEON,        /**< Arm NEON SIMD (A-profile). */
	ALP_CAP_ID_GPU2D,       /**< 2D graphics accelerator. */
	ALP_CAP_ID_DAVE2D,      /**< Renesas D/AVE 2D graphics engine. */
	ALP_CAP_ID_CRYPTOCELL,  /**< Arm CryptoCell security subsystem. */
	ALP_CAP_ID_INLINE_AES,  /**< Inline AES engine on a storage/transport path. */
	ALP_CAP_ID_CAU,         /**< Cryptographic acceleration unit. */
	ALP_CAP_ID_DMA2D,       /**< 2D DMA / blitter engine. */
	ALP_CAP_ID_COUNT        /**< Sentinel: number of capability ids. */
} alp_cap_id_t;

/**
 * @brief Test whether the active SoC offers a hardware capability.
 * @param cap  Capability id from @ref alp_cap_id_t.
 * @return true if the capability is present, false otherwise.
 */
bool alp_has(alp_cap_id_t cap);

/**
 * @brief Return the symbolic name of a capability (e.g. "HW_I2C").
 * @param cap  Capability id; out-of-range returns NULL.
 * @return Pointer to a static string, or NULL.
 */
const char *alp_cap_name(alp_cap_id_t cap);

#ifdef __cplusplus
}
#endif

#endif /* ALP_CAP_H */
