/**
 * @file cap.h
 * @brief Umbrella header for the ALP capability surface.
 *
 * Aggregates the SoC-level macros (from soc_caps.h) and the
 * instance-level types (from cap_instance.h) into one include.
 *
 * Auto-generated by scripts/gen_soc_caps.py.  DO NOT EDIT BY HAND --
 * regenerate with: python3 scripts/gen_soc_caps.py
 *
 * Copyright 2026 ALP Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * @par ABI status: [ABI-EXPERIMENTAL]
 *      Includes cap_instance.h which is v0.7 new and experimental.
 *      Marker is upgraded to [ABI-STABLE] when the underlying
 *      pieces stabilise.
 */

#ifndef ALP_CAP_H
#define ALP_CAP_H

#ifdef __cplusplus
extern "C" {
#endif

#include "soc_caps.h"
#include "cap_instance.h"

#ifdef __cplusplus
}
#endif

#endif /* ALP_CAP_H */
