/**
 * @file soc_caps.h
 * @brief Per-SoC peripheral capability macros (auto-generated).
 *
 * Auto-generated from metadata/socs/{vendor}/{family}/{part}.json
 * by scripts/gen_soc_caps.py.  DO NOT EDIT BY HAND — regenerate.
 *
 * Each SoC's capability macros are gated by CONFIG_ALP_SOC_{TOKEN}.
 * Apps select the active SoC via Kconfig.  When no SoC is
 * selected the macros default to a permissive UINT16_MAX so
 * capability checks accept any config — apps that want runtime
 * validation must select a specific SoC.
 *
 * Copyright 2026 ALP Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * @par ABI status: [ABI-STABLE]
 *      v0.1 generated; capability constants.
 *      See docs/abi-markers.md for the convention.
 */

#ifndef ALP_SOC_CAPS_H
#define ALP_SOC_CAPS_H

#include <stdint.h>

#if defined(CONFIG_ALP_SOC_ALIF_ENSEMBLE_E3)
/* alif:ensemble:e3 */
#define ALP_SOC_REF_STR "alif:ensemble:e3"
#define ALP_SOC_I2C_COUNT 5
#define ALP_SOC_SPI_COUNT 5
#define ALP_SOC_UART_COUNT 9
#define ALP_SOC_I2S_COUNT 5
#define ALP_SOC_PDM_COUNT 8
#define ALP_SOC_ADC_COUNT 4
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS 24
#define ALP_SOC_DAC_COUNT 2
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS 12
#define ALP_SOC_CAN_COUNT 1
#define ALP_SOC_CAN_FD_SUPPORTED 1
#define ALP_SOC_RTC_COUNT 1
#define ALP_SOC_WDT_COUNT 2
#define ALP_SOC_QENC_COUNT 4
#define ALP_SOC_TIMER_COUNT 16
#define ALP_SOC_PWM_COUNT 12
#define ALP_SOC_ETHERNET_COUNT 1
#define ALP_SOC_USB_COUNT 1
#define ALP_SOC_MIPI_CSI_COUNT 1
#define ALP_SOC_MIPI_DSI_COUNT 1
#define ALP_SOC_XSPI_DMA 1
#define ALP_SOC_HEXSPI_DMA 0
#define ALP_SOC_EMMC_DMA 0
#define ALP_SOC_QUADSPI_DMA 0
#define ALP_SOC_DRP_AI 0
#define ALP_SOC_HELIUM_MVE 1
#define ALP_SOC_NEON 0
#define ALP_SOC_GPU2D 0
#define ALP_SOC_DAVE2D 0
#define ALP_SOC_CRYPTOCELL 1
#define ALP_SOC_INLINE_AES 1
#define ALP_SOC_CAU 0
#define ALP_SOC_DMA2D 1
#define ALP_SOC_NPU_ARENA_SRAM_KIB 0

#elif defined(CONFIG_ALP_SOC_ALIF_ENSEMBLE_E4)
/* alif:ensemble:e4 */
#define ALP_SOC_REF_STR "alif:ensemble:e4"
#define ALP_SOC_I2C_COUNT 0
#define ALP_SOC_SPI_COUNT 0
#define ALP_SOC_UART_COUNT 0
#define ALP_SOC_I2S_COUNT 0
#define ALP_SOC_PDM_COUNT 0
#define ALP_SOC_ADC_COUNT 0
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_DAC_COUNT 0
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_CAN_COUNT 0
#define ALP_SOC_CAN_FD_SUPPORTED 0
#define ALP_SOC_RTC_COUNT 0
#define ALP_SOC_WDT_COUNT 0
#define ALP_SOC_QENC_COUNT 0
#define ALP_SOC_TIMER_COUNT 0
#define ALP_SOC_PWM_COUNT 0
#define ALP_SOC_ETHERNET_COUNT 0
#define ALP_SOC_USB_COUNT 0
#define ALP_SOC_MIPI_CSI_COUNT 0
#define ALP_SOC_MIPI_DSI_COUNT 0
#define ALP_SOC_XSPI_DMA 1
#define ALP_SOC_HEXSPI_DMA 0
#define ALP_SOC_EMMC_DMA 0
#define ALP_SOC_QUADSPI_DMA 0
#define ALP_SOC_DRP_AI 0
#define ALP_SOC_HELIUM_MVE 1
#define ALP_SOC_NEON 0
#define ALP_SOC_GPU2D 0
#define ALP_SOC_DAVE2D 0
#define ALP_SOC_CRYPTOCELL 1
#define ALP_SOC_INLINE_AES 1
#define ALP_SOC_CAU 0
#define ALP_SOC_DMA2D 1
#define ALP_SOC_NPU_ARENA_SRAM_KIB 0

#elif defined(CONFIG_ALP_SOC_ALIF_ENSEMBLE_E5)
/* alif:ensemble:e5 */
#define ALP_SOC_REF_STR "alif:ensemble:e5"
#define ALP_SOC_I2C_COUNT 0
#define ALP_SOC_SPI_COUNT 0
#define ALP_SOC_UART_COUNT 0
#define ALP_SOC_I2S_COUNT 0
#define ALP_SOC_PDM_COUNT 0
#define ALP_SOC_ADC_COUNT 0
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_DAC_COUNT 0
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_CAN_COUNT 0
#define ALP_SOC_CAN_FD_SUPPORTED 0
#define ALP_SOC_RTC_COUNT 0
#define ALP_SOC_WDT_COUNT 0
#define ALP_SOC_QENC_COUNT 0
#define ALP_SOC_TIMER_COUNT 0
#define ALP_SOC_PWM_COUNT 0
#define ALP_SOC_ETHERNET_COUNT 0
#define ALP_SOC_USB_COUNT 0
#define ALP_SOC_MIPI_CSI_COUNT 0
#define ALP_SOC_MIPI_DSI_COUNT 0
#define ALP_SOC_XSPI_DMA 1
#define ALP_SOC_HEXSPI_DMA 0
#define ALP_SOC_EMMC_DMA 0
#define ALP_SOC_QUADSPI_DMA 0
#define ALP_SOC_DRP_AI 0
#define ALP_SOC_HELIUM_MVE 1
#define ALP_SOC_NEON 1
#define ALP_SOC_GPU2D 0
#define ALP_SOC_DAVE2D 0
#define ALP_SOC_CRYPTOCELL 1
#define ALP_SOC_INLINE_AES 1
#define ALP_SOC_CAU 0
#define ALP_SOC_DMA2D 1
#define ALP_SOC_NPU_ARENA_SRAM_KIB 0

#elif defined(CONFIG_ALP_SOC_ALIF_ENSEMBLE_E6)
/* alif:ensemble:e6 */
#define ALP_SOC_REF_STR "alif:ensemble:e6"
#define ALP_SOC_I2C_COUNT 0
#define ALP_SOC_SPI_COUNT 0
#define ALP_SOC_UART_COUNT 0
#define ALP_SOC_I2S_COUNT 0
#define ALP_SOC_PDM_COUNT 0
#define ALP_SOC_ADC_COUNT 0
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_DAC_COUNT 0
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_CAN_COUNT 0
#define ALP_SOC_CAN_FD_SUPPORTED 0
#define ALP_SOC_RTC_COUNT 0
#define ALP_SOC_WDT_COUNT 0
#define ALP_SOC_QENC_COUNT 0
#define ALP_SOC_TIMER_COUNT 0
#define ALP_SOC_PWM_COUNT 0
#define ALP_SOC_ETHERNET_COUNT 0
#define ALP_SOC_USB_COUNT 0
#define ALP_SOC_MIPI_CSI_COUNT 0
#define ALP_SOC_MIPI_DSI_COUNT 0
#define ALP_SOC_XSPI_DMA 1
#define ALP_SOC_HEXSPI_DMA 0
#define ALP_SOC_EMMC_DMA 0
#define ALP_SOC_QUADSPI_DMA 0
#define ALP_SOC_DRP_AI 0
#define ALP_SOC_HELIUM_MVE 1
#define ALP_SOC_NEON 1
#define ALP_SOC_GPU2D 1
#define ALP_SOC_DAVE2D 1
#define ALP_SOC_CRYPTOCELL 1
#define ALP_SOC_INLINE_AES 1
#define ALP_SOC_CAU 0
#define ALP_SOC_DMA2D 1
#define ALP_SOC_NPU_ARENA_SRAM_KIB 0

#elif defined(CONFIG_ALP_SOC_ALIF_ENSEMBLE_E7)
/* alif:ensemble:e7 */
#define ALP_SOC_REF_STR "alif:ensemble:e7"
#define ALP_SOC_I2C_COUNT 5
#define ALP_SOC_SPI_COUNT 5
#define ALP_SOC_UART_COUNT 9
#define ALP_SOC_I2S_COUNT 5
#define ALP_SOC_PDM_COUNT 8
#define ALP_SOC_ADC_COUNT 4
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS 24
#define ALP_SOC_DAC_COUNT 2
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS 12
#define ALP_SOC_CAN_COUNT 1
#define ALP_SOC_CAN_FD_SUPPORTED 1
#define ALP_SOC_RTC_COUNT 1
#define ALP_SOC_WDT_COUNT 4
#define ALP_SOC_QENC_COUNT 4
#define ALP_SOC_TIMER_COUNT 16
#define ALP_SOC_PWM_COUNT 12
#define ALP_SOC_ETHERNET_COUNT 1
#define ALP_SOC_USB_COUNT 1
#define ALP_SOC_MIPI_CSI_COUNT 1
#define ALP_SOC_MIPI_DSI_COUNT 1
#define ALP_SOC_XSPI_DMA 1
#define ALP_SOC_HEXSPI_DMA 0
#define ALP_SOC_EMMC_DMA 0
#define ALP_SOC_QUADSPI_DMA 0
#define ALP_SOC_DRP_AI 0
#define ALP_SOC_HELIUM_MVE 1
#define ALP_SOC_NEON 1
#define ALP_SOC_GPU2D 1
#define ALP_SOC_DAVE2D 1
#define ALP_SOC_CRYPTOCELL 1
#define ALP_SOC_INLINE_AES 1
#define ALP_SOC_CAU 0
#define ALP_SOC_DMA2D 1
#define ALP_SOC_NPU_ARENA_SRAM_KIB 0

#elif defined(CONFIG_ALP_SOC_ALIF_ENSEMBLE_E8)
/* alif:ensemble:e8 */
#define ALP_SOC_REF_STR "alif:ensemble:e8"
#define ALP_SOC_I2C_COUNT 6
#define ALP_SOC_SPI_COUNT 5
#define ALP_SOC_UART_COUNT 9
#define ALP_SOC_I2S_COUNT 5
#define ALP_SOC_PDM_COUNT 8
#define ALP_SOC_ADC_COUNT 4
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS 24
#define ALP_SOC_DAC_COUNT 2
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS 12
#define ALP_SOC_CAN_COUNT 1
#define ALP_SOC_CAN_FD_SUPPORTED 1
#define ALP_SOC_RTC_COUNT 1
#define ALP_SOC_WDT_COUNT 4
#define ALP_SOC_QENC_COUNT 4
#define ALP_SOC_TIMER_COUNT 16
#define ALP_SOC_PWM_COUNT 12
#define ALP_SOC_ETHERNET_COUNT 1
#define ALP_SOC_USB_COUNT 1
#define ALP_SOC_MIPI_CSI_COUNT 1
#define ALP_SOC_MIPI_DSI_COUNT 1
#define ALP_SOC_XSPI_DMA 0
#define ALP_SOC_HEXSPI_DMA 1
#define ALP_SOC_EMMC_DMA 0
#define ALP_SOC_QUADSPI_DMA 0
#define ALP_SOC_DRP_AI 0
#define ALP_SOC_HELIUM_MVE 1
#define ALP_SOC_NEON 1
#define ALP_SOC_GPU2D 1
#define ALP_SOC_DAVE2D 1
#define ALP_SOC_CRYPTOCELL 1
#define ALP_SOC_INLINE_AES 1
#define ALP_SOC_CAU 0
#define ALP_SOC_DMA2D 1
#define ALP_SOC_NPU_ARENA_SRAM_KIB 0

#elif defined(CONFIG_ALP_SOC_DEEPX_DX_M1)
/* deepx:dx:m1 */
#define ALP_SOC_REF_STR "deepx:dx:m1"
#define ALP_SOC_I2C_COUNT 1
#define ALP_SOC_SPI_COUNT 1
#define ALP_SOC_UART_COUNT 1
#define ALP_SOC_I2S_COUNT 0
#define ALP_SOC_PDM_COUNT 0
#define ALP_SOC_ADC_COUNT 0
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_DAC_COUNT 0
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_CAN_COUNT 0
#define ALP_SOC_CAN_FD_SUPPORTED 0
#define ALP_SOC_RTC_COUNT 0
#define ALP_SOC_WDT_COUNT 1
#define ALP_SOC_QENC_COUNT 0
#define ALP_SOC_TIMER_COUNT 0
#define ALP_SOC_PWM_COUNT 1
#define ALP_SOC_ETHERNET_COUNT 0
#define ALP_SOC_USB_COUNT 0
#define ALP_SOC_MIPI_CSI_COUNT 0
#define ALP_SOC_MIPI_DSI_COUNT 0
#define ALP_SOC_XSPI_DMA 0
#define ALP_SOC_HEXSPI_DMA 0
#define ALP_SOC_EMMC_DMA 0
#define ALP_SOC_QUADSPI_DMA 0
#define ALP_SOC_DRP_AI 0
#define ALP_SOC_HELIUM_MVE 0
#define ALP_SOC_NEON 0
#define ALP_SOC_GPU2D 0
#define ALP_SOC_DAVE2D 0
#define ALP_SOC_CRYPTOCELL 0
#define ALP_SOC_INLINE_AES 0
#define ALP_SOC_CAU 0
#define ALP_SOC_DMA2D 0
#define ALP_SOC_NPU_ARENA_SRAM_KIB 0

#elif defined(CONFIG_ALP_SOC_NXP_IMX9_IMX93)
/* nxp:imx9:imx93 */
#define ALP_SOC_REF_STR "nxp:imx9:imx93"
#define ALP_SOC_I2C_COUNT 0
#define ALP_SOC_SPI_COUNT 0
#define ALP_SOC_UART_COUNT 0
#define ALP_SOC_I2S_COUNT 0
#define ALP_SOC_PDM_COUNT 0
#define ALP_SOC_ADC_COUNT 0
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_DAC_COUNT 0
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_CAN_COUNT 0
#define ALP_SOC_CAN_FD_SUPPORTED 0
#define ALP_SOC_RTC_COUNT 0
#define ALP_SOC_WDT_COUNT 0
#define ALP_SOC_QENC_COUNT 0
#define ALP_SOC_TIMER_COUNT 0
#define ALP_SOC_PWM_COUNT 0
#define ALP_SOC_ETHERNET_COUNT 0
#define ALP_SOC_USB_COUNT 0
#define ALP_SOC_MIPI_CSI_COUNT 0
#define ALP_SOC_MIPI_DSI_COUNT 0
#define ALP_SOC_XSPI_DMA 0
#define ALP_SOC_HEXSPI_DMA 0
#define ALP_SOC_EMMC_DMA 1
#define ALP_SOC_QUADSPI_DMA 0
#define ALP_SOC_DRP_AI 0
#define ALP_SOC_HELIUM_MVE 0
#define ALP_SOC_NEON 1
#define ALP_SOC_GPU2D 0
#define ALP_SOC_DAVE2D 0
#define ALP_SOC_CRYPTOCELL 0
#define ALP_SOC_INLINE_AES 0
#define ALP_SOC_CAU 0
#define ALP_SOC_DMA2D 0
#define ALP_SOC_NPU_ARENA_SRAM_KIB 0

#elif defined(CONFIG_ALP_SOC_RENESAS_RZV2N_N44)
/* renesas:rzv2n:n44 */
#define ALP_SOC_REF_STR "renesas:rzv2n:n44"
#define ALP_SOC_I2C_COUNT 9
#define ALP_SOC_SPI_COUNT 3
#define ALP_SOC_UART_COUNT 10
#define ALP_SOC_I2S_COUNT 10
#define ALP_SOC_PDM_COUNT 6
#define ALP_SOC_ADC_COUNT 24
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS 12
#define ALP_SOC_DAC_COUNT 0
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS 0
#define ALP_SOC_CAN_COUNT 6
#define ALP_SOC_CAN_FD_SUPPORTED 1
#define ALP_SOC_RTC_COUNT 1
#define ALP_SOC_WDT_COUNT 4
#define ALP_SOC_QENC_COUNT 0
#define ALP_SOC_TIMER_COUNT 0
#define ALP_SOC_PWM_COUNT 0
#define ALP_SOC_ETHERNET_COUNT 0
#define ALP_SOC_USB_COUNT 1
#define ALP_SOC_MIPI_CSI_COUNT 2
#define ALP_SOC_MIPI_DSI_COUNT 1
#define ALP_SOC_XSPI_DMA 0
#define ALP_SOC_HEXSPI_DMA 0
#define ALP_SOC_EMMC_DMA 1
#define ALP_SOC_QUADSPI_DMA 0
#define ALP_SOC_DRP_AI 1
#define ALP_SOC_HELIUM_MVE 0
#define ALP_SOC_NEON 1
#define ALP_SOC_GPU2D 0
#define ALP_SOC_DAVE2D 0
#define ALP_SOC_CRYPTOCELL 0
#define ALP_SOC_INLINE_AES 0
#define ALP_SOC_CAU 0
#define ALP_SOC_DMA2D 0
#define ALP_SOC_NPU_ARENA_SRAM_KIB 0

#else /* No SoC selected — accept any config. */
#define ALP_SOC_REF_STR "unknown"
#define ALP_SOC_I2C_COUNT UINT16_MAX
#define ALP_SOC_SPI_COUNT UINT16_MAX
#define ALP_SOC_UART_COUNT UINT16_MAX
#define ALP_SOC_I2S_COUNT UINT16_MAX
#define ALP_SOC_PDM_COUNT UINT16_MAX
#define ALP_SOC_ADC_COUNT UINT16_MAX
#define ALP_SOC_ADC_MAX_RESOLUTION_BITS UINT16_MAX
#define ALP_SOC_DAC_COUNT UINT16_MAX
#define ALP_SOC_DAC_MAX_RESOLUTION_BITS UINT16_MAX
#define ALP_SOC_CAN_COUNT UINT16_MAX
#define ALP_SOC_CAN_FD_SUPPORTED UINT16_MAX
#define ALP_SOC_RTC_COUNT UINT16_MAX
#define ALP_SOC_WDT_COUNT UINT16_MAX
#define ALP_SOC_QENC_COUNT UINT16_MAX
#define ALP_SOC_TIMER_COUNT UINT16_MAX
#define ALP_SOC_PWM_COUNT UINT16_MAX
#define ALP_SOC_ETHERNET_COUNT UINT16_MAX
#define ALP_SOC_USB_COUNT UINT16_MAX
#define ALP_SOC_MIPI_CSI_COUNT UINT16_MAX
#define ALP_SOC_MIPI_DSI_COUNT UINT16_MAX
#define ALP_SOC_XSPI_DMA UINT16_MAX
#define ALP_SOC_HEXSPI_DMA UINT16_MAX
#define ALP_SOC_EMMC_DMA UINT16_MAX
#define ALP_SOC_QUADSPI_DMA UINT16_MAX
#define ALP_SOC_DRP_AI UINT16_MAX
#define ALP_SOC_HELIUM_MVE UINT16_MAX
#define ALP_SOC_NEON UINT16_MAX
#define ALP_SOC_GPU2D UINT16_MAX
#define ALP_SOC_DAVE2D UINT16_MAX
#define ALP_SOC_CRYPTOCELL UINT16_MAX
#define ALP_SOC_INLINE_AES UINT16_MAX
#define ALP_SOC_CAU UINT16_MAX
#define ALP_SOC_DMA2D UINT16_MAX
#define ALP_SOC_NPU_ARENA_SRAM_KIB UINT16_MAX

#endif

/* ---------------------------------------------------------------
 * Capability layer -- portable, SoM-agnostic.  Derived from the
 * active CONFIG_ALP_SOC_* selection via the macros above.
 *
 * Counts collapse to 0/1 via `> 0`, so ALP_HAS() is always a
 * constant expression and safe inside #if and static_assert.
 * --------------------------------------------------------------- */
#define ALP_CAP_HW_I2C (ALP_SOC_I2C_COUNT > 0)
#define ALP_CAP_HW_SPI (ALP_SOC_SPI_COUNT > 0)
#define ALP_CAP_HW_UART (ALP_SOC_UART_COUNT > 0)
#define ALP_CAP_HW_I2S (ALP_SOC_I2S_COUNT > 0)
#define ALP_CAP_HW_PDM (ALP_SOC_PDM_COUNT > 0)
#define ALP_CAP_HW_ADC (ALP_SOC_ADC_COUNT > 0)
#define ALP_CAP_HW_DAC (ALP_SOC_DAC_COUNT > 0)
#define ALP_CAP_HW_CAN (ALP_SOC_CAN_COUNT > 0)
#define ALP_CAP_HW_CAN_FD (ALP_SOC_CAN_FD_SUPPORTED)
#define ALP_CAP_HW_RTC (ALP_SOC_RTC_COUNT > 0)
#define ALP_CAP_HW_WDT (ALP_SOC_WDT_COUNT > 0)
#define ALP_CAP_HW_QENC (ALP_SOC_QENC_COUNT > 0)
#define ALP_CAP_HW_TIMER (ALP_SOC_TIMER_COUNT > 0)
#define ALP_CAP_HW_PWM (ALP_SOC_PWM_COUNT > 0)
#define ALP_CAP_HW_ETHERNET (ALP_SOC_ETHERNET_COUNT > 0)
#define ALP_CAP_HW_USB (ALP_SOC_USB_COUNT > 0)
#define ALP_CAP_HW_MIPI_CSI (ALP_SOC_MIPI_CSI_COUNT > 0)
#define ALP_CAP_HW_MIPI_DSI (ALP_SOC_MIPI_DSI_COUNT > 0)
#define ALP_CAP_XSPI_DMA (ALP_SOC_XSPI_DMA)
#define ALP_CAP_HEXSPI_DMA (ALP_SOC_HEXSPI_DMA)
#define ALP_CAP_EMMC_DMA (ALP_SOC_EMMC_DMA)
#define ALP_CAP_QUADSPI_DMA (ALP_SOC_QUADSPI_DMA)
#define ALP_CAP_NPU_DRPAI (ALP_SOC_DRP_AI)
#define ALP_CAP_HELIUM_MVE (ALP_SOC_HELIUM_MVE)
#define ALP_CAP_NEON (ALP_SOC_NEON)
#define ALP_CAP_GPU2D (ALP_SOC_GPU2D)
#define ALP_CAP_DAVE2D (ALP_SOC_DAVE2D)
#define ALP_CAP_CRYPTOCELL (ALP_SOC_CRYPTOCELL)
#define ALP_CAP_INLINE_AES (ALP_SOC_INLINE_AES)
#define ALP_CAP_CAU (ALP_SOC_CAU)
#define ALP_CAP_DMA2D (ALP_SOC_DMA2D)

#define ALP_HAS(cap) (ALP_CAP_##cap)

#endif /* ALP_SOC_CAPS_H */
