# Copyright (c) 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
#
# Model-gen step for aen-npu-inference.
#
# Vela-compiles an int8 .tflite for the AEN801's Ethos-U85 (256-MAC) and emits a
# C header (model.h) that embeds the *_vela.tflite as a byte array plus the
# tensor-arena placement attributes.  This mirrors the upstream tflm_ethosu
# sample's models/<name>/model.h convention (a Vela-compiled network as a C
# array + a TENSOR_ARENA_ATTR / MODEL_ATTR section macro) so the on-target main.c
# can hand the buffer straight to tflite::GetModel() and the Ethos-U op resolver.
#
# WHY a Vela pass (not the raw .tflite): the Ethos-U custom op only exists in a
# Vela-compiled model -- Vela fuses the supported subgraph into a single
# "ethos-u" custom operator carrying the NPU command stream + weights.  Feeding
# the raw .tflite would dispatch on the CPU reference kernels, NOT the NPU, so it
# would not prove NPU inference.  See the RESULT contract in src/main.c.
#
# Invoked from CMakeLists.txt at configure+build time:
#   python gen_model.py --vela <vela> --accel ethos-u85-256 \
#       --model <in.tflite> --build-dir <gen> --out <gen>/model.h
#
# DMA placement (the #1 bench risk -- see the overlay header): the M55-HE board's
# zephyr,sram is &dtcm, which the Ethos-U DMA cannot reach.  Both the model buffer
# and the tensor arena are therefore tagged into the "SRAM0" linker region (the
# global on-chip SRAM @0x02000000, declared by the SoC dtsi sram0 node's
# zephyr,memory-region = "SRAM0").  This is the analogue of the eth_dwmac
# DMA-buffers-in-sram0 + DCACHE=n finding.

import argparse
import os
import shutil
import subprocess
import sys


def vela_compile(vela: str, accel: str, model: str, out_dir: str,
                 config: str) -> str:
	"""Run Vela and return the path to the produced *_vela.tflite."""
	os.makedirs(out_dir, exist_ok=True)
	cmd = [
		vela,
		"--accelerator-config", accel,
	]
	# The Alif Vela system-config (ensemble_vela.ini) is ALIF PROPRIETARY and is
	# NOT redistributed by alp-sdk -- it is injected at build time from
	# alp-sdk-internal via the app's -DAEN_NPU_VELA_CONFIG cache var (see
	# CMakeLists.txt).  When supplied it declares the Ethos_U85_SRAM_* region
	# model the bench-validated E8 RTSS-HE runtime was matched against; when
	# absent Vela falls back to its built-in system-config (the command stream
	# will NOT match the bench).  Empty string -> omit the flag entirely.
	if config:
		cmd += ["--config", config]
	cmd += [
		# Sram_Only: the model + tensor arena both live in ONE region (SRAM0) on
		# this board.  Vela's default (Dedicated_Sram) splits weights into a
		# separate DRAM region the NPU then addresses -- which we do NOT have, so
		# the NPU job fails (ethosu_invoke returns status 1, BENCH-CONFIRMED on E8).
		# Single-region Sram_Only matches our SRAM0-only placement.
		"--memory-mode", "Sram_Only",
		"--output-dir", out_dir,
		model,
	]
	# Surface the exact command in the build log so a HIL operator can
	# reproduce the compile by hand.
	print("aen-npu-inference: vela:", " ".join(cmd), file=sys.stderr)
	subprocess.run(cmd, check=True)

	stem = os.path.splitext(os.path.basename(model))[0]
	vela_tflite = os.path.join(out_dir, stem + "_vela.tflite")
	if not os.path.isfile(vela_tflite):
		raise FileNotFoundError(
			"vela did not produce expected output: " + vela_tflite)
	return vela_tflite


def emit_header(vela_tflite: str, out_h: str, model_name: str,
                arena_bytes: int) -> None:
	"""Emit model.h: the Vela network as a C array + placement macros."""
	with open(vela_tflite, "rb") as f:
		data = f.read()

	lines = []
	lines.append("/*")
	lines.append(" * Copyright (c) 2026 Alp Lab AB")
	lines.append(" * SPDX-License-Identifier: Apache-2.0")
	lines.append(" *")
	lines.append(" * GENERATED by gen_model.py -- do not edit by hand.")
	lines.append(" * Source model : " + os.path.basename(model_name))
	lines.append(" * Vela output  : " + os.path.basename(vela_tflite))
	lines.append(" * Network bytes: " + str(len(data)))
	lines.append(" *")
	lines.append(" * The network + tensor arena are placed in the \"SRAM0\" linker")
	lines.append(" * region (global on-chip SRAM @0x02000000) because the Ethos-U")
	lines.append(" * DMA cannot reach the M55-HE DTCM that is the board's default")
	lines.append(" * zephyr,sram.  See gen_model.py + the board overlay header.")
	lines.append(" */")
	lines.append("")
	lines.append("#pragma once")
	lines.append("")
	lines.append("#include <stdint.h>")
	lines.append("#include <zephyr/devicetree.h>")
	lines.append("")
	lines.append("/* Embedded-model identity (printed on the RESULT line). */")
	lines.append("#define NETWORK_MODEL_NAME \"" + model_name + "\"")
	lines.append("")
	lines.append("/*")
	lines.append(" * Tensor-arena size.  tiny_int8 needs only a few hundred bytes;")
	lines.append(" * 256 KiB is a generous headroom that still fits comfortably in")
	lines.append(" * the 4 MiB SRAM0 bank, leaving room to swap in a larger real")
	lines.append(" * model later without re-tuning the placement.")
	lines.append(" */")
	lines.append("#define TENSOR_ARENA_SIZE " + str(arena_bytes))
	lines.append("")
	lines.append("/*")
	lines.append(" * DMA-reachable placement.  The Ethos-U reads the command stream +")
	lines.append(" * weights (the model) and the intermediate tensors (the arena) over")
	lines.append(" * its own AXI master, so BOTH must live in SRAM0, not DTCM.  16-byte")
	lines.append(" * alignment matches the NPU's access granularity.")
	lines.append(" */")
	lines.append("#define NPU_ALIGN 16")
	lines.append("#define MODEL_ATTR \\")
	lines.append("\t__aligned(NPU_ALIGN) \\")
	lines.append("\t__attribute__((section(\"SRAM0\")))")
	lines.append("#define TENSOR_ARENA_ATTR \\")
	lines.append("\t__aligned(NPU_ALIGN) \\")
	lines.append("\t__attribute__((section(\"SRAM0\")))")
	lines.append("")
	# CONST rodata array (correctly initialized, read-in-place from ITCM/flash).
	# It is deliberately NOT in the "SRAM0" custom section: Zephyr does not
	# init-copy zephyr,memory-region sections, so an *initialized* array placed
	# there is GARBAGE at runtime -> TFLM parses garbage -> bus fault (observed on
	# E8 bench, BFAR wild pointer).  main() memcpy's this const model into an
	# uninitialized SRAM0 buffer at startup so the Ethos-U DMA can reach it.  (The
	# tensor arena stays in SRAM0 -- uninitialized scratch needs no init-copy.)
	lines.append("const uint8_t networkModelData[] = {")

	# 12 bytes per line, hex, matches the upstream sample's density.
	for i in range(0, len(data), 12):
		chunk = data[i:i + 12]
		row = "\t" + " ".join("0x%02x," % b for b in chunk)
		lines.append(row)

	lines.append("};")
	lines.append("")
	lines.append("#define NETWORK_MODEL_LEN ((uint32_t)sizeof(networkModelData))")
	lines.append("")

	os.makedirs(os.path.dirname(out_h), exist_ok=True)
	with open(out_h, "w") as f:
		f.write("\n".join(lines))
	print("aen-npu-inference: wrote", out_h,
	      "(%d network bytes, arena %d B)" % (len(data), arena_bytes),
	      file=sys.stderr)


def main() -> int:
	ap = argparse.ArgumentParser()
	ap.add_argument("--vela", required=True, help="path to the vela executable")
	ap.add_argument("--accel", required=True, help="vela --accelerator-config")
	ap.add_argument("--model", required=True, help="input .tflite")
	ap.add_argument("--build-dir", required=True, help="vela output dir")
	ap.add_argument("--out", required=True, help="output model.h path")
	ap.add_argument("--name", default=None, help="embedded model name")
	ap.add_argument("--config", default="",
	                help="vela --config .ini path (Alif-proprietary "
	                     "ensemble_vela.ini from alp-sdk-internal; omitted if empty)")
	ap.add_argument("--arena-bytes", type=int, default=256 * 1024)
	args = ap.parse_args()

	if shutil.which(args.vela) is None and not os.path.isfile(args.vela):
		print("ERROR: vela not found at", args.vela, file=sys.stderr)
		return 2

	name = args.name or os.path.splitext(os.path.basename(args.model))[0]
	vela_tflite = vela_compile(args.vela, args.accel, args.model,
	                           args.build_dir, args.config)
	emit_header(vela_tflite, args.out, name, args.arena_bytes)
	return 0


if __name__ == "__main__":
	sys.exit(main())
