#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Secure-boot config emitters -- sysbuild.conf + the TF-M child-image overlay.

`emit_sysbuild_conf` renders the sysbuild.conf overlay from board.yaml's `boot:`
block (the MCUboot wiring); `emit_tfm_sysbuild_conf` renders the TF-M sysbuild
child-image overlay from `security.psa:`. Pure string templating off the parsed
BoardProject -- the leaf-most emit seam (#285), a sink the build-plan emitter
imports later.
"""

from __future__ import annotations

from .models import BoardProject


def emit_sysbuild_conf(project: BoardProject) -> str:
    """Emit the sysbuild.conf overlay for the project's `boot:` block.

    Returns a SB_CONFIG_*-style snippet the build wires into
    `build/alp_sysbuild.conf` (handed to the sysbuild image via
    `west build --sysbuild -- -DSB_CONF_FILE=<abs>`; `west build` has
    no `--sysbuild-config` flag).  Returns an empty string when the project
    does not declare a `boot:` block (the SDK's stock per-family
    defaults at zephyr/sysbuild/<family>/sysbuild.conf apply).
    """
    boot = project.boot or {}
    if not boot:
        return ""
    method = (boot.get("method") or "mcuboot").lower()
    if method == "none":
        return ("# Auto-generated from board.yaml `boot:` block.\n"
                "SB_CONFIG_BOOTLOADER_MCUBOOT=n\n")
    if method != "mcuboot":
        return ""

    lines: list[str] = [
        "# Auto-generated by scripts/alp_orchestrate.py from "
        "board.yaml `boot:`.",
        "# Drives the sysbuild MCUboot child image.  Customers who",
        "# omit `boot:` get the SDK's stock per-family defaults.",
        "",
        "SB_CONFIG_BOOTLOADER_MCUBOOT=y",
    ]
    sign = boot.get("signing") or {}
    algo = (sign.get("algorithm") or "").lower()
    algo_kc = {
        "ecdsa_p256": "SB_CONFIG_MCUBOOT_SIGNATURE_TYPE_ECDSA_P256=y",
        "rsa2048":    "SB_CONFIG_MCUBOOT_SIGNATURE_TYPE_RSA=y\n"
                      "SB_CONFIG_MCUBOOT_SIGNATURE_TYPE_RSA_LEN=2048",
        "rsa3072":    "SB_CONFIG_MCUBOOT_SIGNATURE_TYPE_RSA=y\n"
                      "SB_CONFIG_MCUBOOT_SIGNATURE_TYPE_RSA_LEN=3072",
        "ed25519":    "SB_CONFIG_MCUBOOT_SIGNATURE_TYPE_ED25519=y",
    }.get(algo)
    if algo_kc:
        lines.append(algo_kc)
    if sign.get("key_file"):
        lines.append(f'SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="{sign["key_file"]}"')
    slots = boot.get("slots") or {}
    primary = (slots.get("primary") or {}).get("size_kib")
    secondary = (slots.get("secondary") or {}).get("size_kib")
    if primary:
        lines.append(f"SB_CONFIG_BOOT_PRIMARY_PARTITION_SIZE={int(primary) * 1024}")
    if secondary:
        lines.append(f"SB_CONFIG_BOOT_SECONDARY_PARTITION_SIZE={int(secondary) * 1024}")
    swap = (boot.get("swap_algorithm") or "scratch").lower()
    swap_kc = {
        "scratch":   "SB_CONFIG_MCUBOOT_MODE_SWAP_USING_SCRATCH=y",
        "move":      "SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE=y",
        "overwrite": "SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=y",
    }.get(swap)
    if swap_kc:
        lines.append(swap_kc)
    if swap == "scratch" and boot.get("scratch_size_kib"):
        lines.append(f"SB_CONFIG_BOOT_SCRATCH_PARTITION_SIZE="
                     f"{int(boot['scratch_size_kib']) * 1024}")
    if boot.get("anti_rollback"):
        lines.append("SB_CONFIG_BOOT_COUNTERS_MCUBOOT=y")
    return "\n".join(lines) + "\n"


def emit_tfm_sysbuild_conf(project: BoardProject) -> str:
    """Emit the TF-M sysbuild child-image overlay for `security.psa:`.

    Returns a `SB_CONFIG_*` + `CONFIG_PSA_CRYPTO_*` snippet the build
    wires into `build/sysbuild/tfm/tfm.conf` (picked up automatically by
    sysbuild's per-image config convention from its `sysbuild/tfm/`
    path -- no command-line flag needed).  Returns an empty
    string when the project omits `security.psa:` or sets
    `tfm: false` -- PSA Crypto then runs entirely non-secure
    (mbedTLS-only) and no child image is built.

    The TF-M boundary lives on the same M55-HP core as the non-secure
    app via Armv8-M TrustZone-M; see ADR 0013.
    """
    security = project.security or {}
    psa = security.get("psa") or {}
    if not psa or not psa.get("tfm"):
        return ""

    # TF-M build type follows the project's MCUboot build_type when
    # set so the secure + bootloader artefacts ship the same flavour.
    # Default is Release; debug builds use MinSizeRel for parity with
    # the upstream sysbuild template.
    boot = project.boot or {}
    build_type = (boot.get("build_type") or "Release")
    if build_type.lower() == "debug":
        tfm_build_type = "Debug"
    elif build_type.lower() in ("minsizerel", "min_size_rel"):
        tfm_build_type = "MinSizeRel"
    elif build_type.lower() == "release":
        tfm_build_type = "Release"
    else:
        # Pass through verbatim if the customer set an exact CMake
        # build-type string we don't pre-canonicalise.
        tfm_build_type = build_type

    lines: list[str] = [
        "# Auto-generated by scripts/alp_orchestrate.py from "
        "board.yaml `security.psa:`.",
        "# Drives the sysbuild TF-M child image on the M55-HP core via "
        "Armv8-M TrustZone-M.",
        "# See docs/adr/0013-tfm-boundary-m55-hp-trustzone.md and "
        "docs/security-audit-plan.md.",
        "",
        "SB_CONFIG_TFM=y",
        f"SB_CONFIG_TFM_BUILD_TYPE={tfm_build_type}",
    ]

    persistent_slots = psa.get("persistent_slots")
    if persistent_slots is None:
        # Schema default mirrors v0.6: 16 slots.
        persistent_slots = 16
    lines.append(
        f"CONFIG_PSA_CRYPTO_PERSISTENT_SLOT_COUNT={int(persistent_slots)}"
    )

    its = psa.get("its_storage")
    if its:
        lines.append(f'CONFIG_PSA_CRYPTO_ITS_BACKING_STORE="{its}"')
    ps = psa.get("ps_storage")
    if ps:
        lines.append(f'CONFIG_PSA_CRYPTO_PS_BACKING_STORE="{ps}"')

    att_root = (psa.get("attestation_root") or "none").lower()
    if att_root == "optiga_trust_m":
        lines.append(
            "# Attestation root anchored in OPTIGA Trust M (on-module "
            "secure element).")
        lines.append(
            "# See src/security/optiga_trust_m_bridge.c for the "
            "PSA <-> OPTIGA bridge driver.")
        lines.append("CONFIG_ALP_SDK_PSA_ATTESTATION_OPTIGA=y")
    elif att_root == "tfm_internal":
        lines.append("CONFIG_ALP_SDK_PSA_ATTESTATION_TFM_INTERNAL=y")

    return "\n".join(lines) + "\n"
