/*
 * Copyright (c) 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * aen-npu-inference -- on-silicon FULL NPU inference on the E1M-AEN801 (Ensemble
 * E8, M55-HE).  A Vela-compiled int8 model runs through TFLM's MicroInterpreter,
 * whose Ethos-U custom-op resolver dispatches the fused subgraph onto the
 * Ethos-U85 (256-MAC) NPU.  This is the inference follow-up to
 * aen-npu-ethosu-regcheck (which proved the U85 is present + clocked,
 * ID=0x20007001, device_is_ready=1).
 *
 * WHAT THIS PROVES (and what it does NOT):
 *   It proves the full path: a Vela-compiled .tflite -> tflite::GetModel() ->
 *   MicroMutableOpResolver with AddEthosU() (registers the "ethos-u" custom op)
 *   -> MicroInterpreter::Invoke().  When the interpreter hits the fused Ethos-U
 *   op, the TFLM kernel (tensorflow/lite/micro/kernels/ethos_u/ethosu.cc) calls
 *   ethosu_invoke_v3() on the Arm Ethos-U core driver, which streams the command
 *   stream to the NPU and blocks on its IRQ until the NPU finishes.  A
 *   kTfLiteOk return + a populated output tensor is the "real inference ran on
 *   the NPU" evidence.
 *
 *   It does NOT validate model *accuracy* -- the embedded model is the in-tree
 *   FIXTURE tiny_int8.tflite (Vela reports 1 NPU op, 100% NPU, 8 MACs), chosen
 *   so the bench app is hermetic and small.  A real-model end-to-end (a person-
 *   detect / mobilenet int8 with a known expected argmax) is the documented
 *   follow-up: rebuild with -DAEN_NPU_MODEL=<real.tflite>; the RESULT contract
 *   below is model-agnostic.
 *
 * HOW WE OBSERVE (mirrors the regcheck dual-path):
 *   1. main() prints one RESULT PASS/FAIL line to the RAM console (read
 *      'ram_console_buf' over J-Link mem8, ASCII-decode).
 *   2. The same evidence is latched into file-scope globals (g_invoke_status,
 *      g_out_bytes, g_out_first[]) so it is readable by symbol over SWD even if
 *      the console were not captured.  volatile so the stores survive -O2.
 *
 * PASS gate:
 *   - the model schema version is accepted,
 *   - AllocateTensors() == kTfLiteOk (arena big enough, all ops resolved),
 *   - Invoke() == kTfLiteOk (the Ethos-U op dispatched + the NPU completed),
 *   - the output tensor is non-empty (bytes > 0) and not all-zero (the NPU
 *     actually wrote a result; an all-zero output on a non-trivial model would
 *     be the silent-failure signal we want to catch).
 *
 * DMA placement (the #1 bench risk): the model + arena live in SRAM0 (global
 * on-chip SRAM @0x02000000), NOT the M55-HE DTCM, because the NPU DMA cannot
 * reach DTCM.  The model gets its section via gen_model.py; the arena via the
 * TENSOR_ARENA_ATTR macro in the generated model.h (also "SRAM0").  Combined
 * with CONFIG_DCACHE=n, the CPU and NPU share a coherent view.  See the overlay.
 */

#include <cstdint>
#include <cstring>

#include <zephyr/kernel.h>
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/sys/printk.h>

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

/* Generated by gen_model.py: networkModelData[] (in SRAM0), NETWORK_MODEL_LEN,
 * NETWORK_MODEL_NAME, TENSOR_ARENA_SIZE, and the TENSOR_ARENA_ATTR placement
 * macro (also SRAM0). */
#include "model.h"

/* The Ethos-U node added by boards/alp_e1m_aen801_m55_he_ae822fa0e5597ls0_rtss_he.overlay. */
#define NPU_NODE DT_NODELABEL(ethosu_npu)

/*
 * Tensor arena -- DMA-reachable SRAM0, 16-byte aligned (NPU access granularity).
 * TENSOR_ARENA_ATTR resolves to __aligned(16) __attribute__((section("SRAM0"))).
 * This is the working memory the MicroInterpreter hands to both the CPU
 * reference kernels and the Ethos-U op; it MUST be NPU-reachable.
 */
TENSOR_ARENA_ATTR static uint8_t tensor_arena[TENSOR_ARENA_SIZE];

/*
 * DMA-reachable copy of the model.  networkModelData[] is const rodata (correctly
 * initialized, in ITCM/flash); the Ethos-U reads the fused command stream +
 * weights out of the model via its own AXI master, so the bytes it executes MUST
 * live in NPU-reachable SRAM0.  An *initialized* array placed directly in the
 * SRAM0 custom section is NOT init-copied by Zephyr (zephyr,memory-region
 * sections get no load-copy) -> garbage -> bus fault.  So keep the model in
 * rodata and memcpy it into this uninitialized SRAM0 buffer at startup.
 */
static uint8_t model_sram[NETWORK_MODEL_LEN] __aligned(NPU_ALIGN) __attribute__((section("SRAM0")));

/*
 * Latched evidence, readable by symbol over SWD independent of the RAM-console
 * decode.  volatile so the stores are not optimised away.
 */
volatile int      g_invoke_status = -1;    /* TfLiteStatus of Invoke()         */
volatile int      g_alloc_status  = -1;    /* TfLiteStatus of AllocateTensors  */
volatile uint32_t g_in_bytes      = 0;     /* input tensor size in bytes       */
volatile uint32_t g_out_bytes     = 0;     /* output tensor size in bytes      */
volatile uint8_t  g_out_first[16] = { 0 }; /* first output bytes (raw int8)    */
volatile int      g_argmax        = -1;    /* argmax over the output bytes     */

int main(void)
{
	printk("\n=== aen-npu-inference ===\n");
	printk("model      : %s (%u bytes)\n", NETWORK_MODEL_NAME, (unsigned)NETWORK_MODEL_LEN);
	printk(
	    "arena      : %u bytes @ SRAM0 (%p)\n", (unsigned)TENSOR_ARENA_SIZE, (void *)tensor_arena);

	/*
	 * The Arm Ethos-U core driver auto-instantiates the NPU device at
	 * POST_KERNEL (the arm,ethos-u node is status="okay").  Reaching main()
	 * with device_is_ready()==1 means ethosu_init() (incl. the NPU soft reset)
	 * completed -- a prerequisite for ethosu_invoke_v3() to succeed.
	 */
	const struct device *npu       = DEVICE_DT_GET(NPU_NODE);
	bool                 npu_ready = device_is_ready(npu);
	printk(
	    "npu ready  : %d (Ethos-U85 @0x%08x)\n", (int)npu_ready, (unsigned)DT_REG_ADDR(NPU_NODE));

	/* Stage the model into DMA-reachable SRAM0 (see model_sram comment). */
	memcpy(model_sram, networkModelData, NETWORK_MODEL_LEN);

	/* Verify the embedded model's schema version. */
	const tflite::Model *model = tflite::GetModel(model_sram);
	if (model->version() != TFLITE_SCHEMA_VERSION) {
		printk("RESULT FAIL: model schema %u != supported %d\n",
		       (unsigned)model->version(),
		       TFLITE_SCHEMA_VERSION);
		return 0;
	}

	/*
	 * Op resolver.  AddEthosU() registers the "ethos-u" custom op whose kernel
	 * dispatches onto the NPU; the handful of builtin ops cover anything Vela
	 * left in CPU-land (for this fixture Vela fused everything into one NPU op,
	 * but registering the common builtins keeps the app reusable for a larger
	 * real model without a rebuild of the resolver).  Bound = 8 ops.
	 */
	tflite::MicroMutableOpResolver<8> resolver;
	resolver.AddEthosU();
	resolver.AddReshape();
	resolver.AddConv2D();
	resolver.AddDepthwiseConv2D();
	resolver.AddFullyConnected();
	resolver.AddSoftmax();
	resolver.AddQuantize();
	resolver.AddDequantize();

	tflite::MicroInterpreter interpreter(model, resolver, tensor_arena, TENSOR_ARENA_SIZE);

	/* Allocate tensors out of the SRAM0 arena. */
	TfLiteStatus alloc = interpreter.AllocateTensors();
	g_alloc_status     = (int)alloc;
	if (alloc != kTfLiteOk) {
		printk("RESULT FAIL: AllocateTensors=%d (arena too small / op "
		       "unresolved)\n",
		       (int)alloc);
		return 0;
	}

	/*
	 * Feed a deterministic input: zero-fill the input tensor by its reported
	 * size.  We read the size from the interpreter rather than hard-coding it
	 * so the app works unchanged for a different model.  (int8 zero == the
	 * tensor's encoding of its zero-point-relative origin; a fixed, repeatable
	 * stimulus is all the bench needs to prove the pipeline.)
	 */
	TfLiteTensor *input = interpreter.input(0);
	g_in_bytes          = (uint32_t)input->bytes;
	memset(input->data.raw, 0, input->bytes);
	printk("input      : %u bytes (zero-filled)\n", (unsigned)input->bytes);

	/*
	 * Run inference.  When the interpreter reaches the fused Ethos-U op,
	 * ethosu.cc -> ethosu_invoke_v3() streams the command stream to the NPU and
	 * blocks on the NPU IRQ until completion.  kTfLiteOk == the NPU finished.
	 */
	TfLiteStatus invoke = interpreter.Invoke();
	g_invoke_status     = (int)invoke;
	if (invoke != kTfLiteOk) {
		printk("RESULT FAIL: Invoke=%d (NPU dispatch failed / timed out)\n", (int)invoke);
		return 0;
	}

	/*
	 * Read the output tensor.  Latch the first bytes + the argmax for the
	 * RESULT line and for the SWD symbol read.
	 */
	TfLiteTensor *output = interpreter.output(0);
	g_out_bytes          = (uint32_t)output->bytes;

	uint32_t n           = output->bytes < 16u ? output->bytes : 16u;
	int      best_i      = -1;
	int      best_v      = -128; /* int8 floor */
	bool     any_nonzero = false;
	for (uint32_t i = 0; i < output->bytes; i++) {
		int8_t v = (int8_t)output->data.int8[i];
		if (i < n) {
			g_out_first[i] = (uint8_t)v;
		}
		if (v != 0) {
			any_nonzero = true;
		}
		if (v > best_v) {
			best_v = v;
			best_i = (int)i;
		}
	}
	g_argmax = best_i;

	printk("output     : %u bytes, argmax=%d (val=%d), first[0..%u]=",
	       (unsigned)output->bytes,
	       best_i,
	       best_v,
	       (unsigned)(n ? n - 1 : 0));
	for (uint32_t i = 0; i < n; i++) {
		printk("%02x ", g_out_first[i]);
	}
	printk("\n");

	/*
	 * PASS = inference completed AND the NPU actually produced a result.
	 * any_nonzero guards the silent-failure case (an all-zero output despite a
	 * kTfLiteOk would mean the NPU did not really write the tensor).
	 */
	bool ok = (invoke == kTfLiteOk) && (output->bytes > 0) && any_nonzero;
	if (ok) {
		printk("RESULT PASS: NPU inference complete -- model=%s "
		       "Invoke=OK out_bytes=%u argmax=%d npu_ready=%d\n",
		       NETWORK_MODEL_NAME,
		       (unsigned)output->bytes,
		       best_i,
		       (int)npu_ready);
	} else {
		printk("RESULT FAIL: Invoke=%d out_bytes=%u nonzero=%d "
		       "npu_ready=%d -- output not populated\n",
		       (int)invoke,
		       (unsigned)output->bytes,
		       (int)any_nonzero,
		       (int)npu_ready);
	}

	return 0;
}
