/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * microros-ros2-v2n / linux -- alp-microros-bridge, the Cortex-A55 half.
 *
 * WHAT IT IS
 *   A ~100-line forwarder between two datagram transports:
 *
 *     M33 micro-ROS client  <-- RPMsg (<alp/rpc.h>, method "xrce") -->  this bridge
 *     this bridge           <-- UDP (127.0.0.1:8888)               -->  micro-ROS agent
 *
 *   The micro-ROS agent is UNMODIFIED: it believes it is talking to a
 *   micro-ROS client over its stock `udp4` transport.  Only this bridge
 *   knows the client is really a Cortex-M33 behind a shared-memory mailbox.
 *   Design rationale: docs/adr/0035-micro-ros-cross-core-transport.md
 *   (Option B).
 *
 * THE CHANNEL
 *   Opened exactly like ../../rpmsg-v2n/linux/src/main.c: the M33 always
 *   listens on fixed rpmsg endpoint 1024 (see that file's header for why the
 *   generated endpoint ids are not used), src_ept = 0 means RPMSG_ADDR_ANY.
 *   <alp/rpc.h> frames each message as `<method>\0<bytes>`; XRCE datagrams
 *   travel under the method "xrce".
 *
 * WHY A "hello"
 *   The M33 is the rpmsg slave: it can only reply to an address it has
 *   already seen a frame from.  So the bridge sends an (empty) "hello" at
 *   start-up and whenever the UDP side has been quiet for a second; the M33
 *   treats any frame as "peer is alive" and drops non-"xrce" methods.  The
 *   idle re-hello also re-teaches a rebooted M33 our address.
 *
 * WHAT IT DOES NOT DO
 *   No fragmentation: RPMsg carries at most 491 payload bytes per datagram
 *   (496-byte buffer minus the 5-byte method header), so datagrams larger
 *   than BRIDGE_MTU are dropped with a log line.  The XRCE client MTU must be
 *   configured to fit; see README.md.
 *
 * Usage: alp-microros-bridge [agent-ip [agent-udp-port]]   (127.0.0.1 8888)
 */

#include <arpa/inet.h>
#include <errno.h>
#include <poll.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

#include <alp/rpc.h>
#include <alp/system_ipc.h> /* generated by alp_orchestrate/ -- channel name + mailbox id */

/* The M33 responder's fixed rpmsg endpoint (APP_EPT_ADDR in m33_sm/src/rpmsg_link.c). */
#define M33_RPMSG_EPT_ADDR 1024u

/* 496-byte rpmsg buffer - 5-byte "xrce\0" method header. */
#define BRIDGE_MTU 491u

#define HELLO_PERIOD_MS 1000

static volatile sig_atomic_t stop;

static void on_signal(int sig)
{
	(void)sig;
	stop = 1;
}

/* M33 -> agent.  Runs on <alp/rpc.h>'s receive thread; send() on a socket is
 * thread-safe, so no locking is needed against the main loop below. */
static void on_xrce_from_m33(const void *payload, size_t len, void *user)
{
	int fd = *(int *)user;

	if (send(fd, payload, len, 0) < 0) {
		/* Agent not running yet (ECONNREFUSED on a connected UDP socket):
		 * XRCE retransmits, so dropping is the right thing. */
		fprintf(stderr, "[bridge] M33 -> agent: send failed: %s\n", strerror(errno));
	}
}

int main(int argc, char **argv)
{
	const char *host = argc > 1 ? argv[1] : "127.0.0.1";
	int         port = argc > 2 ? atoi(argv[2]) : 8888;

	signal(SIGINT, on_signal);
	signal(SIGTERM, on_signal);

	/* UDP socket "connected" to the agent: send()/recv() then only see that
	 * peer, and the agent's replies come back to this socket's ephemeral port. */
	int                fd    = socket(AF_INET, SOCK_DGRAM, 0);
	struct sockaddr_in agent = { .sin_family = AF_INET, .sin_port = htons((uint16_t)port) };
	if (fd < 0 || inet_pton(AF_INET, host, &agent.sin_addr) != 1 ||
	    connect(fd, (struct sockaddr *)&agent, sizeof agent) != 0) {
		fprintf(stderr, "[bridge] cannot set up UDP to %s:%d: %s\n", host, port, strerror(errno));
		return 1;
	}

	const alp_rpc_config_t cfg = {
		.name    = ALP_IPC_ALP_DEFAULT_RPMSG_NAME,
		.src_ept = 0u, /* RPMSG_ADDR_ANY; the M33 learns it from our first frame */
		.dst_ept = M33_RPMSG_EPT_ADDR,
		.mbox_ch = ALP_IPC_ALP_DEFAULT_RPMSG_MBOX_CH,
	};
	alp_rpc_channel_t *ch = alp_rpc_open(&cfg);
	if (ch == NULL) {
		fprintf(stderr, "[bridge] alp_rpc_open failed: last_err=%d\n", (int)alp_last_error());
		return 1;
	}
	if (alp_rpc_subscribe(ch, "xrce", on_xrce_from_m33, &fd) != ALP_OK) {
		fprintf(stderr, "[bridge] alp_rpc_subscribe failed\n");
		alp_rpc_close(ch);
		return 1;
	}
	printf("[bridge] RPMsg <-> udp4 %s:%d, Ctrl-C to stop\n", host, port);

	(void)alp_rpc_send(ch, "hello", NULL, 0);

	/* Agent -> M33: wait for a datagram from the agent; on a quiet second,
	 * say hello again (see file header). */
	while (!stop) {
		struct pollfd p = { .fd = fd, .events = POLLIN };
		int           n = poll(&p, 1, HELLO_PERIOD_MS);

		if (n == 0) {
			(void)alp_rpc_send(ch, "hello", NULL, 0);
			continue;
		}
		if (n < 0 || !(p.revents & POLLIN)) {
			if (n < 0 && errno != EINTR) {
				usleep(100 * 1000); /* POLLERR from a refused UDP send: back off */
			}
			continue;
		}

		unsigned char buf[2048];
		ssize_t       len = recv(fd, buf, sizeof buf, 0);
		if (len <= 0) {
			continue; /* ECONNREFUSED from an earlier send: not fatal */
		}
		if ((size_t)len > BRIDGE_MTU) {
			fprintf(stderr,
			        "[bridge] agent -> M33: %zd B > %u B RPMsg MTU, dropped\n",
			        len,
			        BRIDGE_MTU);
			continue;
		}
		if (alp_rpc_send(ch, "xrce", buf, (size_t)len) != ALP_OK) {
			fprintf(stderr,
			        "[bridge] agent -> M33: alp_rpc_send failed (last_err=%d)\n",
			        (int)alp_last_error());
		}
	}

	alp_rpc_close(ch);
	close(fd);
	return 0;
}
