/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * rpmsg-imx93 -- Cortex-A55 / Yocto-Linux consumer.
 *
 * Subscribes to the `temperature` method published by the M33
 * producer (see ../../m33/src/main.c) and prints each sample to
 * stdout.
 */

#include <stdio.h>
#include <stdatomic.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>

#include <alp/rpc.h>
#include <alp/system_ipc.h> /* generated by alp_orchestrate.py */

#define DRAIN_COUNT 4u

static atomic_uint g_received;

static void on_temperature(const void *payload, size_t len, void *user)
{
	(void)user;
	if (len != sizeof(float)) {
		printf("[a55]   short payload (%zu)\n", len);
		return;
	}
	float c;
	memcpy(&c, payload, sizeof c);
	const unsigned n = atomic_fetch_add(&g_received, 1u);
	printf("[a55] recv temperature[%u]=%.1f\n", n, (double)c);
}

int main(void)
{
	printf("[a55] rpmsg-imx93 consumer coming up\n");

	const alp_rpc_config_t cfg = {
		.name    = ALP_IPC_ALP_DEFAULT_RPMSG_NAME,
		.src_ept = ALP_IPC_ALP_DEFAULT_RPMSG_DST_EPT,
		.dst_ept = ALP_IPC_ALP_DEFAULT_RPMSG_SRC_EPT,
		.mbox_ch = ALP_IPC_ALP_DEFAULT_RPMSG_MBOX_CH,
	};
	alp_rpc_channel_t *ch = alp_rpc_open(&cfg);
	if (ch == NULL) {
		printf("[a55]   alp_rpc_open failed: last_err=%d\n", (int)alp_last_error());
		return 1;
	}

	if (alp_rpc_subscribe(ch, "temperature", on_temperature, NULL) != ALP_OK) {
		printf("[a55]   alp_rpc_subscribe failed: last_err=%d\n", (int)alp_last_error());
		alp_rpc_close(ch);
		return 1;
	}

	for (int i = 0; i < 100 && atomic_load(&g_received) < DRAIN_COUNT; ++i) {
		usleep(100 * 1000);
	}

	alp_rpc_close(ch);
	printf("[rpmsg-imx93] done\n");
	return 0;
}
