/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * rpmsg-imx93 -- Cortex-A55 / Yocto-Linux consumer.
 *
 * Subscribes to the `temperature` method published by the M33
 * producer (see ../../m33/src/main.c) and prints each sample to
 * stdout.
 */

#include <stdio.h>
#include <stdatomic.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>

#include <alp/rpc.h>
#include <alp/system_ipc.h> /* generated by alp_orchestrate/ */

/* Matches the M33 producer's SAMPLE_BURST -- how many samples we expect
 * before giving up, so the demo (and the twister harness) terminates
 * instead of blocking forever if the producer side never comes up. */
#define DRAIN_COUNT 4u

/* Written from on_temperature() (the SDK's RX worker thread) and read from
 * main()'s poll loop below; atomic because those are two different threads
 * of control with no other synchronisation between them. */
static atomic_uint g_received;

static void on_temperature(const void *payload, size_t len, void *user)
{
	(void)user;
	/* The payload is a single raw float -- no shared header enforces
	 * this shape across the M33/A55 language boundary, so a producer
	 * mismatch is caught here instead of silently misread. */
	if (len != sizeof(float)) {
		printf("[a55]   short payload (%zu)\n", len);
		return;
	}
	float c;
	memcpy(&c, payload, sizeof c);
	const unsigned n = atomic_fetch_add(&g_received, 1u);
	printf("[a55] recv temperature[%u]=%.1f\n", n, (double)c);
}

int main(void)
{
	printf("[a55] rpmsg-imx93 consumer coming up\n");

	/* Endpoints are mirrored relative to the producer's config: this
	 * side's src is the producer's dst and vice versa, so both ends
	 * converge on the same pair of RPMsg endpoint ids from the one
	 * generated <alp/system_ipc.h> contract. */
	const alp_rpc_config_t cfg = {
		.name    = ALP_IPC_ALP_DEFAULT_RPMSG_NAME,
		.src_ept = ALP_IPC_ALP_DEFAULT_RPMSG_DST_EPT,
		.dst_ept = ALP_IPC_ALP_DEFAULT_RPMSG_SRC_EPT,
		.mbox_ch = ALP_IPC_ALP_DEFAULT_RPMSG_MBOX_CH,
	};
	alp_rpc_channel_t *ch = alp_rpc_open(&cfg);
	if (ch == NULL) {
		/* Common cause: the M33 producer hasn't reached its
		 * alp_rpc_open() yet, so the name-service handshake this call
		 * retries internally never completes within its timeout. */
		printf("[a55]   alp_rpc_open failed: last_err=%d\n", (int)alp_last_error());
		return 1;
	}

	if (alp_rpc_subscribe(ch, "temperature", on_temperature, NULL) != ALP_OK) {
		printf("[a55]   alp_rpc_subscribe failed: last_err=%d\n", (int)alp_last_error());
		alp_rpc_close(ch);
		return 1;
	}

	/* Poll instead of block: on_temperature() runs on the SDK's own RX
	 * worker, so main() just waits for DRAIN_COUNT samples to land or
	 * for the 10 s bound (100 * 100 ms) to expire, whichever is first. */
	for (int i = 0; i < 100 && atomic_load(&g_received) < DRAIN_COUNT; ++i) {
		usleep(100 * 1000);
	}

	alp_rpc_close(ch);
	printf("[rpmsg-imx93] done\n");
	return 0;
}
