/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * rpmsg-imx93 -- Cortex-A55 / Yocto-Linux consumer (NXP i.MX93).
 *
 * CONSUMER half of a dual-core demo. The M33 core runs the Zephyr PRODUCER
 * (../../m33/src/main.c); this Linux user-space binary subscribes to the
 * `temperature` event it publishes and prints each sample to stdout.
 *
 * What it teaches:
 *   - The SAME portable <alp/rpc.h> surface serves a Linux process here and the
 *     Zephyr firmware on the M33 -- the kernel's rpmsg char device on this end
 *     and OpenAMP on the other are hidden behind one API.
 *   - Endpoint ids and the mailbox channel are generated into
 *     <alp/system_ipc.h> from board.yaml's `ipc:` block (alp_orchestrate.py),
 *     so the two slices never drift apart across rebuilds.
 *   - The payload is opaque: here a bare float temperature memcpy'd into the
 *     RPMsg frame and length-checked on arrival.
 */

#include <stdio.h>
#include <stdatomic.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>

#include <alp/rpc.h>
#include <alp/system_ipc.h> /* generated by alp_orchestrate.py */

/* Exit after this many samples so a CI smoke test / systemd unit can latch the
 * run instead of blocking forever on an open subscription. */
#define DRAIN_COUNT 4u

static atomic_uint g_received;

/* Receive callback. RPMsg hands us an opaque (payload,len); a length that is not
 * exactly sizeof(float) means a producer/consumer wire mismatch, so reject it
 * before copying the value out. */
static void on_temperature(const void *payload, size_t len, void *user)
{
	(void)user;
	if (len != sizeof(float)) {
		printf("[a55]   short payload (%zu)\n", len);
		return;
	}
	float c;
	memcpy(&c, payload, sizeof c);
	const unsigned n = atomic_fetch_add(&g_received, 1u);
	printf("[a55] recv temperature[%u]=%.1f\n", n, (double)c);
}

int main(void)
{
	printf("[a55] rpmsg-imx93 consumer coming up\n");

	/* Endpoint ids are CROSSED relative to the producer -- our src is the M33's
	 * dst and vice-versa -- so each side's "destination" names the other's
	 * "source". The values themselves come straight from the generated header. */
	const alp_rpc_config_t cfg = {
		.name    = ALP_IPC_ALP_DEFAULT_RPMSG_NAME,
		.src_ept = ALP_IPC_ALP_DEFAULT_RPMSG_DST_EPT,
		.dst_ept = ALP_IPC_ALP_DEFAULT_RPMSG_SRC_EPT,
		.mbox_ch = ALP_IPC_ALP_DEFAULT_RPMSG_MBOX_CH,
	};
	alp_rpc_channel_t *ch = alp_rpc_open(&cfg);
	if (ch == NULL) {
		/* No rpmsg device: native_sim has no real link; on hardware the M33 peer
		 * / remoteproc node isn't online yet. */
		printf("[a55]   alp_rpc_open failed: last_err=%d\n", (int)alp_last_error());
		return 1;
	}

	/* Bind the callback to the "temperature" method before samples arrive; the
	 * framing layer dispatches each matching frame to on_temperature. */
	if (alp_rpc_subscribe(ch, "temperature", on_temperature, NULL) != ALP_OK) {
		printf("[a55]   alp_rpc_subscribe failed: last_err=%d\n", (int)alp_last_error());
		alp_rpc_close(ch);
		return 1;
	}

	/* Poll up to ~10 s for the producer's burst. A real service loops forever;
	 * the demo bounds the wait so CI can observe a clean finish. */
	for (int i = 0; i < 100 && atomic_load(&g_received) < DRAIN_COUNT; ++i) {
		usleep(100 * 1000);
	}

	alp_rpc_close(ch);
	printf("[rpmsg-imx93] done\n");
	return 0;
}
