/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */
/* Generated file; do not hand-format -- regenerate from device_status.proto. */
/* clang-format off */

#include "device_status.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DeviceStatus, DeviceStatus, AUTO)



