/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_DEVICE_STATUS_PB_H_INCLUDED
#define PB_DEVICE_STATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DeviceStatus {
    int32_t uptime_s;
    /* Fixed max_size -> nanopb emits a plain `char[17]` field (16 chars +
 NUL), not a pb_callback_t.  No heap, no callback plumbing -- the
 struct is fully static, which is what you want on an M-class target. */
    char device_id[17];
} DeviceStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DeviceStatus_init_default                {0, ""}
#define DeviceStatus_init_zero                   {0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceStatus_uptime_s_tag                1
#define DeviceStatus_device_id_tag               2

/* Struct field encoding specification for nanopb */
#define DeviceStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    uptime_s,          1) \
X(a, STATIC,   SINGULAR, STRING,   device_id,         2)
#define DeviceStatus_CALLBACK NULL
#define DeviceStatus_DEFAULT NULL

extern const pb_msgdesc_t DeviceStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DeviceStatus_fields &DeviceStatus_msg

/* Maximum encoded size of messages (where known) */
#define DEVICE_STATUS_PB_H_MAX_SIZE              DeviceStatus_size
#define DeviceStatus_size                        29

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
