# Copyright (c) 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
#
# Model-gen step for aen-npu-inference-alif -- the MATCHED-RUNTIME variant of
# aen-npu-inference.
#
# Vela-compiles an int8 .tflite for the AEN801's Ethos-U85 (256-MAC) USING THE
# ALIF SYSTEM-CONFIG, and emits a C header (model.h) that embeds the
# *_vela.tflite as a byte array plus the tensor-arena placement attributes.
#
# WHY THE ALIF SYSTEM-CONFIG (the fix vs the sibling aen-npu-inference):
#   The sibling app ran vela with only `--memory-mode Sram_Only` and the vela
#   internal-default system-config.  That defaults the command-stream base
#   addresses / region config to a generic memory model that does NOT match the
#   Alif E8 RTSS runtime + the hal_alif ethosu_address_remap (local_to_global),
#   so ethosu_invoke returned status 1 on E8.
#
#   This variant passes the ALIF Vela config (`--config <ensemble_vela.ini>`)
#   and selects the HE-core single-SRAM-region system-config
#   (`--system-config Ethos_U85_SRAM_Only`) with `--memory-mode Sram_Only`.
#   That is the system-config the Alif samples (samples/modules/executorch,
#   tflm_ethosu) compile against, so the command stream matches the silicon the
#   hal_alif Ethos-U callback is built for.  The .ini path is passed in from
#   CMake (AEN_NPU_VELA_CONFIG); see the app CMakeLists.txt.
#
# WHY a Vela pass (not the raw .tflite): the Ethos-U custom op only exists in a
# Vela-compiled model -- Vela fuses the supported subgraph into a single
# "ethos-u" custom operator carrying the NPU command stream + weights.  Feeding
# the raw .tflite would dispatch on the CPU reference kernels, NOT the NPU.
#
# DMA placement (the #1 bench risk -- see the overlay header): the M55-HE board's
# zephyr,sram is &dtcm, which the Ethos-U DMA cannot reach.  Both the model
# buffer and the tensor arena are tagged into the "SRAM0" linker region (the
# global on-chip SRAM @0x02000000).  SRAM0 is already a global system address,
# so local_to_global() is a no-op for it; the strong remap matters for any
# ITCM/DTCM-resident buffer and is linked regardless for correctness.

import argparse
import os
import subprocess
import sys


def vela_compile(vela: str, accel: str, model: str, out_dir: str,
                 config: str, system_config: str, memory_mode: str) -> str:
	"""Run Vela with the Alif system-config and return the *_vela.tflite path."""
	os.makedirs(out_dir, exist_ok=True)
	cmd = [
		vela,
		"--accelerator-config", accel,
	]
	# The Alif Vela config (ensemble_vela.ini) declares the Ethos_U85_SRAM_*
	# system-configs + the Sram_Only / Shared_Sram / Dedicated_Sram memory
	# modes.  Without --config, --system-config/--memory-mode below would not
	# resolve to the Alif region model and we fall back to vela internal-default.
	if config:
		cmd += ["--config", config]
	if system_config:
		cmd += ["--system-config", system_config]
	if memory_mode:
		cmd += ["--memory-mode", memory_mode]
	cmd += [
		"--output-dir", out_dir,
		model,
	]
	# Surface the exact command in the build log so a HIL operator can
	# reproduce the compile by hand.
	print("aen-npu-inference-alif: vela:", " ".join(cmd), file=sys.stderr)
	subprocess.run(cmd, check=True)

	stem = os.path.splitext(os.path.basename(model))[0]
	vela_tflite = os.path.join(out_dir, stem + "_vela.tflite")
	if not os.path.isfile(vela_tflite):
		raise FileNotFoundError(
			"vela did not produce expected output: " + vela_tflite)
	return vela_tflite


def emit_header(vela_tflite: str, out_h: str, model_name: str,
                arena_bytes: int) -> None:
	"""Emit model.h: the Vela network as a C array + placement macros."""
	with open(vela_tflite, "rb") as f:
		data = f.read()

	lines = []
	lines.append("/*")
	lines.append(" * Copyright (c) 2026 Alp Lab AB")
	lines.append(" * SPDX-License-Identifier: Apache-2.0")
	lines.append(" *")
	lines.append(" * GENERATED by gen_model.py -- do not edit by hand.")
	lines.append(" * Source model : " + os.path.basename(model_name))
	lines.append(" * Vela output  : " + os.path.basename(vela_tflite))
	lines.append(" * Network bytes: " + str(len(data)))
	lines.append(" *")
	lines.append(" * Compiled with the ALIF Vela system-config (Ethos_U85_SRAM_Only)")
	lines.append(" * so the command stream matches the E8 RTSS-HE runtime + the")
	lines.append(" * hal_alif ethosu_address_remap.  Network + arena are placed in the")
	lines.append(" * \"SRAM0\" linker region (global on-chip SRAM @0x02000000) -- the")
	lines.append(" * Ethos-U DMA cannot reach the M55-HE DTCM that is the board's")
	lines.append(" * default zephyr,sram.  See gen_model.py + the board overlay header.")
	lines.append(" */")
	lines.append("")
	lines.append("#pragma once")
	lines.append("")
	lines.append("#include <stdint.h>")
	lines.append("#include <zephyr/devicetree.h>")
	lines.append("")
	lines.append("/* Embedded-model identity (printed on the RESULT line). */")
	lines.append("#define NETWORK_MODEL_NAME \"" + model_name + "\"")
	lines.append("")
	lines.append("/*")
	lines.append(" * Tensor-arena size.  tiny_int8 needs only a few hundred bytes;")
	lines.append(" * 256 KiB is generous headroom that still fits comfortably in the")
	lines.append(" * 4 MiB SRAM0 bank, leaving room to swap in a larger real model")
	lines.append(" * later without re-tuning the placement.")
	lines.append(" */")
	lines.append("#define TENSOR_ARENA_SIZE " + str(arena_bytes))
	lines.append("")
	lines.append("/*")
	lines.append(" * DMA-reachable placement.  The Ethos-U reads the command stream +")
	lines.append(" * weights (the model) and the intermediate tensors (the arena) over")
	lines.append(" * its own AXI master, so BOTH must live in SRAM0, not DTCM.  16-byte")
	lines.append(" * alignment matches the NPU's access granularity.")
	lines.append(" */")
	lines.append("#define NPU_ALIGN 16")
	lines.append("#define MODEL_ATTR \\")
	lines.append("\t__aligned(NPU_ALIGN) \\")
	lines.append("\t__attribute__((section(\"SRAM0\")))")
	lines.append("#define TENSOR_ARENA_ATTR \\")
	lines.append("\t__aligned(NPU_ALIGN) \\")
	lines.append("\t__attribute__((section(\"SRAM0\")))")
	lines.append("")
	# CONST rodata array (correctly initialized, read-in-place from ITCM/flash).
	# Deliberately NOT in the "SRAM0" custom section: Zephyr does not init-copy
	# zephyr,memory-region sections, so an *initialized* array placed there is
	# GARBAGE at runtime.  main() memcpy's this const model into an uninitialized
	# SRAM0 buffer at startup so the Ethos-U DMA can reach valid bytes.
	lines.append("const uint8_t networkModelData[] = {")

	# 12 bytes per line, hex, matches the upstream sample's density.
	for i in range(0, len(data), 12):
		chunk = data[i:i + 12]
		row = "\t" + " ".join("0x%02x," % b for b in chunk)
		lines.append(row)

	lines.append("};")
	lines.append("")
	lines.append("#define NETWORK_MODEL_LEN ((uint32_t)sizeof(networkModelData))")
	lines.append("")

	os.makedirs(os.path.dirname(out_h), exist_ok=True)
	with open(out_h, "w") as f:
		f.write("\n".join(lines))
	print("aen-npu-inference-alif: wrote", out_h,
	      "(%d network bytes, arena %d B)" % (len(data), arena_bytes),
	      file=sys.stderr)


def main() -> int:
	ap = argparse.ArgumentParser()
	ap.add_argument("--vela", required=True, help="path to the vela executable")
	ap.add_argument("--accel", required=True, help="vela --accelerator-config")
	ap.add_argument("--model", required=True, help="input .tflite")
	ap.add_argument("--build-dir", required=True, help="vela output dir")
	ap.add_argument("--out", required=True, help="output model.h path")
	ap.add_argument("--name", default=None, help="embedded model name")
	ap.add_argument("--config", default="", help="vela --config .ini path")
	ap.add_argument("--system-config", default="", help="vela --system-config")
	ap.add_argument("--memory-mode", default="", help="vela --memory-mode")
	ap.add_argument("--arena-bytes", type=int, default=256 * 1024)
	args = ap.parse_args()

	if not os.path.isfile(args.vela) and not _which(args.vela):
		print("ERROR: vela not found at", args.vela, file=sys.stderr)
		return 2

	name = args.name or os.path.splitext(os.path.basename(args.model))[0]
	vela_tflite = vela_compile(args.vela, args.accel, args.model,
	                           args.build_dir, args.config,
	                           args.system_config, args.memory_mode)
	emit_header(vela_tflite, args.out, name, args.arena_bytes)
	return 0


def _which(prog: str):
	import shutil
	return shutil.which(prog)


if __name__ == "__main__":
	sys.exit(main())
