"""`alp init` -- scaffold a new project from a template."""

from __future__ import annotations

import shutil
from pathlib import Path

import click

REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATE_DIR = REPO_ROOT / "examples" / "peripheral-io" / "hello-world"
SOM_DIR = REPO_ROOT / "metadata" / "e1m_modules"
PRESET_DIR = REPO_ROOT / "metadata" / "boards"
STARTER_PERIPHERALS = ("uart", "gpio", "i2c", "spi", "pwm")


def _list_skus() -> list[str]:
    return sorted(
        p.stem for p in SOM_DIR.rglob("*.yaml") if p.stem.startswith("E1M-")
    )


def _list_presets() -> list[str]:
    return sorted(p.stem for p in PRESET_DIR.glob("*.yaml"))


def _interactive(
    som: str | None,
    preset: str | None,
    peripherals: tuple[str, ...] | None,
) -> tuple[str, str, list[str]]:
    import questionary

    if som is None:
        som = questionary.select(
            "Pick a SoM SKU:", choices=_list_skus()
        ).unsafe_ask()
    if preset is None:
        preset = questionary.select(
            "Pick a board preset:", choices=_list_presets()
        ).unsafe_ask()
    if peripherals is None:
        choices = list(STARTER_PERIPHERALS)
        peripherals = tuple(
            questionary.checkbox(
                "Starter peripherals (optional, space to toggle):",
                choices=choices,
            ).unsafe_ask()
            or []
        )
    return som, preset, list(peripherals)


def _scaffold(dest: Path, som: str, preset: str, peripherals: list[str]) -> None:
    shutil.copytree(TEMPLATE_DIR, dest)
    board_yaml = dest / "board.yaml"
    text = board_yaml.read_text(encoding="utf-8")
    text = text.replace("E1M-AEN801", som)
    text = text.replace("preset: e1m-evk", f"preset: {preset}")
    if peripherals:
        # Peripherals are an array of strings (not objects) per the board.yaml schema.
        stub = "\n".join(f"      - {p}" for p in peripherals)
        text = text.replace("    peripherals: []", "    peripherals:\n" + stub)
    board_yaml.write_text(text, encoding="utf-8")
    (dest / "README.md").write_text(
        f"# {dest.name}\n\nGenerated by `alp init`. See docs/tutorials/.\n",
        encoding="utf-8",
    )


@click.command(name="init", help="Scaffold a new Alp SDK project.")
@click.argument("name", type=str)
@click.option("--som", default=None, help="SoM SKU (e.g. E1M-AEN801).")
@click.option("--preset", default=None, help="Board preset (e.g. e1m-evk).")
@click.option(
    "--peripherals",
    default=None,
    callback=lambda _ctx, _param, value: (
        None
        if value is None
        else tuple(s.strip() for s in value.split(",") if s.strip())
    ),
    help="Comma-separated starter peripherals (uart,gpio,i2c,spi,pwm).",
)
def init_cmd(
    name: str,
    som: str | None,
    preset: str | None,
    peripherals: tuple[str, ...] | None,
) -> None:
    dest = Path.cwd() / name
    if dest.exists():
        click.echo(f"alp init: '{name}' already exists")
        raise SystemExit(1)

    if som is None or preset is None or peripherals is None:
        som, preset, periph_list = _interactive(som, preset, peripherals)
    else:
        periph_list = list(peripherals)

    _scaffold(dest, som, preset, periph_list)
    click.echo(f"Created {name}/ with som={som}, preset={preset}.")
    click.echo("Next: cd " + name + " && alp run")
