/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * rpmsg-aen -- Cortex-A32 / Yocto-Linux consumer (E1M-AEN801 / Alif Ensemble E8).
 *
 * CONSUMER half of a dual-core demo. The M55-HP core runs the Zephyr PRODUCER
 * (../../m55_hp/src/main.c); this Linux user-space binary subscribes to the
 * `imu_sample` event it publishes once per second and prints each sample to
 * stdout.
 *
 * What it teaches:
 *   - The SAME portable <alp/rpc.h> surface drives both ends of the link --
 *     Zephyr firmware on the M55 and a Linux process on the A32 -- so the
 *     application code never sees that one side is OpenAMP/RPMsg and this side
 *     is the kernel's rpmsg char device.
 *   - Endpoint ids and the mailbox channel are NOT hand-typed: they come from
 *     <alp/system_ipc.h>, which alp_orchestrate.py generates from the project's
 *     board.yaml `ipc:` block. Both slices read the same macros, so they cannot
 *     drift apart across rebuilds.
 *   - The wire format is a fixed-size packed struct memcpy'd into the RPMsg
 *     payload (no field-by-field serialisation); both sides agree on it via the
 *     shared declaration below.
 */

#include <stdio.h>
#include <stdatomic.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>

#include <alp/rpc.h>
#include <alp/system_ipc.h> /* generated by alp_orchestrate.py */

/* Wire format -- must stay byte-identical to the producer's copy in
 * ../../m55_hp/src/main.c. packed so there is no compiler padding for the two
 * cores to disagree about across the A32/M55 ABI boundary. */
typedef struct {
	uint32_t seq;
	float    accel_g[3];
	float    pressure_pa;
	float    temperature_c;
} __attribute__((packed)) imu_sample_t;

/* Exit after this many samples so a CI smoke test / systemd unit can latch the
 * run and shut down instead of blocking forever on an open subscription. */
#define DRAIN_COUNT 4u

static atomic_uint g_received;

/* Receive callback. RPMsg delivers an opaque, length-prefixed blob handed to us
 * as (payload,len); a length that is not exactly our struct means a
 * producer/consumer wire-format mismatch, so reject it before the memcpy. */
static void on_imu_sample(const void *payload, size_t len, void *user)
{
	(void)user;
	if (len != sizeof(imu_sample_t)) {
		printf("[a32]   short imu_sample (%zu)\n", len);
		return;
	}
	imu_sample_t s;
	memcpy(&s, payload, sizeof s);
	printf("[a32] imu_sample seq=%u T=%.1f P=%.1f Az=%.2fg\n",
	       (unsigned)s.seq,
	       (double)s.temperature_c,
	       (double)s.pressure_pa,
	       (double)s.accel_g[2]);
	atomic_fetch_add(&g_received, 1u);
}

int main(void)
{
	printf("[a32] rpmsg-aen consumer coming up\n");

	/* Open the consumer end. The endpoint ids are deliberately CROSSED versus
	 * the producer: our src_ept is the producer's dst_ept and vice-versa, so
	 * each side's "destination" names the other side's "source". Only the
	 * SRC/DST roles swap -- the values are the same generated macros both slices
	 * read. cacheable=true matches the producer (AEN shared memory is cacheable,
	 * spec §6.8). */
	const alp_rpc_config_t cfg = {
		.name      = ALP_IPC_ALP_DEFAULT_RPMSG_NAME,
		.src_ept   = ALP_IPC_ALP_DEFAULT_RPMSG_DST_EPT,
		.dst_ept   = ALP_IPC_ALP_DEFAULT_RPMSG_SRC_EPT,
		.mbox_ch   = ALP_IPC_ALP_DEFAULT_RPMSG_MBOX_CH,
		.cacheable = true,
	};
	alp_rpc_channel_t *ch = alp_rpc_open(&cfg);
	if (ch == NULL) {
		/* No rpmsg device: native_sim has no real link, and on hardware this
		 * means the M55 peer firmware / remoteproc binding isn't up yet. */
		printf("[a32]   alp_rpc_open failed: last_err=%d\n", (int)alp_last_error());
		return 1;
	}

	/* Register the callback before any sample arrives: subscribe binds our
	 * dst_ept to the "imu_sample" method name, and the framing layer dispatches
	 * each matching frame to on_imu_sample. */
	if (alp_rpc_subscribe(ch, "imu_sample", on_imu_sample, NULL) != ALP_OK) {
		printf("[a32]   alp_rpc_subscribe failed: last_err=%d\n", (int)alp_last_error());
		alp_rpc_close(ch);
		return 1;
	}

	/* Poll up to ~10 s (100 * 100 ms) for the producer's burst. A real service
	 * would run its event loop forever; the demo bounds the wait so CI can
	 * observe a clean finish. */
	for (int i = 0; i < 100 && atomic_load(&g_received) < DRAIN_COUNT; ++i) {
		usleep(100 * 1000);
	}

	alp_rpc_close(ch);
	printf("[rpmsg-aen] done\n");
	return 0;
}
