/*
 * Copyright 2026 ALP Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * rpmsg-aen -- Cortex-A32 / Yocto-Linux consumer.
 *
 * Subscribes to the `imu_sample` method published by the M55-HP
 * producer (see ../../m55_hp/src/main.c) and prints each sample
 * to stdout.  The wire format is a fixed-size struct memcpy'd
 * into the RPMsg payload; both sides agree on it via the shared
 * declaration below.
 */

#include <stdio.h>
#include <stdatomic.h>
#include <stdint.h>
#include <string.h>
#include <unistd.h>

#include <alp/rpc.h>
#include <alp/system_ipc.h> /* generated by alp_orchestrate.py */

typedef struct {
    uint32_t seq;
    float    accel_g[3];
    float    pressure_pa;
    float    temperature_c;
} __attribute__((packed)) imu_sample_t;

#define DRAIN_COUNT 4u

static atomic_uint g_received;

static void        on_imu_sample(const void *payload, size_t len, void *user)
{
    (void)user;
    if (len != sizeof(imu_sample_t)) {
        printf("[a32]   short imu_sample (%zu)\n", len);
        return;
    }
    imu_sample_t s;
    memcpy(&s, payload, sizeof s);
    printf("[a32] imu_sample seq=%u T=%.1f P=%.1f Az=%.2fg\n", (unsigned)s.seq,
           (double)s.temperature_c, (double)s.pressure_pa, (double)s.accel_g[2]);
    atomic_fetch_add(&g_received, 1u);
}

int main(void)
{
    printf("[a32] rpmsg-aen consumer coming up\n");

    const alp_rpc_config_t cfg = {
        .name      = ALP_IPC_ALP_DEFAULT_RPMSG_NAME,
        .src_ept   = ALP_IPC_ALP_DEFAULT_RPMSG_DST_EPT,
        .dst_ept   = ALP_IPC_ALP_DEFAULT_RPMSG_SRC_EPT,
        .mbox_ch   = ALP_IPC_ALP_DEFAULT_RPMSG_MBOX_CH,
        .cacheable = true,
    };
    alp_rpc_channel_t *ch = alp_rpc_open(&cfg);
    if (ch == NULL) {
        printf("[a32]   alp_rpc_open failed: last_err=%d\n", (int)alp_last_error());
        return 1;
    }

    if (alp_rpc_subscribe(ch, "imu_sample", on_imu_sample, NULL) != ALP_OK) {
        printf("[a32]   alp_rpc_subscribe failed: last_err=%d\n", (int)alp_last_error());
        alp_rpc_close(ch);
        return 1;
    }

    for (int i = 0; i < 100 && atomic_load(&g_received) < DRAIN_COUNT; ++i) {
        usleep(100 * 1000);
    }

    alp_rpc_close(ch);
    printf("[rpmsg-aen] done\n");
    return 0;
}
