#!/usr/bin/env python3
"""tools/genlogo.py -- a partner logo (PNG or SVG) -> an ARGB4444 C header for the HUD.

The HUD (src/hud/hud.c) draws an OPTIONAL partner logo, always on, from a
generated header named by the build (CMake -DTR_PARTNER_LOGO=<header>). With
no header nothing is drawn and the image is byte-identical. This tool makes
that header; the logo artwork and its header are the partner's trademark and
are NOT committed here -- keep them in a private repo and pass the path.

    python3 tools/genlogo.py LOGO.{png,svg} OUT.h [--box 106x48] [--source URL]

The logo is scaled to fit --box (keeping its aspect ratio, never upscaled past
the box), composited in premultiplied alpha (no dark fringes) and quantised to
ARGB4444, straight alpha: A[15:12] R[11:8] G[7:4] B[3:0] -- the HUD buffer's own
format (hud.h). OUT.h defines TR_PARTNER_LOGO_W / _H and tr_partner_logo[].

The default box fits the HUD's free left strip (hud.c PARTNER_BOX_W/H); hud.c
refuses a header bigger than that at compile time.

Needs Pillow + numpy; SVG input also needs `pip install resvg_py`.
"""
import argparse
import io
import os
import sys

import numpy as np
from PIL import Image

SS = 4  # supersampling per axis for the final box-filter downscale


def load(path, tw, th):
    """RGBA float array (premultiplied), rendered at SS x the fitted size."""
    if path.lower().endswith(".svg"):
        import resvg_py

        svg = open(path, "rb").read()
        probe = Image.open(io.BytesIO(bytes(resvg_py.svg_to_bytes(svg_string=svg.decode("utf-8")))))
        sw, sh = probe.size
    else:
        probe = Image.open(path).convert("RGBA")
        sw, sh = probe.size
    scale = min(tw / sw, th / sh, 1.0)
    w, h = max(1, round(sw * scale)), max(1, round(sh * scale))
    if path.lower().endswith(".svg"):
        big = Image.open(
            io.BytesIO(
                bytes(resvg_py.svg_to_bytes(svg_string=svg.decode("utf-8"), width=w * SS, height=h * SS))
            )
        ).convert("RGBA")
    else:
        big = probe.convert("RGBa").resize((w * SS, h * SS), Image.LANCZOS).convert("RGBA")
        big = Image.fromarray(np.asarray(big))
    return np.asarray(big, dtype=np.float64) / 255.0, w, h


def to_argb4444(rgba, w, h):
    a = rgba[..., 3:4]
    pre = np.concatenate([rgba[..., :3] * a, a], axis=-1)  # premultiplied
    box = pre.reshape(h, SS, w, SS, 4).mean(axis=(1, 3))
    alpha = box[..., 3]
    rgb = np.divide(box[..., :3], alpha[..., None], out=np.zeros_like(box[..., :3]), where=alpha[..., None] > 0)
    a4 = np.rint(alpha * 15).astype(np.uint16)
    c4 = np.rint(np.clip(rgb, 0, 1) * 15).astype(np.uint16)
    px = (a4 << 12) | (c4[..., 0] << 8) | (c4[..., 1] << 4) | c4[..., 2]
    px[a4 == 0] = 0  # a clear pixel carries no colour: the HUD skips alpha 0
    return px


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("logo")
    ap.add_argument("out")
    ap.add_argument("--box", default="106x48", help="max WxH in px (default 106x48)")
    ap.add_argument("--source", default="", help="where the artwork came from (recorded in the header)")
    a = ap.parse_args()
    tw, th = (int(v) for v in a.box.lower().split("x"))
    rgba, w, h = load(a.logo, tw, th)
    px = to_argb4444(rgba, w, h)
    o = [
        "/* clang-format off */",
        "/* GENERATED by tools/genlogo.py from %s, do not edit." % os.path.basename(a.logo),
    ]
    if a.source:
        o.append(" * Source: %s" % a.source)
    o += [
        " * ARGB4444 straight alpha, %d x %d px, row-major. Partner artwork: keep out of public repos. */" % (w, h),
        "#define TR_PARTNER_LOGO_W %d" % w,
        "#define TR_PARTNER_LOGO_H %d" % h,
        "static const uint16_t tr_partner_logo[TR_PARTNER_LOGO_W * TR_PARTNER_LOGO_H] = {",
    ]
    flat = px.reshape(-1)
    for i in range(0, len(flat), 12):
        o.append("\t" + ", ".join("0x%04X" % v for v in flat[i : i + 12]) + ",")
    o.append("};")
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(o) + "\n")
    print("genlogo: %s -> %s (%dx%d, %d px opaque-ish)" % (a.logo, a.out, w, h, int((px >> 12 != 0).sum())))


if __name__ == "__main__":
    sys.exit(main())
