# meta-alp-sdk: tighten the DX-M1 udev device-node permissions shipped
# by DEEPX's own dx-driver recipe.
#
# Upstream dx-driver_<PV>.bb installs
# ${sysconfdir}/udev/rules.d/99-dx-dma.rules with
# `KERNEL=="dxrt*", MODE="0666"` -- world-writable access to the DX-M1
# device node for any local user/process on the target.  Rewrite it to
# `KERNEL=="dxrt*", MODE="0660", GROUP="video"` (same group convention
# used elsewhere in this layer for restricted-but-shared device access)
# so only root + the `video` group can open the node.
#
# do_install:append (not a SRC_URI patch): the file is generated by
# upstream's own do_install, not shipped as a static source file we
# could patch -- appending after do_install and sed-ing the staged
# copy is the smallest correct hook.  Fails loudly (bbfatal) if the
# file or the exact upstream line is missing, so a future upstream
# rename/rewrite of this rule is caught at build time instead of
# silently leaving 0666 in the image.
#
# Lives under dynamic-layers/meta-deepx-m1/ (not a plain top-level
# bbappend) because dx-driver is DEEPX's OWN recipe, not one this
# layer defines: a plain bbappend has no matching recipe -- and is a
# hard BitBake parse error -- on any build that has not added
# meta-deepx-m1 to bblayers.conf.  BBFILES_DYNAMIC in
# meta-alp-sdk/conf/layer.conf gates this file to parse ONLY when the
# meta-deepx-m1 collection is present, so non-DEEPX builds stay clean.

do_install:append() {
    rules_file="${D}${sysconfdir}/udev/rules.d/99-dx-dma.rules"
    if [ ! -f "${rules_file}" ]; then
        bbfatal "dx-driver: expected udev rule ${rules_file} not found -- \
upstream dx-driver has likely changed its udev rule filename/path; \
update this bbappend's do_install:append to match."
    fi
    if ! grep -q 'KERNEL=="dxrt\*", MODE="0666"' "${rules_file}"; then
        bbfatal "dx-driver: expected upstream line \
'KERNEL==\"dxrt*\", MODE=\"0666\"' not found in ${rules_file} -- \
upstream dx-driver has likely changed this rule's wording; update \
this bbappend's sed pattern to match before relying on it."
    fi
    sed -i 's/KERNEL=="dxrt\*", MODE="0666"/KERNEL=="dxrt*", MODE="0660", GROUP="video"/' \
        "${rules_file}"
}
