CONFIG_ALP_SDK=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_UHC_DRIVER=y
CONFIG_DCACHE=n
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_ALP_SDK_CHIP_CC3501E=y
CONFIG_DMA=y
CONFIG_DMA_PL330_ALIF=y
CONFIG_DMA_ALIF_EVENT_ROUTER=y
CONFIG_SPI_DW_ALIF_USE_DMA=y
CONFIG_SPI_DW_ALIF_DMA_MIN_LEN=64
