#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Guard: every scripts/ and firmware/ write_text() of a repo-tree text
artifact passes newline="".

Path.write_text() translates every '\\n' to os.linesep on write. On a
Windows host that silently rewrites the whole file to CRLF; .gitattributes
normalizes it back to LF on `git add`, so the bug never reaches a commit and
never reds CI -- it just leaves the regenerated file permanently
whole-file-dirty in every working tree, burying the one line that actually
changed underneath a wall of line-ending noise. Fix: newline="" (write LF
verbatim; the caller's own text already uses '\\n').

A genuine tempfile/build/scratch/out-of-tree writer is exempt per call, not
per file: mark the call itself (or the line directly above it) with

    # write-text-newline-exempt: <reason>

A marker on one of the call's own physical lines may trail other code on
that line -- that is the normal single-line style. A marker on the line
directly above the call only counts if it is a *standalone* comment (the
`#` is the first non-whitespace token on that line): a comment trailing
some OTHER statement on the line above does not exempt an unmarked call
that happens to start on the next line.

A bare marker with no reason is a defect in the marker, not a pass -- it is
reported on its own. A `newline=` keyword must be the literal `""` or
`"\\n"`; `newline=None` -- the CRLF-translating default -- any other string
literal (`"\\r\\n"`, `"\\r"`), or any non-literal value (a variable, an
expression, an f-string) is flagged too. A `newline=` passed positionally or
only via `**kwargs` is invisible to this check (it only looks for a literal
`newline=` keyword) and is flagged the same way a missing one is.

Markers and calls are resolved from real `tokenize.COMMENT` tokens, not raw
line text, so a marker spelled inside a string literal or a docstring never
counts, and a marker trailing one call's line never leaks onto an unmarked
call on the next line. Files are read with `tokenize.open()`, which honours
a BOM or a PEP-263 `# -*- coding: ... -*-` declaration the same way CPython
itself does when it runs the file -- a file `ast.parse()` on raw
utf-8-decoded text would reject (BOM) or `bytes.decode("utf-8")` would raise
on (a non-utf-8 coding declaration) is still checked, not silently skipped.
A file that still fails to parse or decode is itself reported as a problem
instead of being skipped -- a write_text() call this gate can't see is not
the same as a write_text() call that's clean.

Line numbers throughout come from `tokenize`/`ast`, which -- like CPython
itself -- only ever break a physical line on '\\n'. This deliberately does
NOT use `str.splitlines()`, which also breaks on FF/VT/NEL/U+2028/U+2029:
using it here would silently shift every line number after such a
character and misfile markers.

Scope limit: this only matches the `.write_text()` attribute call. A repo-
tree writer using `open(path, "w")` (which translates '\\n' to os.linesep
identically) is not yet checked here.
"""
from __future__ import annotations

import argparse
import ast
import io
import sys
import tokenize
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

_MARKER = "write-text-newline-exempt"

# Trees scanned for a bare write_text() -- both hold committed, LF-pinned
# text artefacts regenerated by a Python script (scripts/*.py generators,
# firmware/*/tests/gen_*.py protocol-vector generators).
_SCAN_SUBDIRS = ("scripts", "firmware")

# A standalone comment's COMMENT token is preceded by one of these token
# types (or nothing at all, at the very start of the file); anything else
# means a real token sits before it on the same physical line, i.e. it
# trails other code.
_STANDALONE_PREDECESSORS = frozenset({
    None, tokenize.NL, tokenize.NEWLINE, tokenize.INDENT, tokenize.DEDENT,
})


def _comment_map(text: str) -> dict[int, tuple[str, bool]]:
    """Map physical line number -> (full comment text incl. '#', is this a
    standalone comment), built from real `tokenize.COMMENT` tokens only. A
    marker token that appears inside a string literal or docstring is
    invisible here, and the line numbers line up with `ast`'s (both count
    only '\\n' as a line break -- see the module docstring).

    "Standalone" means the `#` is the first non-whitespace token on its
    physical line -- i.e. the token immediately preceding the COMMENT token
    is NL/NEWLINE/INDENT/DEDENT (or there is no preceding token at all).
    Anything else (a real token right before it) means the comment trails
    other code on that same line.
    """
    comments: dict[int, tuple[str, bool]] = {}
    prev_type: int | None = None
    try:
        for tok in tokenize.generate_tokens(io.StringIO(text).readline):
            if tok.type == tokenize.COMMENT:
                standalone = prev_type in _STANDALONE_PREDECESSORS
                comments[tok.start[0]] = (tok.string, standalone)
            prev_type = tok.type
    except (tokenize.TokenError, IndentationError):
        pass
    return comments


def _marker_reason(
    node: ast.Call,
    node_idx: int,
    comments: dict[int, tuple[str, bool]],
    spans: list[tuple[int, int, int]],
) -> str | None:
    """Resolve the write-text-newline-exempt marker for one write_text()
    call.

    A marker comment binds to this call only if its line is one of the
    call's own physical lines (`node.lineno..node.end_lineno`) or the line
    directly above (`node.lineno - 1`), AND:

    - if the line is NOT one of the call's own lines (the "line above"
      case), the comment must be standalone -- a comment trailing some
      OTHER statement on that line is not "for" the call below it; and
    - that line does not fall inside the own span of some OTHER write_text()
      call in the file, UNLESS that other call's own span merely contains
      this call's own span (this call is nested inside it, or they share an
      identical span from being called on the same physical line) -- a call
      cannot be "blocked" by a span that wraps its own.

    Every candidate line is scanned and a reasoned marker wins over a bare
    one wherever it appears, so a stray bare marker elsewhere in the window
    doesn't shadow a correctly-reasoned one covering this call.

    Returns the stripped reason string ("" for a bare marker), or None if
    no marker binds to this call at all.
    """
    own_lo = node.lineno
    own_hi = node.end_lineno or node.lineno
    candidates = list(range(own_lo, own_hi + 1))
    if own_lo - 1 >= 1:
        candidates.append(own_lo - 1)

    found_bare = False
    for lineno in candidates:
        entry = comments.get(lineno)
        if entry is None:
            continue
        comment, standalone = entry
        if _MARKER not in comment:
            continue
        on_own_line = own_lo <= lineno <= own_hi
        if not on_own_line and not standalone:
            continue  # trails some OTHER statement on the line above
        if any(
            other_idx != node_idx
            and lo <= lineno <= hi
            and not (lo <= own_lo and hi >= own_hi)
            for other_idx, lo, hi in spans
        ):
            continue  # this line belongs to some OTHER call's own span
        idx = comment.find(_MARKER)
        rest = comment[idx + len(_MARKER):].lstrip()
        reason = rest[1:].strip() if rest.startswith(":") else ""
        if reason:
            return reason
        found_bare = True
    return "" if found_bare else None


def _describe_non_literal_newline(value: ast.expr) -> str:
    """Human-readable reason a `newline=...` value is not a bare `""`/`"\\n"`
    string literal -- names the actual value's class instead of pretending
    every non-literal is `None`."""
    if isinstance(value, ast.Constant):
        if value.value is None:
            return (
                "newline=None is the CRLF-translating default and "
                "silently defeats the guard"
            )
        return (
            f"newline=... is a literal {type(value.value).__name__} value, "
            f"not a str"
        )
    return (
        f"newline=... is a {type(value).__name__} expression, not a "
        f"literal, so this gate can't verify what it evaluates to"
    )


def find_problems(root: Path) -> list[str]:
    problems: list[str] = []
    py_files: list[Path] = []
    for sub in _SCAN_SUBDIRS:
        d = root / sub
        if d.is_dir():
            py_files.extend(d.rglob("*.py"))

    for path in sorted(py_files):
        rel = path.relative_to(root).as_posix()
        try:
            with tokenize.open(path) as f:
                text = f.read()
            tree = ast.parse(text, filename=str(path))
        except (SyntaxError, UnicodeDecodeError) as exc:
            problems.append(
                f"{rel}: could not parse this file to check its "
                f"write_text() calls ({type(exc).__name__}: {exc})"
            )
            continue

        calls = [
            node
            for node in ast.walk(tree)
            if isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "write_text"
        ]
        if not calls:
            continue

        comments = _comment_map(text)
        spans = [
            (idx, c.lineno, c.end_lineno or c.lineno)
            for idx, c in enumerate(calls)
        ]

        for idx, node in enumerate(calls):
            marker = _marker_reason(node, idx, comments, spans)
            if marker is not None:
                if marker:
                    continue
                problems.append(
                    f"{rel}:{node.lineno}: write-text-newline-exempt "
                    f"marker needs a reason -- "
                    f'"# write-text-newline-exempt: <reason>"'
                )
                continue

            newline_kw = next(
                (kw for kw in node.keywords if kw.arg == "newline"), None
            )
            if newline_kw is None:
                problems.append(
                    f'{rel}:{node.lineno}: write_text() without newline="" '
                    f"-- CRLF-on-Windows working-tree churn (see "
                    f"scripts/abi_snapshot.py for the rationale; if this "
                    f'path never lands in the repo tree, mark it "# '
                    f'write-text-newline-exempt: <reason>" instead; a '
                    f"newline=... passed positionally or only via "
                    f"**kwargs is invisible to this gate too -- pass it as "
                    f'a literal newline="" keyword)'
                )
            elif not (
                isinstance(newline_kw.value, ast.Constant)
                and isinstance(newline_kw.value.value, str)
            ):
                problems.append(
                    f"{rel}:{node.lineno}: write_text() newline=... is not "
                    f"a string literal -- "
                    f"{_describe_non_literal_newline(newline_kw.value)}; "
                    f'pass a literal newline="" (or newline="\\n"), or '
                    f'mark the call "# write-text-newline-exempt: <reason>" '
                    f"if this path never lands in the repo tree"
                )
            elif newline_kw.value.value not in ("", "\n"):
                problems.append(
                    f"{rel}:{node.lineno}: write_text() "
                    f"newline={newline_kw.value.value!r} is not \"\" or "
                    f'"\\n" -- that writes a literal line ending '
                    f"(CRLF-on-disk for \"\\r\\n\") instead of the "
                    f"platform default, the exact class of bug this gate "
                    f'exists to stop; pass newline="" (or newline="\\n"), '
                    f'or mark the call "# write-text-newline-exempt: '
                    f'<reason>" if this path never lands in the repo tree'
                )
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=REPO,
                     help="repo root to scan (default: the real repo)")
    args = ap.parse_args()

    if not any((args.root / sub).is_dir() for sub in _SCAN_SUBDIRS):
        print(
            f"error: --root {args.root} has neither a scripts/ nor a "
            f"firmware/ directory -- wrong --root?", file=sys.stderr,
        )
        return 1

    problems = find_problems(args.root)
    for p in problems:
        print(p, file=sys.stderr)
    if problems:
        print(f"\ncheck_write_text_newline: {len(problems)} site(s) need "
              f'newline="".', file=sys.stderr)
        return 1
    print("OK: every scripts/ and firmware/ write_text() call is "
          "newline-safe.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
