#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
E1M physical footprint gate -- validates the hand-transcribed pad-grid
geometry at ``metadata/e1m/footprint.yaml`` against
``metadata/schemas/e1m-footprint-v1.schema.json`` and cross-checks it
against the generated pin-mux capability tables.

The footprint file is the standard's fixed pad-grid geometry (one shared
file per footprint revision -- AEN/V2N/NX9 all share the same E1M
connector), *not* generated data; the pin-mux capability tables
(``metadata/pinmux/<family>.yaml``, generated by
``scripts/gen_pinmux_capability.py``) are the per-family function
assignment. This gate proves the two stay joinable:

  1. schema validation (``jsonschema``, mirrors ``validate_metadata.py``);
  2. every pad's ``pad`` id is exactly ``row + col``, ``row`` is a declared
     row, and ``col`` is within ``grid.columns``;
  3. no duplicate ``pad`` id;
  4. ``len(pads) == body.pad_count == 312`` (the E1M standard's fixed
     312-pad LGA footprint -- a ratchet: bump the literal deliberately if
     a future footprint revision changes the pad count);
  5. reverse-join: every non-``TBD`` ``e1m_pad`` in
     ``metadata/pinmux/*.yaml`` resolves to a pad in this footprint;
  6. function-join: every ``(e1m_pad, e1m_function)`` pair in each family
     pin-mux table with real (non-``TBD``) pads matches the same pad's
     ``e1m_function`` here (canonical-name, exact-match). Families are
     auto-detected (``_function_join_families``) so none is silently skipped
     once its table gains real ``e1m_pad`` values; v2n is all ``TBD`` today.

It also enforces structural invariants that keep the file a trustworthy
render/verification source: unique ``rows[]``; every pad's ``band`` matches
the deterministic row/col rule; no duplicate ``e1m_function``; every
``signal``/``analog`` pad carries an ``e1m_function`` or a ``note`` (so a
dropped label can't pass as a blank pad); and a ``provenance`` ratchet
(``datasheet_confirmed`` requires concrete ``pitch_mm`` + ``view``/``a1_corner``).

Run locally:

    python3 scripts/check_e1m_footprint.py

CI wires this in `pr-metadata-validate.yml`.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import jsonschema

try:
    import yaml  # type: ignore[import-untyped]
except ImportError:
    sys.exit("check_e1m_footprint: PyYAML is required.  Install via `pip install pyyaml`.")

REPO = Path(__file__).resolve().parent.parent
FOOTPRINT = REPO / "metadata" / "e1m" / "footprint.yaml"
SCHEMA = REPO / "metadata" / "schemas" / "e1m-footprint-v1.schema.json"
PINMUX_DIR = REPO / "metadata" / "pinmux"

# The E1M standard's fixed LGA pad count.  Bump deliberately if a future
# footprint revision changes it -- this is a ratchet, not a guess.
EXPECTED_PAD_COUNT = 312

# The function-join runs for every family whose pin-mux table carries at
# least one real (non-TBD) e1m_pad -- auto-detected (see
# _function_join_families), so a family is never silently skipped once its
# table gains real e1m_pad assignments.  v2n.yaml is all "TBD" today.


def _load_yaml(path: Path):
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _check_schema(doc) -> list[str]:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    validator = jsonschema.Draft202012Validator(schema)
    errors = sorted(validator.iter_errors(doc), key=lambda e: list(e.absolute_path))
    return [
        f"schema: {'/'.join(str(p) for p in err.absolute_path) or '<root>'}: {err.message}"
        for err in errors
    ]


def _check_pad_shape(doc) -> list[str]:
    """Every pad: pad == row + col; row in rows[]; 1 <= col <= grid.columns."""
    errors: list[str] = []
    rows = set(doc.get("rows") or [])
    max_col = (doc.get("grid") or {}).get("columns")
    for p in doc.get("pads") or []:
        pad, row, col = p.get("pad"), p.get("row"), p.get("col")
        if pad != f"{row}{col}":
            errors.append(f"pad {pad!r}: does not equal row+col ({row!r}+{col!r})")
        if row not in rows:
            errors.append(f"pad {pad!r}: row {row!r} not in rows[]")
        if not isinstance(col, int) or not (1 <= col <= (max_col or 0)):
            errors.append(f"pad {pad!r}: col {col!r} not in 1..{max_col}")
    return errors


def _check_no_duplicate_pads(doc) -> list[str]:
    seen: dict[str, int] = {}
    for p in doc.get("pads") or []:
        pad = p.get("pad")
        seen[pad] = seen.get(pad, 0) + 1
    return [f"pad {pad!r}: appears {n} times (duplicate)" for pad, n in seen.items() if n > 1]


def _check_pad_count(doc) -> list[str]:
    errors: list[str] = []
    n_pads = len(doc.get("pads") or [])
    declared = (doc.get("body") or {}).get("pad_count")
    if n_pads != declared:
        errors.append(f"len(pads)={n_pads} != body.pad_count={declared}")
    if declared != EXPECTED_PAD_COUNT:
        errors.append(f"body.pad_count={declared} != expected {EXPECTED_PAD_COUNT}")
    if n_pads != EXPECTED_PAD_COUNT:
        errors.append(f"len(pads)={n_pads} != expected {EXPECTED_PAD_COUNT}")
    return errors


def _pinmux_files() -> list[Path]:
    if not PINMUX_DIR.is_dir():
        return []
    return sorted(PINMUX_DIR.glob("*.yaml"))


def _function_join_families() -> list[str]:
    """Family stems whose pin-mux table has >= 1 non-TBD e1m_pad, so an
    (e1m_pad, e1m_function) join against the footprint is meaningful.
    Auto-detected so a family is never silently skipped once its table
    gains real e1m_pad values."""
    families: list[str] = []
    for path in _pinmux_files():
        fam_doc = _load_yaml(path)
        if any(
            (row.get("e1m_pad") and row.get("e1m_pad") != "TBD")
            for row in (fam_doc.get("pads") or [])
        ):
            families.append(path.stem)
    return families


def _check_reverse_join(doc) -> list[str]:
    """Every non-TBD e1m_pad in metadata/pinmux/*.yaml resolves to a
    footprint pad."""
    errors: list[str] = []
    footprint_pads = {p.get("pad") for p in doc.get("pads") or []}
    total = resolved = 0
    for path in _pinmux_files():
        family_doc = _load_yaml(path)
        rel = path.relative_to(REPO).as_posix()
        for row in (family_doc.get("pads") or []):
            e1m_pad = row.get("e1m_pad")
            if not e1m_pad or e1m_pad == "TBD":
                continue
            total += 1
            if e1m_pad not in footprint_pads:
                errors.append(
                    f"reverse-join {rel}: e1m_pad {e1m_pad!r} (silicon_peripheral="
                    f"{row.get('silicon_peripheral')!r}) has no matching pad in "
                    f"{FOOTPRINT.relative_to(REPO).as_posix()}"
                )
            else:
                resolved += 1
    print(f"reverse-join: {resolved}/{total} pin-mux e1m_pad ref(s) resolve to a footprint pad.")
    return errors


def _check_aen_function_join(doc) -> list[str]:
    """Every (e1m_pad, e1m_function) in the listed FUNCTION_JOIN_FAMILIES'
    pin-mux tables must match the same pad's e1m_function here."""
    errors: list[str] = []
    footprint_funcs = {p.get("pad"): p.get("e1m_function") for p in doc.get("pads") or []}
    for family in _function_join_families():
        path = PINMUX_DIR / f"{family}.yaml"
        if not path.is_file():
            errors.append(f"function-join: no pin-mux table at {path}")
            continue
        family_doc = _load_yaml(path)
        rel = path.relative_to(REPO).as_posix()
        checked = matched = 0
        for row in (family_doc.get("pads") or []):
            e1m_pad = row.get("e1m_pad")
            if not e1m_pad or e1m_pad == "TBD":
                continue
            e1m_function = row.get("e1m_function")
            checked += 1
            if e1m_pad not in footprint_funcs:
                continue  # already reported by _check_reverse_join
            footprint_function = footprint_funcs[e1m_pad]
            if footprint_function != e1m_function:
                errors.append(
                    f"function-join {rel}: e1m_pad {e1m_pad!r} has e1m_function "
                    f"{e1m_function!r}, but footprint.yaml has "
                    f"{footprint_function!r}"
                )
            else:
                matched += 1
        print(f"function-join ({family}): {matched}/{checked} e1m_pad/e1m_function pair(s) match.")
    return errors


def _check_rows_unique(doc) -> list[str]:
    seen: dict[str, int] = {}
    for r in doc.get("rows") or []:
        seen[r] = seen.get(r, 0) + 1
    return [
        f"rows[]: {r!r} appears {n} times (row letters must be unique)"
        for r, n in seen.items()
        if n > 1
    ]


def _expected_band(row: str, col, columns: int):
    """Row-priority band rule the footprint data is built with: the top/bottom
    rows win over the left/right column bands at the corners."""
    if row in ("A", "B"):
        return "top"
    if row in ("AG", "AH"):
        return "bottom"
    if isinstance(col, int) and col <= 3:
        return "left"
    if isinstance(col, int) and col >= columns - 2:
        return "right"
    return None


def _check_band(doc) -> list[str]:
    """Every pad's band matches the deterministic row/col rule -- so band can
    drive a renderer instead of being a decorative, unvalidated field."""
    errors: list[str] = []
    columns = (doc.get("grid") or {}).get("columns") or 0
    for p in doc.get("pads") or []:
        want = _expected_band(p.get("row"), p.get("col"), columns)
        if want is None:
            errors.append(
                f"pad {p.get('pad')!r}: interior pad not allowed "
                f"(row {p.get('row')!r} col {p.get('col')!r} maps to no band)"
            )
        elif p.get("band") != want:
            errors.append(
                f"pad {p.get('pad')!r}: band {p.get('band')!r} != expected {want!r}"
            )
    return errors


def _check_duplicate_functions(doc) -> list[str]:
    seen: dict[str, list[str]] = {}
    for p in doc.get("pads") or []:
        fn = p.get("e1m_function")
        if fn:
            seen.setdefault(fn, []).append(p.get("pad"))
    return [
        f"e1m_function {fn!r}: assigned to multiple pads {pads}"
        for fn, pads in seen.items()
        if len(pads) > 1
    ]


def _check_label_completeness(doc) -> list[str]:
    """A muxable/analog pad must carry either an e1m_function or a note, so a
    dropped transcription label can't masquerade as an intentionally blank pad."""
    bad = [
        p.get("pad")
        for p in doc.get("pads") or []
        if p.get("type") in ("signal", "analog")
        and not p.get("e1m_function")
        and not p.get("note")
    ]
    return (
        [f"label: {len(bad)} signal/analog pad(s) have neither e1m_function nor note: {bad}"]
        if bad
        else []
    )


def _check_provenance_ratchet(doc) -> list[str]:
    """datasheet_confirmed asserts the geometry is checked against the mechanical
    drawing / CAD -- so pitch and view/origin must then be concrete."""
    errors: list[str] = []
    if doc.get("provenance") == "datasheet_confirmed":
        if (doc.get("grid") or {}).get("pitch_mm") is None:
            errors.append("provenance=datasheet_confirmed but grid.pitch_mm is null")
        if not doc.get("view") or not doc.get("a1_corner"):
            errors.append("provenance=datasheet_confirmed but view/a1_corner not set")
    return errors


def main() -> int:
    if not FOOTPRINT.is_file():
        print(f"check_e1m_footprint: no footprint file at {FOOTPRINT}", file=sys.stderr)
        return 1
    if not SCHEMA.is_file():
        print(f"check_e1m_footprint: no schema at {SCHEMA}", file=sys.stderr)
        return 1

    doc = _load_yaml(FOOTPRINT)

    all_errors: list[str] = []
    all_errors += _check_schema(doc)
    all_errors += _check_pad_shape(doc)
    all_errors += _check_no_duplicate_pads(doc)
    all_errors += _check_pad_count(doc)
    all_errors += _check_rows_unique(doc)
    all_errors += _check_band(doc)
    all_errors += _check_duplicate_functions(doc)
    all_errors += _check_label_completeness(doc)
    all_errors += _check_provenance_ratchet(doc)
    all_errors += _check_reverse_join(doc)
    all_errors += _check_aen_function_join(doc)

    if all_errors:
        for e in all_errors:
            print(f"e1m-footprint: {e}", file=sys.stderr)
        print(f"\ncheck_e1m_footprint: {len(all_errors)} issue(s).", file=sys.stderr)
        return 1

    print(f"check_e1m_footprint: {len(doc.get('pads') or [])} pad(s) OK -- schema valid, "
          f"shape valid, no duplicates, pad_count matches, pin-mux joins clean.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
