#!/usr/bin/env python3
# Copyright 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Doc-drift gate -- fails (exit 1) when customer-facing documentation
references SDK identifiers that no longer exist, when a top-level
doc isn't linked from the docs index, or when CC3501E docs/examples
describe the current bridge as the obsolete CS-less design.

Five independent checks:

  (a) Dead-symbol references.  Every `ALP_[A-Z0-9_]+` and
      `alp_[a-z0-9_]+` token mentioned in a customer doc -- including a
      `CONFIG_`-prefixed one (`CONFIG_ALP_SDK_FOO=y`); the prefix is
      stripped before the known-symbol check, since Kconfig source
      spells the same symbol bare -- must exist as a token in one of
      the SDK's authoritative sources of truth:
        * C-API public + internal headers, sources
                                   include/**/*.h, src/**/*.h,
                                 src/**/*.c, src/**/*.cpp
        * Kconfig config symbols   zephyr/Kconfig[.alp-libraries],
                                 zephyr/kconfigs/*.kconfig
        * generated identifiers    scripts/alp_project.py + scripts/gen_*.py
          (the alp_hw_info_build CMake helper, ALP_HW_BUILD_* / ALP_SOC_*
           macros)
        * vendor integration anchors  vendors/**/CMakeLists.txt (e.g.
          ALP_HAS_RENESAS_FSP) -- a symbol a vendors/<lib>/README.md
          documents can be declared ONLY here, not under include/ or src/
        * real board targets       zephyr/boards/alp/<dir>/board.yml's
          `board: name:` field (e.g. alp_e1m_aen801_m55_he) -- EXISTENCE,
          not naming shape, is what makes a board name real; a token
          that merely looks like alp_e1m_<shape> but has no board.yml
          on disk is dead (see collect_real_board_names())
      A token that appears in the docs but in NONE of these is "dead" --
      almost always a rename the docs missed (e.g. the DEEPX_DX ->
      DEEPX_DXM1 / .alpmodel migration left ALP_..._DEEPX_DX behind).
      Harvesting from the real sources (rather than a hand-kept
      allowlist) keeps the gate low-maintenance and free of
      build-identifier false positives.

      Scanned surfaces (customer-facing only):
        README.md, docs/*.md (top-level), docs/tutorials/**,
        docs/soms/**, docs/boards/**, docs/bench/**, vendors/**/*.md
      Deliberately NOT scanned:
        * historical / generated / internal: CHANGELOG.md,
          docs/superpowers/**, docs/abi/**, docs/adr/**
        * forward-looking design/proposal docs that document not-yet-
          shipped APIs by intent (see _SCAN_EXCLUDE_DOCS)
      Not yet in scope (narrower than the sibling check_doc_links.py,
      which additionally covers docs/{diagnostics,ci}/** and
      examples/**/README.md): docs/ci/**, docs/diagnostics/**,
      docs/architecture/**, docs/metadata/**, examples/**/README.md.
      Widening this needs its own pass -- a spot-check of those
      directories turns up several ALP_*-shaped tokens that are CI/env
      var names, not SDK symbols (e.g. ALP_CI_APP_ID), so naively adding
      them would need new allowlist curation, not just a scan-surface
      flip.

  (b) Docs-index integrity.  Every top-level docs/*.md (except
      README.md itself) must be linked from docs/README.md.  This is
      the check the updating-docs skill documents in prose; here it is
      mechanised so CI enforces it.

  (c) CC3501E bridge-current wording.  Customer docs, the CC3501E firmware
      wrapper comments, and the AEN CC3501E examples must not describe the
      current bridge as the older CS-less / fixed-count design.  Explicitly
      historical "earlier r1" notes are allowed; current-rev guidance must say
      hardware SS0 + READY, with HOST_IRQ / async events as the remaining
      future work.

  (d) E1M-X pinout namespace guidance.  Standalone/general docs that teach
      developers to pick pinout instance IDs must present the E1M and E1M-X
      namespaces together (`<alp/e1m_pinout.h>` + `<alp/e1m_x_pinout.h>`).
      E1M-only guidance in those docs is drift because the form factors are
      intentionally separate product lines.

  (e) Portability-matrix totals.  docs/portability-matrix.md's generated
      block states the authoritative "N / M cells generate cleanly" count
      per family (regenerated by scripts/gen_portability_matrix.py,
      gated by pr-generated-files.yml).  Several narrative docs
      (docs/v1.0-readiness.md, docs/portability.md,
      docs/tutorials/04-cross-family-portability.md) hand-quote that
      count in prose ("18/21", "8 of 12", ...); nothing previously
      re-checked those quotes against the generated source, so they
      silently drifted when the SoM lineup changed (#1203).  Any
      hand-written "N/M" or "N of M" fraction whose denominator matches
      one of the matrix's own per-family totals must carry the matching
      numerator.

Run from the repo root:

    python3 scripts/check_doc_drift.py                  # both checks
    python3 scripts/check_doc_drift.py --allow ALP_FOO  # extend allowlist

Exits non-zero if any check finds a problem.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import Optional


ROOT = pathlib.Path(__file__).resolve().parent.parent

# Last-resort allowlist for tokens that are deliberately not real
# symbols -- e.g. illustrative placeholders in docs.  Real identifiers
# come from collect_known_symbols(); a growing allowlist usually means
# the gate is catching genuine drift that belongs fixed in the docs
# instead.  Justify every entry.
_ALLOWLIST: set[str] = {
    # The canonical ABI symbol-versioning *example* in release-policy.md
    # ("alp_foo" gets a "@2" version node -> alp_foo_v2): not real APIs.
    "alp_foo",
    "alp_foo_v2",
    # Driver-internal compile gate in zephyr/drivers/spi/spi_renesas_rz_sci_b.c
    # (the parked SCI7 DMAC fast path), referenced by the SCI7 next-rev plan.
    # Real identifier; zephyr/drivers .c files are deliberately outside the
    # scanned API surfaces.
    "ALP_V2N_SCI7_DMAC",
    # Kernel-dtb compile gate in meta-alp-sdk's e1m-v2n-som.dtsi that raises the
    # CA55 cap from 1.7 GHz (default) to 1.8 GHz, documented in build-yocto-v2n.md.
    # Real identifier; *.dtsi is deliberately outside the harvested surfaces
    # (harvest scans meta-alp-sdk *.conf/*.bb/*.bbappend/*.inc only).
    "ALP_CA55_1P8GHZ",
    # U-Boot Kconfig string selecting the board dtb basename for
    # CONFIG_BOOTCOMMAND (#1252), named by bring-up-drpai-v2n.md's deploy
    # section.  Real identifier, but it is DEFINED in
    # meta-alp-sdk/recipes-bsp/u-boot/u-boot/0002-rzv2n-dev-ALP-E1M-production-boot.patch
    # and set in fdtfile-v2m.cfg -- a *.patch and a *.cfg, neither of which
    # is a harvested surface (meta-alp-sdk harvest scans *.conf/*.bb/
    # *.bbappend/*.inc only).  The one .bbappend that does mention it spells
    # it CONFIG_-prefixed, which _BARE_SYMBOL_RE deliberately does not strip
    # during harvest.  Same shape as ALP_CA55_1P8GHZ above.
    "ALP_E1M_FDTFILE",
    # docs/porting-new-som.md's worked example walks through porting a
    # HYPOTHETICAL 7th AEN-family SKU, E1M-AEN901 (see its Sec 3) -- these
    # Zephyr board targets are deliberately illustrative and never land in
    # zephyr/boards/alp/, so collect_real_board_names() will never find them.
    "alp_e1m_aen901_m55_he",
    "alp_e1m_aen901_m55_hp",
    # The rest of docs/porting-new-som.md Sec 3's hypothetical E1M-AEN901 /
    # Alif Ensemble "E9" worked example -- the illustrative `alp_project.py
    # --emit zephyr-conf` stdout excerpt it walks through.  Same rationale
    # as the two board names above: each follows a real, documented
    # *computed* naming pattern (`ALP_SOC_` + ref.upper(), `ALP_SDK_CHIP_`
    # + chip name) for a SoC/chip that doesn't exist yet, so it never lands
    # in a harvested source by design.
    "ALP_SOC_ALIF_ENSEMBLE_E9",
    "ALP_SDK_CHIP_CC3511E",
    # Genuinely removed in the v0.3 cleanup.  vendors/lwrb/README.md and
    # vendors/nanopb/README.md each name it once, in "no Kconfig flag for
    # this any more -- the previous X was removed" historical wording, not
    # as live guidance; docs/board-config.md:165's "Pre-`board.yaml`"
    # table row names ALP_SDK_USE_LWRB the same way, describing what the
    # OLD per-file config looked like before board.yaml replaced it.
    "ALP_SDK_USE_LWRB",
    "ALP_SDK_USE_NANOPB",
    # docs/board-config-features.md's PSA-attestation section names the
    # exact Kconfig line and driver-path comment
    # scripts/alp_orchestrate/secure.py emits for `attestation_root:
    # optiga_trust_m` -- the doc accurately describes the generator's
    # output, but no zephyr/kconfigs/*.kconfig defines a bare `config
    # ALP_SDK_PSA_ATTESTATION_OPTIGA`, and the
    # `src/security/optiga_trust_m_bridge.c` the emitted comment cites
    # does not exist (only the probe-only `chips/optiga_trust_m/
    # optiga_trust_m.c` chip driver is real, see #1164). A real, separate
    # gap from #1228's imx93 table -- allowlisted rather than silently
    # re-widening the harvest, pending a maintainer decision to finish
    # the PSA<->OPTIGA wiring or mark it not-yet-implemented in the doc.
    "ALP_SDK_PSA_ATTESTATION_OPTIGA",
    # docs/gd32-bridge.md's recovery-runbook narration names this env var
    # read by tan-cli's flash_cmd.py (a different repo,
    # python/tan/commands/flash_cmd.py's REQUIRE_DPIDR_ENV, tan-cli#589),
    # not an alp-sdk symbol.  Allowlisted BECAUSE it will never appear in
    # this repo's headers/Kconfig/generators; drop the entry if
    # docs/gd32-bridge.md ever stops naming it.
    "ALP_FLASH_REQUIRE_DPIDR",
    # docs/aen-provisioning.md's app-device-config.json section names these
    # two bench env vars (scripts/bench/aen/flash-update-log-firewall-probe.sh,
    # scripts/bench/aen/flash-update-log-dual.sh) to bound the doc's guidance
    # against the firewall-policy carve-out those scripts already encode.
    # Real identifiers, but *.sh under scripts/bench/ is deliberately outside
    # the harvested surfaces (collect_known_symbols() scans headers/Kconfig/
    # generators/vendor CMakeLists/board.yml only). Same shape as
    # ALP_FLASH_REQUIRE_DPIDR above.
    "ALP_AEN_INCLUDE_DEVICE_CONFIG",
    "ALP_AEN_DEVICE_CONFIG_JSON",
}

# Identifier shapes we treat as SDK symbols.  The optional `CONFIG_`
# prefix is consumed but NOT captured -- `\b` never fires between
# "CONFIG_" and "ALP_" (both are \w, so there's no boundary there), so
# without this every `CONFIG_ALP_SDK_*=y` line in a doc was invisible
# to the scan entirely (#1228).  Kconfig source spells the same symbol
# bare (`config ALP_SDK_FOO`), so stripping the prefix here is what
# lets a doc's `CONFIG_ALP_SDK_FOO` match a harvested `ALP_SDK_FOO`.
# Used for DOC SCANNING only (find_dead_symbols) -- see _BARE_SYMBOL_RE
# for why known-symbol harvesting must not do this same stripping.
_SYMBOL_RE = re.compile(r"\b(?:CONFIG_)?(ALP_[A-Z0-9_]+|alp_[a-z0-9_]+)\b")

# Same identifier shapes WITHOUT the CONFIG_-prefix stripping, used only
# when harvesting known symbols (collect_known_symbols).  A `CONFIG_ALP_*`
# occurrence in a header, C source, CMake file, generator, or Kconfig
# help text is always a REFERENCE to an already-existing Kconfig symbol
# (`#ifdef CONFIG_ALP_SDK_FOO`, `if(CONFIG_ALP_SDK_FOO)`, prose) -- never
# itself the point where the bare symbol ALP_SDK_FOO is defined.
# Stripping the prefix during harvest (like _SYMBOL_RE does for docs) let
# a stale `#ifdef`/`#elif defined(CONFIG_...)` re-confirm a symbol whose
# real Kconfig definition had been renamed out from under it -- the
# `src/**/*.c`+`.cpp` layer went blind to a renamed-away Kconfig symbol
# as long as one stale reference to the old name remained in a source
# file (mutation-proven: renaming `config
# ALP_SDK_INFERENCE_ETHOS_U_VARIANT_U65` out of Kconfig left the gate
# green because src/backends/inference/tflm.cpp's `#elif
# defined(CONFIG_...)` still matched).  A real Kconfig `config ALP_SDK_FOO`
# line has no `CONFIG_` glued in front, so it still matches this bare
# form; only a same-file *reference* to the generated macro spelling
# stops counting as proof of existence.
_BARE_SYMBOL_RE = re.compile(r"\b(ALP_[A-Z0-9_]+|alp_[a-z0-9_]+)\b")

# Real Zephyr board target names are harvested from the `board: name:`
# field of each in-tree zephyr/boards/alp/<dir>/board.yml (see
# collect_real_board_names()) -- board EXISTENCE, not naming shape.  A
# board name that merely matches the alp_e1m_[a-z0-9_]+ shape (e.g. a
# renamed-before-landing or never-shipped target) is dead; only a real
# board.yml makes it known.  Matches the first `name:` line in the file,
# which is always `board: name:` -- it precedes the `socs:` list's own
# `- name:` entries.
_BOARD_YML_NAME_RE = re.compile(r"^\s*name:\s*(\S+)", re.MULTILINE)

# docs/ subdirectories scanned recursively for dead symbols.
_DOC_SUBDIRS = ("tutorials", "soms", "boards", "bench")

# Top-level docs/*.md that are forward-looking design / proposal docs:
# they document APIs that don't exist yet *by intent*, so they are
# excluded from the dead-symbol scan (like docs/superpowers/).  They
# REMAIN required in the docs index (check b) -- they are real docs.
_SCAN_EXCLUDE_DOCS = {
    "v0.6-tbd-and-assumptions.md",   # in-flight v0.6 TBDs / assumptions
}

_CC3501E_BRIDGE_SCAN_SUFFIXES = {
    ".c",
    ".h",
    ".md",
    ".overlay",
    ".ps1",
    ".sh",
    ".syscfg",
    ".yaml",
    ".yml",
}

_CC3501E_BRIDGE_SCAN_GLOBS = (
    "docs/cc3501e*.md",
    "examples/aen/aen-cc3501e-*/**/*",
    "examples/aen/aen-usb-firstlight/**/*",
    "examples/peripheral-io/alp-console/**/*",
)

_CC3501E_STALE_BRIDGE_RE = re.compile(
    r"(?:\b(?:current|this)\b.*\b(?:CS-less|no\s+CS|no\s+chip-select|"
    r"fixed-count|fixed-clock-count)\b)"
    r"|(?:\b(?:CS-less|no-CS)\s+lockstep\b)"
    r"|(?:\bfixed-(?:count|clock-count)\b)"
    r"|(?:\b3-wire\s+(?:CS-less|deterministic|SPI bridge)\b)"
    r"|(?:\bwires only SCLK/MOSI/MISO\b)"
    r"|(?:\bSS tied asserted\b)"
    r"|(?:\bnext board rev\b.*\bCS\b)"
    r"|(?:\bCS line \+ host-IRQ\b)"
    r"|(?:\bCS-less framing fragility\b)",
    re.IGNORECASE,
)

_CC3501E_STALE_ALLOWED_RE = re.compile(
    r"\b(?:earlier|old|obsolete|prior|previous|previously|r1|resolved)\b"
    r"|(?:\bnot\b.{0,40}\b(?:CS-less|fixed-count|fixed-clock-count|lockstep)\b)"
    r"|(?:\bdo not revert\b.{0,40}\bThree Pin\b)",
    re.IGNORECASE,
)

_PINOUT_GUIDANCE_DOCS = (
    "README.md",
    "docs/getting-started.md",
    "docs/firmware-quickstart.md",
    "docs/architecture.md",
)

_E1M_PINOUT_GUIDANCE_RE = re.compile(
    r"(?:<alp/e1m_pinout\.h>|`?ALP_E1M_(?:I2C|SPI|UART|I2S|PWM|ADC|DAC|WDT|GPIO)[A-Z0-9_]*`?)"
)
_E1M_X_PINOUT_GUIDANCE_RE = re.compile(
    r"(?:<alp/e1m_x_pinout\.h>|`?ALP_E1M_X_[A-Z0-9_]*`?)"
)
_PINOUT_TEACHING_RE = re.compile(
    r"\b(?:standalone|hand-written|portable|portability|form factor|instance IDs?|pinout)\b",
    re.IGNORECASE,
)

# The generated per-family "N / M cells generate cleanly" line in
# docs/portability-matrix.md -- the authoritative source every hand-typed
# copy elsewhere must match.
_MATRIX_TOTAL_RE = re.compile(r"\*\*(\d+)\s*/\s*(\d+) cells generate cleanly")

# Narrative docs (root-relative) known to hand-quote the matrix totals in
# prose.  A new doc that starts quoting the totals and drifts silently is
# still a real gap; this list documents where the sweep looked, not an
# exhaustive guarantee -- extend it when a new doc starts citing the matrix.
_MATRIX_TOTAL_QUOTING_DOCS = (
    "README.md",
    "docs/v1.0-readiness.md",
    "docs/portability.md",
    "docs/tutorials/04-cross-family-portability.md",
)

# "18/21", "18 / 21", or "18 of 21" -- the shapes the totals are quoted in.
# The slash form excludes matches embedded in a longer slash/digit chain
# (e.g. "resolution_bits (6/8/10/12 -> hardware DRES)") via lookaround --
# without that guard, re.finditer's non-overlapping scan would read a
# 4-way enumeration as a spurious "10/12" fraction.
_STATED_SLASH_FRACTION_RE = re.compile(r"(?<![\d/])(\d+)\s*/\s*(\d+)(?![\d/])")
_STATED_OF_FRACTION_RE = re.compile(r"(\d+)\s+of\s+(\d+)")

# The example/preset-adoption count docs/board-config-schema.md hand-quotes
# ("100 do today -- 75 on `e1m-evk`, 25 on `e1m-x-evk`") -- checked live
# against examples/**/board.yaml's `preset:` field so it can't re-rot the
# way 66/46/20 did before it.
_EXAMPLE_PRESET_COUNT_RE = re.compile(
    r"\((\d+) do today — (\d+) on `e1m-evk`, (\d+) on `e1m-x-evk`\)"
)


def collect_known_symbols(root: pathlib.Path) -> set[str]:
    """Return every ALP_*/alp_* token that appears in ANY of the SDK's
    authoritative source layers.  An identifier is real (not drift) if it
    exists in any of these -- a doc reference present in NO source layer
    is what we flag.  Tests and docs are deliberately NOT sources of truth.

    Source layers harvested (each bounded to a specific directory -- never
    a whole-tree walk, so this stays fast and skips build artefacts):
      * C-API headers + sources  include/**/*.h, src/**/*.h,
                                 src/**/*.c, src/**/*.cpp
      * Kconfig config symbols   zephyr/Kconfig[.alp-libraries],
                                 zephyr/kconfigs/*.kconfig
      * CMake options / helpers  CMakeLists.txt, src/**/CMakeLists.txt,
                                 cmake/**/*.cmake, vendors/**/CMakeLists.txt
                                 (ALP_OS, ALP_SDK*, alp_hw_info_build,
                                 ALP_HAS_RENESAS_FSP, ...)
      * generators / tooling     scripts/**/*.py, excluding scripts/check_*.py
                                 gate scripts (board names,
                                 ALP_HW_BUILD_* / ALP_SOC_* macros,
                                 board.yaml field identifiers)
      * config schemas           metadata/schemas/*.json (board.yaml fields)
      * board-scoped app overlays  examples/**/boards/*.conf,
                                 examples/**/boards/*.overlay -- the full
                                 per-core board+SoC+core target identity
                                 (collect_real_board_names() only returns
                                 the bare board name)
      * release-signing keys      keys/*.pem
    """
    symbols: set[str] = set()

    def harvest(path: pathlib.Path) -> None:
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return
        symbols.update(m.group(1) for m in _BARE_SYMBOL_RE.finditer(text))

    def harvest_tree(base: pathlib.Path, pattern: str, *, exclude=None) -> None:
        if base.is_dir():
            for path in base.rglob(pattern):
                if exclude is not None and exclude(path):
                    continue
                harvest(path)

    def harvest_filenames(base: pathlib.Path, pattern: str) -> None:
        # Some real identifiers are proven by a filename's EXISTENCE on
        # disk, not by a declaration inside a source file -- same
        # principle as collect_real_board_names().  Match the symbol
        # shape against the filename text itself.
        if base.is_dir():
            for path in base.rglob(pattern):
                symbols.update(m.group(1) for m in _BARE_SYMBOL_RE.finditer(path.name))

    # C-API: public + internal headers, plus .c/.cpp sources -- some
    # symbols (e.g. the per-variant inference backend entry points) are
    # declared only in the .cpp that defines them, not a header.
    harvest_tree(root / "include", "*.h")
    harvest_tree(root / "src", "*.h")
    harvest_tree(root / "src", "*.c")
    harvest_tree(root / "src", "*.cpp")
    # Kconfig config namespace (ALP_SDK_*).  zephyr/Kconfig only sources the
    # per-subsystem fragments under zephyr/kconfigs/ (issue #458 split) plus a
    # couple of driver-tree Kconfig files, so harvest those directly too.
    for kconfig in ("zephyr/Kconfig", "zephyr/Kconfig.alp-libraries"):
        harvest(root / kconfig)
    harvest_tree(root / "zephyr" / "kconfigs", "*.kconfig")
    # CMake options / helper functions (ALP_OS, ALP_SDK*, alp_hw_info_build).
    # vendors/**/CMakeLists.txt is its own layer: a vendor integration
    # anchor (e.g. vendors/renesas-rzv2n/CMakeLists.txt's
    # option(ALP_HAS_RENESAS_FSP ...)) can be the ONLY place a symbol its
    # own vendors/<lib>/README.md documents is declared.
    harvest(root / "CMakeLists.txt")
    harvest_tree(root / "src", "CMakeLists.txt")
    harvest_tree(root / "cmake", "*.cmake")
    harvest_tree(root / "vendors", "CMakeLists.txt")
    # Generators / orchestrator / project tooling -- emit board target
    # names, ALP_HW_BUILD_* / ALP_SOC_* macros, board.yaml field identifiers.
    # Every scripts/check_*.py gate script (this file included) is
    # excluded from this harvest as a class, not just by name: a
    # gate script narrates ALP_*/alp_* tokens in comments, docstrings, and
    # allowlist rationale without ever declaring or generating one.  Left
    # in, any one of them can let a symbol it merely discusses
    # self-confirm as "known" and hide real drift forever; the actual
    # generators (alp_project.py, gen_*.py, alp_orchestrate/**) stay
    # harvested.
    harvest_tree(root / "scripts", "*.py",
                exclude=lambda p: p.name.startswith("check_"))
    # Config schemas -- board.yaml field names.
    harvest_tree(root / "metadata" / "schemas", "*.json")
    # Board-scoped app CONFIG/DT overlays: Zephyr's boards/<board_target>.conf
    # / boards/<board_target>.overlay convention, keyed by the full
    # board+SoC+core target identity (e.g. docs/aen-bench-bringup.md's
    # `boards/alp_e1m_aen801_m55_he_ae822fa0e5597ls0_rtss_he.conf`).  Bounded
    # to examples/ (where every customer-doc-referenced target identity
    # lives) rather than the whole tree, so this doesn't also walk
    # tests/**/boards/ fixtures or pick up build/west-managed dirs.
    harvest_filenames(root / "examples", "boards/*.conf")
    harvest_filenames(root / "examples", "boards/*.overlay")
    # Release-signing key filenames under keys/ (e.g.
    # keys/alp_release_signing_ecdsa_p256.pub.pem, documented by
    # docs/som-release-signing.md).
    harvest_filenames(root / "keys", "*.pem")
    # Yocto layer -- MACHINE / image variables (ALP_BOOT_DEVICE, ...).
    for pat in ("*.conf", "*.bb", "*.bbappend", "*.inc"):
        harvest_tree(root / "meta-alp-sdk", pat)
    return symbols


def collect_real_board_names(root: pathlib.Path) -> set[str]:
    """Return every real Zephyr board target name shipped in-tree, read
    from each zephyr/boards/alp/<dir>/board.yml's `board: name:` field.

    This is the ground-truth check the naming-shape regex it replaced
    was not: a board name that never landed (or was renamed before it
    did) matches the alp_e1m_[a-z0-9_]+ shape just as well as a real
    one -- only an actual board.yml on disk proves the board exists.
    """
    names: set[str] = set()
    boards_dir = root / "zephyr" / "boards" / "alp"
    if not boards_dir.is_dir():
        return names
    for board_yml in boards_dir.glob("*/board.yml"):
        try:
            text = board_yml.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        m = _BOARD_YML_NAME_RE.search(text)
        if m:
            names.add(m.group(1))
    return names


def doc_files_for_symbol_scan(root: pathlib.Path) -> list[pathlib.Path]:
    """Customer-facing docs scanned for dead symbols (spec scope)."""
    out: list[pathlib.Path] = []
    readme = root / "README.md"
    if readme.is_file():
        out.append(readme)
    docs = root / "docs"
    if docs.is_dir():
        out.extend(sorted(p for p in docs.glob("*.md")  # top-level only
                          if p.name not in _SCAN_EXCLUDE_DOCS))
        for sub in _DOC_SUBDIRS:
            d = docs / sub
            if d.is_dir():
                out.extend(sorted(d.rglob("*.md")))      # recursive
    vendors = root / "vendors"
    if vendors.is_dir():
        out.extend(sorted(vendors.rglob("*.md")))         # recursive
    return out


def _is_known(tok: str, known: set[str], allow: set[str]) -> bool:
    """A token is real if it is a known symbol (which includes real,
    in-tree board target names -- see collect_real_board_names()),
    allowlisted, or -- for trailing-underscore family/wildcard
    references like `ALP_E1M_*` (token captured as `ALP_E1M_`) -- a
    prefix of some real symbol."""
    if tok in known or tok in allow:
        return True
    if tok.endswith("_"):
        return any(s.startswith(tok) for s in known)
    return False


def find_dead_symbols(root: pathlib.Path, known: set[str],
                      allow: set[str]) -> list[tuple[str, int, str]]:
    """Return [(relpath, line_no, token)] for every dead symbol ref."""
    dead: list[tuple[str, int, str]] = []
    for doc in doc_files_for_symbol_scan(root):
        rel = doc.relative_to(root).as_posix()
        text = doc.read_text(encoding="utf-8", errors="replace")
        for line_no, line in enumerate(text.splitlines(), 1):
            for m in _SYMBOL_RE.finditer(line):
                tok = m.group(1)
                if not _is_known(tok, known, allow):
                    dead.append((rel, line_no, tok))
    return dead


def find_index_gaps(root: pathlib.Path) -> list[str]:
    """Return top-level docs/*.md filenames not linked from docs/README.md."""
    docs = root / "docs"
    index = docs / "README.md"
    if not index.is_file():
        return []
    # Include '.' in the filename class so dotted stems like
    # `v1.0-readiness.md` match (a bare [A-Za-z0-9_-]+ stops at the dot
    # and mis-extracts "0-readiness.md").
    linked = set(re.findall(r"[A-Za-z0-9_.-]+\.md",
                            index.read_text(encoding="utf-8")))
    gaps: list[str] = []
    for md in sorted(docs.glob("*.md")):
        if md.name == "README.md":
            continue
        # Leading-underscore files are section fragments folded into another
        # doc (e.g. _aen-runbook-section.md -> bring-up-aen.md), not standalone
        # index entries.
        if md.name.startswith("_"):
            continue
        if md.name not in linked:
            gaps.append(md.name)
    return gaps


def cc3501e_bridge_current_files(root: pathlib.Path) -> list[pathlib.Path]:
    """Files whose CC3501E bridge-current wording should stay in sync."""
    seen: set[pathlib.Path] = set()
    out: list[pathlib.Path] = []
    for pattern in _CC3501E_BRIDGE_SCAN_GLOBS:
        for path in root.glob(pattern):
            if not path.is_file():
                continue
            if path.suffix not in _CC3501E_BRIDGE_SCAN_SUFFIXES:
                continue
            if path in seen:
                continue
            seen.add(path)
            out.append(path)
    return sorted(out)


def find_cc3501e_bridge_stale_claims(root: pathlib.Path) -> list[tuple[str, int, str]]:
    """Return stale current-rev CC3501E bridge wording references."""
    stale: list[tuple[str, int, str]] = []
    for path in cc3501e_bridge_current_files(root):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8", errors="replace")
        for line_no, line in enumerate(text.splitlines(), 1):
            if not _CC3501E_STALE_BRIDGE_RE.search(line):
                continue
            if _CC3501E_STALE_ALLOWED_RE.search(line):
                continue
            stale.append((rel, line_no, line.strip()))
    return stale


def find_e1m_x_pinout_guidance_gaps(root: pathlib.Path) -> list[tuple[str, int, str]]:
    """Return E1M-only pinout guidance in standalone/general docs."""
    gaps: list[tuple[str, int, str]] = []
    for rel in _PINOUT_GUIDANCE_DOCS:
        path = root / rel
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        line_no = 1
        for para in re.split(r"\n\s*\n", text):
            if (
                _E1M_PINOUT_GUIDANCE_RE.search(para)
                and _PINOUT_TEACHING_RE.search(para)
                and not _E1M_X_PINOUT_GUIDANCE_RE.search(para)
            ):
                first = next((ln.strip() for ln in para.splitlines() if ln.strip()), "")
                gaps.append((rel, line_no, first))
            line_no += para.count("\n") + 2
    return gaps


def find_matrix_total_drift(root: pathlib.Path) -> list[tuple[str, int, str, str]]:
    """Return stale hand-quoted portability-matrix totals.

    Reads the authoritative "N / M cells generate cleanly" line(s) from
    the GENERATED block of docs/portability-matrix.md, then scans
    _MATRIX_TOTAL_QUOTING_DOCS for any "N/M" or "N of M" fraction whose
    denominator matches one of those totals.  Only the denominator is
    used to key the match -- 21 and 12 are specific to the current
    (SKU x example) cell counts, so an unrelated fraction elsewhere in
    the same docs (a tutorial count, a per-driver progress fraction)
    won't collide.
    """
    matrix_doc = root / "docs" / "portability-matrix.md"
    if not matrix_doc.is_file():
        return []
    matrix_text = matrix_doc.read_text(encoding="utf-8", errors="replace")
    authoritative = {
        int(total): int(passed)
        for passed, total in _MATRIX_TOTAL_RE.findall(matrix_text)
    }
    if not authoritative:
        return []

    drift: list[tuple[str, int, str, str]] = []
    for rel in _MATRIX_TOTAL_QUOTING_DOCS:
        path = root / rel
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for pattern in (_STATED_SLASH_FRACTION_RE, _STATED_OF_FRACTION_RE):
            for m in pattern.finditer(text):
                stated_pass, stated_total = int(m.group(1)), int(m.group(2))
                if stated_total not in authoritative:
                    continue
                expected_pass = authoritative[stated_total]
                if stated_pass != expected_pass:
                    line_no = text.count("\n", 0, m.start()) + 1
                    drift.append((rel, line_no, m.group(0).replace("\n", " "),
                                  f"{expected_pass}/{stated_total}"))
    return drift


def find_example_preset_count_drift(root: pathlib.Path) -> list[tuple[str, int, str, str]]:
    """Return a stale hand-quoted example/preset-adoption count.

    docs/board-config-schema.md hand-quotes how many `examples/**/board.yaml`
    files exist and how many use each preset ("100 do today -- 75 on
    `e1m-evk`, 25 on `e1m-x-evk`"). Recompute the real counts by walking the
    tree and comparing `preset:` values, instead of trusting the prose to
    stay in sync -- the same drift this line has already suffered twice
    (66/46/20, then 100/75/25).
    """
    doc_path = root / "docs" / "board-config-schema.md"
    examples_dir = root / "examples"
    if not doc_path.is_file() or not examples_dir.is_dir():
        return []

    board_yamls = sorted(examples_dir.glob("**/board.yaml"))
    evk = x_evk = 0
    for p in board_yamls:
        m = re.search(r"(?m)^preset:\s*(\S+)",
                       p.read_text(encoding="utf-8", errors="replace"))
        if not m:
            continue
        if m.group(1) == "e1m-evk":
            evk += 1
        elif m.group(1) == "e1m-x-evk":
            x_evk += 1
    actual = (len(board_yamls), evk, x_evk)

    text = doc_path.read_text(encoding="utf-8", errors="replace")
    drift: list[tuple[str, int, str, str]] = []
    for m in _EXAMPLE_PRESET_COUNT_RE.finditer(text):
        stated = (int(m.group(1)), int(m.group(2)), int(m.group(3)))
        if stated != actual:
            line_no = text.count("\n", 0, m.start()) + 1
            drift.append((
                "docs/board-config-schema.md", line_no, m.group(0),
                f"({actual[0]} do today — {actual[1]} on `e1m-evk`, "
                f"{actual[2]} on `e1m-x-evk`)",
            ))
    return drift


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--root", default=str(ROOT),
                        help="repo root to scan (default: the alp-sdk checkout)")
    parser.add_argument("--allow", action="append", default=[], metavar="SYMBOL",
                        help="extend the dead-symbol allowlist (repeatable)")
    args = parser.parse_args(argv)

    root = pathlib.Path(args.root).resolve()
    allow = _ALLOWLIST | set(args.allow)

    known = collect_known_symbols(root) | collect_real_board_names(root)
    dead = find_dead_symbols(root, known, allow)
    gaps = find_index_gaps(root)
    stale_cc3501e = find_cc3501e_bridge_stale_claims(root)
    e1m_x_pinout_gaps = find_e1m_x_pinout_guidance_gaps(root)
    matrix_total_drift = find_matrix_total_drift(root)
    example_preset_count_drift = find_example_preset_count_drift(root)

    if dead:
        print("Dead SDK-symbol references "
              "(token not found in headers / Kconfig / generators):",
              file=sys.stderr)
        for rel, line_no, tok in dead:
            print(f"  {rel}:{line_no}  {tok}", file=sys.stderr)
    if gaps:
        print("Top-level docs/*.md not linked from docs/README.md:",
              file=sys.stderr)
        for name in gaps:
            print(f"  docs/{name}", file=sys.stderr)
    if stale_cc3501e:
        print("Stale CC3501E bridge-current wording "
              "(current rev is hardware SS0 + READY; HOST_IRQ is future):",
              file=sys.stderr)
        for rel, line_no, line in stale_cc3501e:
            print(f"  {rel}:{line_no}  {line}", file=sys.stderr)
    if e1m_x_pinout_gaps:
        print("E1M-only pinout guidance in standalone/general docs "
              "(also mention <alp/e1m_x_pinout.h> / ALP_E1M_X_*):",
              file=sys.stderr)
        for rel, line_no, line in e1m_x_pinout_gaps:
            print(f"  {rel}:{line_no}  {line}", file=sys.stderr)
    if matrix_total_drift:
        print("Portability-matrix totals quoted in narrative docs don't "
              "match the generated docs/portability-matrix.md (regenerate "
              "via scripts/gen_portability_matrix.py, then fix the prose):",
              file=sys.stderr)
        for rel, line_no, matched, expected in matrix_total_drift:
            print(f"  {rel}:{line_no}  \"{matched}\" -- matrix says {expected}",
                  file=sys.stderr)
    if example_preset_count_drift:
        print("Example/preset-adoption count quoted in prose doesn't match "
              "examples/**/board.yaml's preset: fields:", file=sys.stderr)
        for rel, line_no, matched, expected in example_preset_count_drift:
            print(f"  {rel}:{line_no}  \"{matched}\" -- tree says {expected}",
                  file=sys.stderr)

    if (dead or gaps or stale_cc3501e or e1m_x_pinout_gaps
            or matrix_total_drift or example_preset_count_drift):
        print(f"\ndoc-drift: {len(dead)} dead ref(s), {len(gaps)} index "
              f"gap(s), {len(stale_cc3501e)} stale CC3501E bridge "
              f"claim(s), {len(e1m_x_pinout_gaps)} E1M-X pinout "
              f"guidance gap(s), {len(matrix_total_drift)} stale matrix "
              f"total(s), {len(example_preset_count_drift)} stale example "
              f"preset count(s) -- failing.", file=sys.stderr)
        return 1

    print("doc-drift: OK (no dead symbol refs, docs index complete, "
          "CC3501E bridge wording current, E1M-X pinout guidance current, "
          "portability-matrix totals in sync, example preset count in "
          "sync).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
