#!/usr/bin/env python3
# Copyright 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Test-coverage audit: walk every public header in include/alp/, list
the declared functions, and check that at least one test file under
tests/ mentions each one.

Acceptance bar per VERSIONS.md "Quality bar":
   "Every public function: at least one Unity / ztest test."

This script enforces that bar mechanically.  Reports public functions
without any test mention as gaps; CI uses --fail-on-gaps to gate
PRs against new untested public API.

Usage
-----

    python3 scripts/check_test_coverage.py                 # informational
    python3 scripts/check_test_coverage.py --fail-on-gaps  # CI mode

The check is line-grep, not C-parse: a function is "covered" if its
identifier appears anywhere in tests/.  Same heuristic the human
reviewer uses; cheap; works.  False positives possible (a comment
that mentions the function name without exercising it) -- the
follow-up audit is to read the test file when in doubt.

Portable-core vs chip-helper policy (issue #453)
-------------------------------------------------

Gaps split into two buckets by header path:

  * **Portable-core** -- everything under `include/alp/` EXCEPT
    `include/alp/chips/**` (the class surfaces apps call directly:
    `<alp/pwm.h>`, `<alp/can.h>`, `<alp/blocks/*.h>`, ...).  This is
    the SDK's headline API.  `--fail-on-gaps` HARD-fails on ANY
    portable-core gap -- the ratchet value is 0 and it never grows.

  * **Chip-helper** -- `include/alp/chips/**`.  These are the small
    per-IC accessor functions (`_deinit`, `_read_id`, `_soft_reset`,
    register read/write, ...) that come along for free with every new
    chip driver; the SDK ships ~50 chip drivers so this bucket is
    large by construction, not by neglect.  Treated as a bounded,
    explicitly-tracked backlog: `--fail-on-gaps` fails only if the
    count exceeds `CHIP_HELPER_GAP_BUDGET` below (i.e. the backlog
    GREW).  Shrinking it (adding chip tests) does not require a code
    change here -- the check simply reports the lower number; bump
    the budget DOWN in the same PR that shrinks it, so the ratchet
    tightens instead of leaving slack.

Bumping `CHIP_HELPER_GAP_BUDGET` up requires a deliberate PR -- it is
the one number in this file that represents "yes, we're accepting more
untested chip-helper surface," so it should never silently drift.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import Optional


ROOT = pathlib.Path(__file__).resolve().parent.parent

# Portable-core gaps must always be 0 -- see the module docstring.
PORTABLE_GAP_RATCHET = 0

# Chip-helper gaps (include/alp/chips/**) are a bounded, explicitly
# tracked backlog rather than a 0-target: this is the count as of the
# #453 slice that first drew this line.  CI fails if the live count
# exceeds this budget (the backlog grew); it does NOT fail if the
# live count is lower (the backlog shrank) -- ratchet the budget down
# in the same PR when that happens.
CHIP_HELPER_GAP_BUDGET = 210


def _is_chip_helper(header: str) -> bool:
    """True if `header` (relative path like 'alp/chips/bme280.h') is a
    chip-helper header rather than a portable-core one."""
    return header.startswith("alp/chips/")


# Function-declaration regex: captures `<rettype> <name>(...);` lines
# that begin a public declaration.  Skips static / inline definitions
# (those live in impl files, not headers); preprocessor lines starting
# with `#` are stripped before this regex runs.
_FUNC_DECL = re.compile(
    r"^\s*(?!\s*static\b)"
    r"(?:[A-Za-z_][\w\s\*\,\(\)]*?)\s+"
    r"([a-z][a-z0-9_]+)\s*\([^;{]*\)\s*;\s*$",
    re.MULTILINE,
)


# Identifiers that look like functions to the regex but are not real
# public API surface (typedefs of function pointers, callback
# signatures inside structs).  Maintained by hand; small.
_DENYLIST = {
    # Generated by the helper macros, not customer-facing:
    "extern",
}


def list_public_functions(include_root: pathlib.Path) -> dict[str, set[str]]:
    """Return {relative_header_path: {function_names}}."""
    out: dict[str, set[str]] = {}
    for header in sorted(include_root.rglob("*.h")):
        text = header.read_text(encoding="utf-8", errors="replace")
        # Strip block comments cheaply -- the regex doesn't tolerate
        # multi-line /* ... */ wrapping a declaration.
        text_no_blocks = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
        # Strip line comments too.
        text_no_blocks = re.sub(r"//[^\n]*", "", text_no_blocks)
        # Strip preprocessor lines so #define foo(x) doesn't match.
        text_no_blocks = re.sub(r"^\s*#[^\n]*", "", text_no_blocks, flags=re.MULTILINE)
        names = set()
        for m in _FUNC_DECL.finditer(text_no_blocks):
            name = m.group(1)
            if name in _DENYLIST:
                continue
            # Skip typedefs whose return type ended up captured -- a
            # `typedef int (*foo_t)(int)` shape will match but isn't a
            # function declaration.  Cheap heuristic: ignore identifiers
            # that end with `_t` (the SDK's typedef suffix convention).
            if name.endswith("_t"):
                continue
            names.add(name)
        if names:
            rel = header.relative_to(include_root.parent).as_posix()
            out[rel] = names
    return out


def collect_test_mentions(test_root: pathlib.Path) -> set[str]:
    """Return the set of identifiers mentioned in any tests/* file."""
    mentions: set[str] = set()
    for path in test_root.rglob("*"):
        if path.is_file() and path.suffix in (".c", ".cpp", ".cc", ".h", ".py"):
            text = path.read_text(encoding="utf-8", errors="replace")
            # Identifier-shaped tokens.
            for token in re.findall(r"[a-zA-Z_][\w]+", text):
                mentions.add(token)
    return mentions


def collect_example_mentions(example_root: pathlib.Path) -> set[str]:
    """Same as test mentions, but for examples/* (used as a
    soft-pass signal -- a public API exercised by a reference example
    but not by tests still counts as 'covered' for the v1.0 quality
    bar, but flagged as a secondary gap)."""
    mentions: set[str] = set()
    for path in example_root.rglob("*.c"):
        text = path.read_text(encoding="utf-8", errors="replace")
        for token in re.findall(r"[a-zA-Z_][\w]+", text):
            mentions.add(token)
    return mentions


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=pathlib.Path,
        default=ROOT,
        help="repo root to scan (default: the real alp-sdk checkout; "
             "override in tests with a fabricated tree)",
    )
    parser.add_argument(
        "--fail-on-gaps",
        action="store_true",
        help="exit 1 if any public function lacks a test mention",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="list every covered + uncovered symbol (default: only uncovered)",
    )
    args = parser.parse_args(argv)

    include_root = args.root / "include" / "alp"
    test_root    = args.root / "tests"
    example_root = args.root / "examples"

    functions = list_public_functions(include_root)
    tests     = collect_test_mentions(test_root)
    examples  = collect_example_mentions(example_root)

    total       = 0
    test_count  = 0
    ex_only     = 0
    gaps: list[tuple[str, str]] = []

    for header, names in sorted(functions.items()):
        for name in sorted(names):
            total += 1
            if name in tests:
                test_count += 1
                if args.verbose:
                    print(f"OK    {name:50s} -> tests/")
            elif name in examples:
                ex_only += 1
                if args.verbose:
                    print(f"EX    {name:50s} -> examples/ only (acceptable, but no ztest)")
            else:
                gaps.append((header, name))

    portable_gaps = [(h, n) for h, n in gaps if not _is_chip_helper(h)]
    chip_gaps     = [(h, n) for h, n in gaps if _is_chip_helper(h)]

    pct = (100 * test_count / total) if total else 0.0

    print()
    print("Public API coverage:")
    print(f"  Total public functions:    {total}")
    print(f"  Covered by a ztest:        {test_count}  ({pct:.1f}%)")
    print(f"  Exercised by example only: {ex_only}")
    print(f"  Uncovered gaps:            {len(gaps)}")
    print(f"    - portable-core:         {len(portable_gaps)}  (ratchet: must be {PORTABLE_GAP_RATCHET})")
    print(f"    - chip-helper backlog:   {len(chip_gaps)}  (budget: {CHIP_HELPER_GAP_BUDGET})")

    if portable_gaps:
        print()
        print("Portable-core gaps (HARD FAIL under --fail-on-gaps):")
        for header, name in portable_gaps:
            print(f"  {header}::{name}")

    if chip_gaps:
        print()
        print("Chip-helper backlog (bounded; only fails if it GROWS):")
        for header, name in chip_gaps:
            print(f"  {header}::{name}")

    if args.fail_on_gaps:
        failed = False
        if len(portable_gaps) > PORTABLE_GAP_RATCHET:
            print()
            print(f"FAIL: {len(portable_gaps)} portable-core gap(s) > ratchet "
                  f"({PORTABLE_GAP_RATCHET}).  Portable APIs must ship with a "
                  f"real test or example reference -- see issue #453.")
            failed = True
        if len(chip_gaps) > CHIP_HELPER_GAP_BUDGET:
            print()
            print(f"FAIL: {len(chip_gaps)} chip-helper gap(s) > budget "
                  f"({CHIP_HELPER_GAP_BUDGET}).  The chip-helper backlog grew -- "
                  f"either add tests or raise CHIP_HELPER_GAP_BUDGET deliberately "
                  f"in scripts/check_test_coverage.py.")
            failed = True
        if failed:
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
