#!/usr/bin/env python3
# Copyright 2026 ALP Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Test-coverage audit: walk every public header in include/alp/, list
the declared functions, and check that at least one test file under
tests/ mentions each one.

Acceptance bar per VERSIONS.md "Quality bar":
   "Every public function: at least one Unity / ztest test."

This script enforces that bar mechanically.  Reports public functions
without any test mention as gaps; CI uses --fail-on-gaps to gate
PRs against new untested public API.

Usage
-----

    python3 scripts/check_test_coverage.py                 # informational
    python3 scripts/check_test_coverage.py --fail-on-gaps  # CI mode

The check is line-grep, not C-parse: a function is "covered" if its
identifier appears anywhere in tests/.  Same heuristic the human
reviewer uses; cheap; works.  False positives possible (a comment
that mentions the function name without exercising it) -- the
follow-up audit is to read the test file when in doubt.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import Optional


ROOT          = pathlib.Path(__file__).resolve().parent.parent
INCLUDE_ROOT  = ROOT / "include" / "alp"
TEST_ROOT     = ROOT / "tests"
EXAMPLE_ROOT  = ROOT / "examples"

# Function-declaration regex: captures `<rettype> <name>(...);` lines
# that begin a public declaration.  Skips static / inline definitions
# (those live in impl files, not headers); preprocessor lines starting
# with `#` are stripped before this regex runs.
_FUNC_DECL = re.compile(
    r"^\s*(?!\s*static\b)"
    r"(?:[A-Za-z_][\w\s\*\,\(\)]*?)\s+"
    r"([a-z][a-z0-9_]+)\s*\([^;{]*\)\s*;\s*$",
    re.MULTILINE,
)


# Identifiers that look like functions to the regex but are not real
# public API surface (typedefs of function pointers, callback
# signatures inside structs).  Maintained by hand; small.
_DENYLIST = {
    # Generated by the helper macros, not customer-facing:
    "extern",
}


def list_public_functions() -> dict[str, set[str]]:
    """Return {relative_header_path: {function_names}}."""
    out: dict[str, set[str]] = {}
    for header in sorted(INCLUDE_ROOT.rglob("*.h")):
        text = header.read_text(encoding="utf-8", errors="replace")
        # Strip block comments cheaply -- the regex doesn't tolerate
        # multi-line /* ... */ wrapping a declaration.
        text_no_blocks = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
        # Strip line comments too.
        text_no_blocks = re.sub(r"//[^\n]*", "", text_no_blocks)
        # Strip preprocessor lines so #define foo(x) doesn't match.
        text_no_blocks = re.sub(r"^\s*#[^\n]*", "", text_no_blocks, flags=re.MULTILINE)
        names = set()
        for m in _FUNC_DECL.finditer(text_no_blocks):
            name = m.group(1)
            if name in _DENYLIST:
                continue
            # Skip typedefs whose return type ended up captured -- a
            # `typedef int (*foo_t)(int)` shape will match but isn't a
            # function declaration.  Cheap heuristic: ignore identifiers
            # that end with `_t` (the SDK's typedef suffix convention).
            if name.endswith("_t"):
                continue
            names.add(name)
        if names:
            rel = header.relative_to(INCLUDE_ROOT.parent).as_posix()
            out[rel] = names
    return out


def collect_test_mentions() -> set[str]:
    """Return the set of identifiers mentioned in any tests/* file."""
    mentions: set[str] = set()
    for path in TEST_ROOT.rglob("*"):
        if path.is_file() and path.suffix in (".c", ".cpp", ".cc", ".h", ".py"):
            text = path.read_text(encoding="utf-8", errors="replace")
            # Identifier-shaped tokens.
            for token in re.findall(r"[a-zA-Z_][\w]+", text):
                mentions.add(token)
    return mentions


def collect_example_mentions() -> set[str]:
    """Same as test mentions, but for examples/* (used as a
    soft-pass signal -- a public API exercised by a reference example
    but not by tests still counts as 'covered' for the v1.0 quality
    bar, but flagged as a secondary gap)."""
    mentions: set[str] = set()
    for path in EXAMPLE_ROOT.rglob("*.c"):
        text = path.read_text(encoding="utf-8", errors="replace")
        for token in re.findall(r"[a-zA-Z_][\w]+", text):
            mentions.add(token)
    return mentions


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fail-on-gaps",
        action="store_true",
        help="exit 1 if any public function lacks a test mention",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="list every covered + uncovered symbol (default: only uncovered)",
    )
    args = parser.parse_args(argv)

    functions = list_public_functions()
    tests     = collect_test_mentions()
    examples  = collect_example_mentions()

    total       = 0
    test_count  = 0
    ex_only     = 0
    gaps: list[tuple[str, str]] = []

    for header, names in sorted(functions.items()):
        for name in sorted(names):
            total += 1
            if name in tests:
                test_count += 1
                if args.verbose:
                    print(f"OK    {name:50s} -> tests/")
            elif name in examples:
                ex_only += 1
                if args.verbose:
                    print(f"EX    {name:50s} -> examples/ only (acceptable, but no ztest)")
            else:
                gaps.append((header, name))

    print()
    print("Public API coverage:")
    print(f"  Total public functions:    {total}")
    print(f"  Covered by a ztest:        {test_count}  ({100*test_count/total:.1f}%)")
    print(f"  Exercised by example only: {ex_only}")
    print(f"  Uncovered gaps:            {len(gaps)}")

    if gaps:
        print()
        print("Gaps (no test or example mentions):")
        for header, name in gaps:
            print(f"  {header}::{name}")

    if args.fail_on_gaps and gaps:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
