#!/usr/bin/env python3
# Copyright 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Generate the per-family pin-mux capability table from the SoM pinout TSVs.

The E1M-AEN family ships its pinout as two pad-claim TSVs:

    metadata/e1m_modules/aen/from-alif.tsv      (Alif-Ensemble-owned pads)
    metadata/e1m_modules/aen/from-cc3501e.tsv   (TI CC3501E-owned pads)

These are the single source.  Tools (the `alp` CLI / the IDE) want one
structured, schema'd table rather than five heterogeneous TSVs, so this
generator projects the two pad-claim TSVs into:

    metadata/pinmux/aen.yaml   (schema: pinmux-capability-v1)

Each row becomes one pad entry: { e1m_pad, e1m_function, owner,
silicon_peripheral, silicon_pad }.  The emitted file is validated against
the schema before it is written, and a CI regen-diff gate keeps it
byte-in-sync with the TSVs (so the structured table can never drift from
the source).  Pad exclusivity is enforced separately by
scripts/check_pin_conflicts.py.

Usage:

    python3 scripts/gen_pinmux_capability.py            # regenerate in place
    python3 scripts/gen_pinmux_capability.py --check     # fail if out of sync
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import jsonschema

try:
    import yaml  # type: ignore[import-untyped]
except ImportError:
    sys.exit("gen_pinmux_capability: PyYAML is required.  "
             "Install via `pip install pyyaml`.")

REPO = Path(__file__).resolve().parent.parent
MODULES = REPO / "metadata" / "e1m_modules"
PINMUX_DIR = REPO / "metadata" / "pinmux"
SCHEMA = REPO / "metadata" / "schemas" / "pinmux-capability-v1.schema.json"

# Per-family generation spec: which pad-claim TSVs feed the table and how
# each maps onto the common pad entry.  `owner` is the on-module silicon
# that drives the pad; columns are (e1m_pad, e1m_function, peripheral, pad).
FAMILIES: dict[str, dict] = {
    "aen": {
        "display_name": "E1M-AEN (Alif Ensemble)",
        "sources": [
            {"file": "aen/from-alif.tsv", "owner": "alif"},
            {"file": "aen/from-cc3501e.tsv", "owner": "cc3501e"},
        ],
    },
}


def _read_tsv_rows(path: Path) -> list[list[str]]:
    """Return data rows (header + blank + comment lines stripped)."""
    rows: list[list[str]] = []
    with path.open(encoding="utf-8") as fi:
        for line in fi:
            s = line.rstrip("\n")
            if not s or s.startswith("#") or s.startswith("e1m_pad\t"):
                continue
            rows.append(s.split("\t"))
    return rows


def _pads_for_family(spec: dict) -> list[dict[str, str]]:
    """Project a family's pad-claim TSVs into ordered pad entries."""
    pads: list[dict[str, str]] = []
    for src in spec["sources"]:
        path = MODULES / src["file"]
        for row in _read_tsv_rows(path):
            if len(row) < 4:
                raise SystemExit(
                    f"gen_pinmux_capability: malformed row in {src['file']!r}: "
                    f"{row!r} (expected 4 tab-separated columns)")
            pads.append({
                "e1m_pad": row[0].strip(),
                "e1m_function": row[1].strip(),
                "owner": src["owner"],
                "silicon_peripheral": row[2].strip(),
                "silicon_pad": row[3].strip(),
            })
    return pads


def _yaml_quote(value: str) -> str:
    """Double-quote a scalar for the flow-style emitter (stable + safe)."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render(family: str, spec: dict, pads: list[dict[str, str]]) -> str:
    """Hand-roll the YAML so output is byte-stable across PyYAML versions."""
    lines = [
        "# Auto-generated by scripts/gen_pinmux_capability.py from",
        f"# metadata/e1m_modules/{family}/*.tsv.  DO NOT EDIT BY HAND -- regenerate:",
        "#     python3 scripts/gen_pinmux_capability.py",
        "# Schema: metadata/schemas/pinmux-capability-v1.schema.json",
        "#",
        "# Structured, queryable projection of the pin-mux: each E1M edge pad ->",
        "# the silicon function/peripheral that backs it, and which on-module",
        "# silicon owns it.  The TSVs remain the single source; this file is gated",
        "# byte-in-sync.  Pad exclusivity is gated by scripts/check_pin_conflicts.py.",
        "schemaVersion: pinmux-capability-v1",
        f"family: {family}",
        f"display_name: {_yaml_quote(spec['display_name'])}",
        "pads:",
    ]
    for p in pads:
        lines.append(
            "  - { "
            f"e1m_pad: {_yaml_quote(p['e1m_pad'])}, "
            f"e1m_function: {_yaml_quote(p['e1m_function'])}, "
            f"owner: {_yaml_quote(p['owner'])}, "
            f"silicon_peripheral: {_yaml_quote(p['silicon_peripheral'])}, "
            f"silicon_pad: {_yaml_quote(p['silicon_pad'])} "
            "}"
        )
    return "\n".join(lines) + "\n"


def _validate(text: str, family: str) -> None:
    """Round-trip the emitted YAML through the schema before trusting it."""
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    doc = yaml.safe_load(text)
    errors = sorted(jsonschema.Draft202012Validator(schema).iter_errors(doc),
                    key=lambda e: list(e.absolute_path))
    if errors:
        loc = "\n".join(
            f"  · {'/'.join(str(p) for p in e.absolute_path) or '<root>'}: {e.message}"
            for e in errors)
        raise SystemExit(
            f"gen_pinmux_capability: emitted {family}.yaml fails schema:\n{loc}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail (exit 1) if any table is out of sync with the TSVs")
    args = ap.parse_args()

    PINMUX_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for family, spec in FAMILIES.items():
        pads = _pads_for_family(spec)
        text = _render(family, spec, pads)
        _validate(text, family)
        out = PINMUX_DIR / f"{family}.yaml"
        if args.check:
            current = out.read_text(encoding="utf-8") if out.is_file() else ""
            if current != text:
                stale.append(family)
            else:
                print(f"OK   {out.relative_to(REPO)}  ({len(pads)} pads, in sync)")
        else:
            out.write_text(text, encoding="utf-8")
            print(f"wrote {out.relative_to(REPO)}  ({len(pads)} pads)")

    if args.check and stale:
        print(f"\ngen_pinmux_capability: {', '.join(stale)} out of sync -- run "
              "`python3 scripts/gen_pinmux_capability.py` and commit the result.",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
