#!/usr/bin/env python3
# Copyright 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Generate src/backends/rpc/alp_amp_window.h: the A55-side constants of the
CM33 OpenAMP shared window, projected from the SoC description's
`openamp_carveout` block (metadata/socs/renesas/rzv2n/n44.json).

The window is a hardware fact, declared once.  The CM33 board .dts is
generated from the same block by gen_zephyr_board.py; the Linux
reserved-memory/UIO nodes are hand-written and pinned to it by
scripts/check_amp_window.py.  The beacon LAYOUT (offsets from the window
end) is not hardware and lives in include/alp/protocol/amp_beacon.h.

    python3 scripts/gen_amp_window.py           # rewrite the header
    python3 scripts/gen_amp_window.py --check   # exit 1 if it is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOC_JSON = Path("metadata/socs/renesas/rzv2n/n44.json")
OUT = Path("src/backends/rpc/alp_amp_window.h")


def load_carveout(root: Path = REPO) -> dict:
    return json.loads((root / SOC_JSON).read_text(encoding="utf-8"))["openamp_carveout"]


def render(c: dict) -> str:
    a55, cm33, rsc = c["a55_base"], c["cm33_ns_base"], c["rsctbl_size"]
    return f"""\
/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by scripts/gen_amp_window.py from {SOC_JSON.as_posix()}
 * (`openamp_carveout`) -- do not edit; regenerate.
 *
 * The CM33 OpenAMP shared window as the A55 sees it.  The beacon words
 * sit in the last ALP_AMP_BEACON_SIZE bytes of the rsctbl page, laid out
 * by include/alp/protocol/amp_beacon.h.
 */

#ifndef ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H
#define ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H

#define ALP_AMP_A55_BASE     {a55:#x}u
#define ALP_AMP_SIZE         {c['size']:#x}u
#define ALP_AMP_RSCTBL_SIZE  {rsc:#x}u
#define ALP_AMP_MHU_SHM_BASE {a55 + rsc:#x}u
#define ALP_AMP_CM33_NS_BASE {cm33:#x}u
/* CM33-NS address = A55 address + this. */
#define ALP_AMP_A55_TO_CM33_NS_OFFSET {cm33 - a55:#x}u
/* A55 address of the liveness beacon. */
#define ALP_AMP_BEACON_A55_ADDR {a55 + rsc - 16:#x}u

/* sysfs names of the generic-uio nodes: "<unit-address>.<node-name>". */
#define ALP_AMP_UIO_RSCTBL_NAME  "{a55:x}.rsctbl"
#define ALP_AMP_UIO_MHU_SHM_NAME "{a55 + rsc:x}.mhu-shm"

#endif /* ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H */
"""


def main(argv: list[str]) -> int:
    text = render(load_carveout())
    out = REPO / OUT
    if "--check" in argv:
        if not out.is_file() or out.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
            print(f"{OUT}: stale -- run python3 scripts/gen_amp_window.py", file=sys.stderr)
            return 1
        return 0
    out.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
