#!/usr/bin/env python3
# Copyright 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Generate metadata/error-catalog.json from the SDK's two single sources of
truth for error/diagnostic codes:

  * API errors      -- the `ALP_ERR_*` members of the `alp_status_t` enum in
                       include/alp/peripheral.h, with their Doxygen `/**< */`
                       comments.
  * Runtime         -- the ALP-Bxxx diagnostic landing pages in
    diagnostics       docs/diagnostics/ALP-B*.md, whose heading + body carry
                       the human-readable narrative (cause / fix).

The catalog is what `alp explain <code>` reads, so a firmware engineer (or
their agent) can type `alp explain ALP_ERR_NO_BACKEND` (or `alp explain
ALP-B003`) and get the cause/fix/doc-link instead of grepping headers.

NO TEXT IS INVENTED here: every field is lifted verbatim from the enum
comment or the markdown.  A field that has no source (e.g. an api-error with
no `## Fix` section -- there are none) is OMITTED, never fabricated.

The emit is byte-stable (sorted keys, fixed indent, trailing newline) and
carries an AUTO-GENERATED banner, mirroring scripts/gen_soc_caps.py /
scripts/gen_support_matrix.py.  A CI drift gate
(.github/workflows/pr-generated-files.yml) reruns this with --check and
fails the PR if the committed JSON drifts from the headers/docs.

Usage:

    python3 scripts/gen_error_catalog.py            # regenerate in place
    python3 scripts/gen_error_catalog.py --check    # fail (exit 1) if stale
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HEADER = REPO / "include" / "alp" / "peripheral.h"
DIAG_DIR = REPO / "docs" / "diagnostics"
OUT = REPO / "metadata" / "error-catalog.json"

BANNER = (
    "AUTO-GENERATED by scripts/gen_error_catalog.py -- DO NOT EDIT; "
    "regenerate.  Source: include/alp/peripheral.h (ALP_ERR_* enum) + "
    "docs/diagnostics/ALP-B*.md.  CI gate: "
    ".github/workflows/pr-generated-files.yml."
)

# The enum whose ALP_ERR_* members are the api-error source of truth.
_ENUM_NAME = "alp_status_t"
# An enum member `ALP_ERR_NAME = -N,` with an optional trailing Doxygen
# `/**< ... */` comment.  The `= -N` value may sit on the same line or wrap
# to the next (the wide members do), and the comment FOLLOWS the comma, so
# we match across newlines (re.DOTALL) rather than line-by-line.
_MEMBER_RE = re.compile(
    r"\b(ALP_ERR_[A-Z0-9_]+)\b"          # the code
    r"\s*=\s*-?\d+"                       # = -N   (may wrap a newline)
    r"\s*,?\s*"                           # optional comma
    r"(?:/\*\*<\s*(?P<doc>.*?)\s*\*/)?",  # optional Doxygen `/**< ... */`
    re.DOTALL,
)


def _collapse_ws(text: str) -> str:
    """Squash internal runs of whitespace/newlines to single spaces."""
    return re.sub(r"\s+", " ", text).strip()


def _rel(path: Path) -> str:
    """Repo-relative POSIX path, or the bare name if outside the repo."""
    try:
        return path.resolve().relative_to(REPO).as_posix()
    except ValueError:
        return path.name


def parse_api_errors(header: Path) -> dict[str, dict]:
    """Parse the `alp_status_t` enum into {code: entry} for every ALP_ERR_*."""
    src = header.read_text(encoding="utf-8")
    m = re.search(
        r"typedef\s+enum\s*\{(?P<body>.*?)\}\s*" + _ENUM_NAME + r"\s*;",
        src, re.DOTALL,
    )
    if not m:
        raise SystemExit(
            f"gen_error_catalog: could not find `{_ENUM_NAME}` enum in "
            f"{header.relative_to(REPO)}")
    body = m.group("body")
    rel = header.relative_to(REPO).as_posix()

    entries: dict[str, dict] = {}
    for mem in _MEMBER_RE.finditer(body):
        code = mem.group(1)
        if code in entries:
            continue  # @ref cross-references inside comments, ignore dups
        doc = mem.group("doc")
        entry: dict[str, str] = {
            "code": code,
            "kind": "api-error",
            "doc": rel,
        }
        if doc:
            entry["summary"] = _collapse_ws(doc)
        entries[code] = entry
    if not entries:
        raise SystemExit(
            f"gen_error_catalog: no ALP_ERR_* members found in `{_ENUM_NAME}`")
    return entries


# Markdown `## <name>` section headers we lift into structured fields.
_SECTION_FIELD = {
    "cause": "cause",
    "why": "cause",
    "fix": "fix",
    "resolution": "fix",
    "remedy": "fix",
}


def _split_sections(lines: list[str]) -> tuple[list[str], dict[str, list[str]]]:
    """Split body lines into (intro, {section_name_lower: lines})."""
    intro: list[str] = []
    sections: dict[str, list[str]] = {}
    current: list[str] = intro
    for ln in lines:
        h = re.match(r"^#{2,}\s+(.*)$", ln)
        if h:
            name = _collapse_ws(h.group(1)).lower()
            current = sections.setdefault(name, [])
            continue
        current.append(ln)
    return intro, sections


def _para(lines: list[str]) -> str | None:
    """Collapse markdown lines to a single narrative string, or None."""
    text = _collapse_ws("\n".join(lines))
    return text or None


def parse_runtime_diagnostic(path: Path) -> dict:
    """Parse one docs/diagnostics/ALP-Bxxx.md into a catalog entry."""
    code = path.stem  # e.g. ALP-B003
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    heading = ""
    rest_start = 0
    for i, ln in enumerate(lines):
        if ln.startswith("#"):
            heading = ln.lstrip("#").strip()
            rest_start = i + 1
            break

    intro, sections = _split_sections(lines[rest_start:])

    entry: dict[str, str] = {
        "code": code,
        "kind": "runtime-diagnostic",
        "doc": _rel(path),
    }

    # A descriptive heading (anything beyond the bare code) is the summary;
    # otherwise the intro narrative paragraph is.
    title = heading
    if title.startswith(code):
        title = title[len(code):].lstrip(" :-—").strip()
    summary = title or _para(intro)
    if summary:
        entry["summary"] = _collapse_ws(summary)

    for name, field in _SECTION_FIELD.items():
        if name in sections and field not in entry:
            val = _para(sections[name])
            if val:
                entry[field] = val
    return entry


def parse_runtime_diagnostics(diag_dir: Path) -> dict[str, dict]:
    """Parse every ALP-B*.md into {code: entry}."""
    entries: dict[str, dict] = {}
    for path in sorted(diag_dir.glob("ALP-B*.md")):
        entry = parse_runtime_diagnostic(path)
        entries[entry["code"]] = entry
    return entries


def build_catalog() -> dict:
    """Assemble the full byte-stable catalog object."""
    codes: dict[str, dict] = {}
    codes.update(parse_api_errors(HEADER))
    codes.update(parse_runtime_diagnostics(DIAG_DIR))
    return {"_banner": BANNER, "codes": codes}


def render(catalog: dict) -> str:
    """Serialise the catalog byte-stably (sorted, indented, trailing \\n)."""
    return json.dumps(
        catalog, indent=2, sort_keys=True, ensure_ascii=False,
    ) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail (exit 1) if the catalog is out of sync with "
                         "the headers / diagnostic docs")
    args = ap.parse_args()

    catalog = build_catalog()
    text = render(catalog)
    n = len(catalog["codes"])

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print("gen_error_catalog: metadata/error-catalog.json is out of "
                  "sync -- run `python3 scripts/gen_error_catalog.py` and "
                  "commit the result.", file=sys.stderr)
            return 1
        print(f"OK   {OUT.relative_to(REPO)}  ({n} codes, in sync)")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}  ({n} codes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
