#!/usr/bin/env python3
# Copyright 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Regenerate metadata/npu_ops/ethos_u/*.json from the real `vela` toolchain's
own supported-ops report -- never hand-transcribed.

Vela publishes exactly TWO TFLite operator-support tables
(`## Ethos-U85 TFLite Summary Table`, `## Ethos-U55 and Ethos-U65 TFLite
Summary Table`), and both are invariant to `--accelerator-config` (verified
by regenerating at ethos-u55-32, ethos-u55-256, ethos-u65-512, ethos-u85-128
and ethos-u85-2048: identical report). That is the real unit of identity, so
this script emits one file per TABLE, keyed by (variant, toolchain,
toolchain_version) -- not one file per silicon SKU:

    metadata/npu_ops/ethos_u/u85@vela-<version>.json
    metadata/npu_ops/ethos_u/u55-u65@vela-<version>.json

`vela --supported-ops-report` writes `SUPPORTED_OPS.md` into the CURRENT
WORKING DIRECTORY (it has no --output-dir of its own), so this script runs
it inside a scratch tempdir.

The TOSA tables in the same report are ignored -- the Vela adapter
(`tan.model.adapters.ethos_u`, tan-cli; formerly `scripts/alp_model/adapters/
ethos_u.py` here before ADR-0028) accepts only `src_format == "tflite"`.

This script does NOT touch metadata/npu_ops/drpai/ -- the DRP-AI Translator
publishes no machine-readable report, only a vendor PDF manual, so that
table is hand-transcribed (`"authority": "vendor-manual"`) and is out of
scope for a tool-wrapping generator. It does not touch metadata/npu_ops/
deepx/ either -- that directory does not exist, deliberately (see
changelog.d/1470.md): DEEPX's dxcom publishes no op-support table at all.

NOT in test-all.sh's `stage_generated_files` `gens` array (unlike
gen_soc_caps.py & co): that array always REGENERATES (unconditional write),
and every other generator in it needs at most PyYAML + jsonschema, or
clang-format, which are already baseline dependencies of this repo's own
gates. `vela` is the heavy, license-clean but multi-hundred-MB
`model-compile` optional extra, not something every contributor or CI
runner has -- same reasoning that keeps the DRP-AI/DEEPX toolchains
bench-gated rather than CI-required elsewhere in this repo.

`stage_generated_files` DOES still call this script, separately, in
`--check` (read-only) mode: `_find_vela()` fails fast with exit 2 the
instant `vela` isn't on PATH, before anything toolchain-heavy runs, so the
call costs nothing on a host without vela and the stage treats exit 2 as a
clean SKIP -- not a stage failure, and not a reason to install vela. On a
host that DOES have vela, `--check` catches metadata/npu_ops/ethos_u/ drift
the same way every other generator's regen-then-diff does. Regenerating for
real (writing new files, e.g. after the `ethos-u-vela` pin in
pyproject.toml's `model-compile` extra moves) is still a by-hand step.

Usage:

    python3 scripts/gen_npu_ops.py            # regenerate in place
    python3 scripts/gen_npu_ops.py --check    # fail (exit 1) if stale
    python3 scripts/gen_npu_ops.py --vela /path/to/vela

Exit codes: 0 success/in-sync, 1 stale (--check) or a real generator defect,
2 `vela` is unavailable to run at all (in either mode).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT_DIR = REPO / "metadata" / "npu_ops" / "ethos_u"

_U85_HEADING = "Ethos-U85 TFLite Summary Table"
_U55_U65_HEADING = "Ethos-U55 and Ethos-U65 TFLite Summary Table"

# The exact Ethos-U85-only delta over Ethos-U55/U65, asserted rather than
# assumed. A real future vela release COULD change this; if it does, this
# script stops and reports the disagreement instead of silently accepting
# a new delta -- see build_tables().
_EXPECTED_U85_ONLY_DELTA = sorted([
    "CAST", "DIV", "EQUAL", "GATHER", "GREATER", "GREATER_EQUAL", "LESS",
    "LESS_EQUAL", "LOGICAL_AND", "LOGICAL_NOT", "LOGICAL_OR", "NOT_EQUAL",
    "REDUCE_ALL", "REDUCE_ANY", "SCATTER_ND", "SELECT", "SELECT_V2",
])

_BANNER = ("AUTO-GENERATED by scripts/gen_npu_ops.py -- DO NOT EDIT; "
           "regenerate: python3 scripts/gen_npu_ops.py")


def _find_vela(explicit: str | None) -> str:
    vela = explicit or shutil.which("vela")
    if not vela:
        raise SystemExit(
            "gen_npu_ops: `vela` not found on PATH. Install the model-compile "
            "extra (pip install -e '.[model-compile]') or pass --vela "
            "/path/to/vela.")
    return vela


def _vela_version(vela: str) -> str:
    proc = subprocess.run([vela, "--version"], capture_output=True,
                          text=True, check=True)
    return proc.stdout.strip()


def _run_vela_report(vela: str, workdir: Path) -> str:
    """Run `vela --supported-ops-report` in `workdir` and return the report
    text. No --output-dir exists for this report -- it always lands at
    ./SUPPORTED_OPS.md relative to the process cwd, hence the scratch dir."""
    subprocess.run([vela, "--supported-ops-report"], cwd=workdir, check=True,
                    capture_output=True, text=True)
    report = workdir / "SUPPORTED_OPS.md"
    if not report.is_file():
        raise SystemExit("gen_npu_ops: vela did not write SUPPORTED_OPS.md")
    return report.read_text(encoding="utf-8")


def _extract_table(lines: list[str], heading: str) -> list[str]:
    """Column 1 of the markdown table under `## <heading>`, in document
    order (deduped by the caller)."""
    start = None
    for i, line in enumerate(lines):
        if line.strip() == f"## {heading}":
            start = i
            break
    if start is None:
        raise SystemExit(
            f"gen_npu_ops: heading '## {heading}' not found in "
            f"SUPPORTED_OPS.md -- did the vela report format change?")
    i = start
    while i < len(lines) and not lines[i].startswith("| Operator"):
        i += 1
        if i >= len(lines):
            raise SystemExit(
                f"gen_npu_ops: no '| Operator |' table found under "
                f"'## {heading}'")
    i += 2  # header row, then the '| --- |' separator row
    ops: list[str] = []
    while i < len(lines) and lines[i].startswith("|"):
        cell = lines[i].split("|")[1].strip()
        if cell:
            ops.append(cell)
        i += 1
    return ops


def build_tables(vela: str) -> dict[str, dict]:
    """Run vela, parse both TFLite summary tables, assert the U55/U65 <=
    U85 subset invariant + the exact known delta, and return
    {"u85": <doc>, "u55-u65": <doc>}."""
    version = _vela_version(vela)
    with tempfile.TemporaryDirectory(prefix="gen-npu-ops-vela-") as tmp:
        text = _run_vela_report(vela, Path(tmp))
    content_hash = "md5:" + hashlib.md5(text.encode("utf-8")).hexdigest()
    lines = text.splitlines()

    u85 = sorted(set(_extract_table(lines, _U85_HEADING)))
    u55_u65 = sorted(set(_extract_table(lines, _U55_U65_HEADING)))

    if not set(u55_u65) <= set(u85):
        stray = sorted(set(u55_u65) - set(u85))
        raise SystemExit(
            "gen_npu_ops: Ethos-U55/U65 is NOT a subset of Ethos-U85 -- ops "
            f"only in U55/U65: {stray}. Refusing to guess -- report this, "
            "don't force the data.")
    delta = sorted(set(u85) - set(u55_u65))
    if delta != _EXPECTED_U85_ONLY_DELTA:
        raise SystemExit(
            "gen_npu_ops: the Ethos-U85-only op delta over U55/U65 no "
            "longer matches the pinned expectation.\n"
            f"  expected ({len(_EXPECTED_U85_ONLY_DELTA)}): {_EXPECTED_U85_ONLY_DELTA}\n"
            f"  actual   ({len(delta)}): {delta}\n"
            "STOPPING -- this needs a human to confirm it's a real vela "
            "change (then update _EXPECTED_U85_ONLY_DELTA deliberately), "
            "not a script that silently accepts a new delta.")

    common_provenance_note = (
        "SUPPORTED_OPS.md is invariant to --accelerator-config (verified by "
        "regenerating at ethos-u55-32, ethos-u55-256, ethos-u65-512, "
        "ethos-u85-128 and ethos-u85-2048: identical report). Only the "
        "TFLite table is used -- the TOSA tables in the same report are out "
        "of scope (tan.model.adapters.ethos_u accepts only "
        "src_format == \"tflite\")."
    )

    tables: dict[str, dict] = {}
    tables["u85"] = {
        "_generated": _BANNER,
        "applies_to": {
            "variant": "u85",
            "products": ["ethos-u85"],
            "toolchain": "vela",
            "toolchain_version": version,
        },
        "op_namespace": "tflite",
        "authority": "tool-generated",
        "stance": "screening",
        "provenance": {
            "source": (f"vela --supported-ops-report, table "
                      f"'## {_U85_HEADING}' (column 1)"),
            "tool_version": f"vela {version}",
            "content_hash": content_hash,
            "note": common_provenance_note,
        },
        "supported_ops": u85,
    }
    tables["u55-u65"] = {
        "_generated": _BANNER,
        "applies_to": {
            "variant": "u55-u65",
            "products": ["ethos-u55", "ethos-u65"],
            "toolchain": "vela",
            "toolchain_version": version,
        },
        "op_namespace": "tflite",
        "authority": "tool-generated",
        "stance": "screening",
        "provenance": {
            "source": (f"vela --supported-ops-report, table "
                      f"'## {_U55_U65_HEADING}' (column 1)"),
            "tool_version": f"vela {version}",
            "content_hash": content_hash,
            "note": (common_provenance_note + " A strict subset of the U85 "
                    "table -- see u85@vela-*.json's supported_ops for the "
                    "17-op delta this SKU lacks."),
        },
        "supported_ops": u55_u65,
    }
    return tables


def render(doc: dict) -> str:
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--vela", default=None,
                    help="path to the vela executable (default: PATH)")
    ap.add_argument("--check", action="store_true",
                    help="fail (exit 1) if metadata/npu_ops/ethos_u/*.json is "
                         "stale; exit 2 if vela is unavailable to check with")
    args = ap.parse_args()

    try:
        vela = _find_vela(args.vela)
    except SystemExit as exc:
        # 2, not the default 1, in EITHER mode: a missing vela is a
        # prerequisite gap, not a generator defect or a real drift --
        # distinguishing it lets a caller (e.g. a human script, never
        # test-all.sh -- see the module docstring) tell "install vela" apart
        # from "the tree is stale" or "the report changed unexpectedly".
        print(str(exc), file=sys.stderr)
        return 2

    tables = build_tables(vela)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ok = True
    written_names: set[str] = set()
    for doc in tables.values():
        at = doc["applies_to"]
        stem = f"{at['variant']}@{at['toolchain']}-{at['toolchain_version']}"
        target = OUT_DIR / f"{stem}.json"
        written_names.add(target.name)
        text = render(doc)
        if args.check:
            current = target.read_text(encoding="utf-8") if target.is_file() else ""
            if current != text:
                print(f"STALE {target.relative_to(REPO)}", file=sys.stderr)
                ok = False
            else:
                print(f"OK    {target.relative_to(REPO)}")
        else:
            target.write_text(text, encoding="utf-8", newline="")
            print(f"wrote {target.relative_to(REPO)}  "
                  f"({len(doc['supported_ops'])} ops)")

    # A previous vela pin can leave behind a now-superseded filename for a
    # variant this script owns (e.g. u85@vela-4.x.json after a version
    # bump) -- clean those up so the directory never carries two tables for
    # the same variant.
    owned_prefixes = tuple(f"{name.split('@', 1)[0]}@vela-" for name in written_names)
    for existing in sorted(OUT_DIR.glob("*.json")):
        if existing.name in written_names:
            continue
        if existing.name.startswith(owned_prefixes):
            if args.check:
                print(f"STALE {existing.relative_to(REPO)}  "
                      f"(superseded vela version)", file=sys.stderr)
                ok = False
            else:
                existing.unlink()
                print(f"removed {existing.relative_to(REPO)}  "
                      f"(superseded vela version)")

    if args.check and not ok:
        print("gen_npu_ops: metadata/npu_ops/ethos_u/ is out of sync -- run "
              "`python3 scripts/gen_npu_ops.py` and commit the result.",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
