#!/usr/bin/env python3
# Copyright 2026 Alp Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Generate src/backends/rpc/alp_amp_window.h: the A55-side constants of the
CM33 OpenAMP shared window, projected from the SoC description's
`openamp_carveout` block (metadata/socs/renesas/rzv2n/n44.json).

The window and every sub-region in it (rsctbl page, mhu-shm, vring-ctl0/1,
vring-shm0/1) are hardware facts, declared once as offset+size inside the
carveout.  The CM33 board .dts is generated from the same block by
gen_zephyr_board.py; the Linux reserved-memory/UIO nodes are hand-written
and pinned to it by scripts/check_amp_window.py.  The beacon LAYOUT (offsets
from the end of the rsctbl page) is not hardware and lives in
include/alp/protocol/amp_beacon.h.

    python3 scripts/gen_amp_window.py           # rewrite the header
    python3 scripts/gen_amp_window.py --check   # exit 1 if it is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOC_JSON = Path("metadata/socs/renesas/rzv2n/n44.json")
OUT = Path("src/backends/rpc/alp_amp_window.h")


def load_carveout(root: Path = REPO) -> dict:
    return json.loads((root / SOC_JSON).read_text(encoding="utf-8"))["openamp_carveout"]


def regions(c: dict) -> dict[str, tuple[int, int]]:
    """name -> (A55 address, size) of each sub-region of the carveout."""
    return {n: (c["a55_base"] + r["offset"], r["size"]) for n, r in c["regions"].items()}


def render(c: dict) -> str:
    rows = [("ALP_AMP_A55_TO_CM33_NS_OFFSET", f"{c['cm33_ns_base'] - c['a55_base']:#x}u")]
    for name, (addr, size) in regions(c).items():
        m = name.upper().replace("-", "_")
        rows += [
            (f"ALP_AMP_{m}_A55_BASE", f"{addr:#x}u"),
            (f"ALP_AMP_{m}_SIZE", f"{size:#x}u"),
            (f"ALP_AMP_UIO_{m}_NAME", f'"{addr:x}.{name}"'),
        ]
    rc = c["ram_console"]
    rows += [
        ("ALP_AMP_RAM_CONSOLE_A55_BASE", f"{c['a55_base'] + rc['offset']:#x}u"),
        ("ALP_AMP_RAM_CONSOLE_SIZE", f"{rc['size']:#x}u"),
    ]
    w = max(len(k) for k, _ in rows)
    defs = "\n".join(f"#define {k.ljust(w)} {v}" for k, v in rows)
    return f"""\
/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * GENERATED by scripts/gen_amp_window.py from {SOC_JSON.as_posix()}
 * (`openamp_carveout`) -- do not edit; regenerate.
 *
 * The CM33 OpenAMP shared window as the A55 sees it: each sub-region's
 * A55 base and size, and the sysfs name of its generic-uio node
 * ("<unit-address>.<node-name>"), plus the CM33 RAM console buffer (no UIO
 * node; the A55 reads it post-mortem via /dev/mem).  The beacon words sit in the last
 * ALP_AMP_BEACON_SIZE bytes of the rsctbl page, laid out by
 * include/alp/protocol/amp_beacon.h.  CM33-NS address = A55 address +
 * ALP_AMP_A55_TO_CM33_NS_OFFSET.
 */

#ifndef ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H
#define ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H

{defs}

#endif /* ALP_BACKENDS_RPC_ALP_AMP_WINDOW_H */
"""


def main(argv: list[str]) -> int:
    text = render(load_carveout())
    out = REPO / OUT
    if "--check" in argv:
        if not out.is_file() or out.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
            print(f"{OUT}: stale -- run python3 scripts/gen_amp_window.py", file=sys.stderr)
            return 1
        return 0
    out.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
