/* src/render/r3d_rig.h -- the runner's skeleton (P3b): bind-pose meshes
 * (per character since P16: body, head, limbs, every vertex rigidly bound
 * to one bone) posed per frame from animation channels and skinned on the CPU.
 * Bones, run-cycle harmonics and key poses are generated by
 * tools/genmesh.py rig() into meshes.h; r3d_scene.c drives the channels.
 * Pure C, IEEE basic ops + tr_sincosf only: host == A32 bits. */
#ifndef TR_R3D_RIG_H
#define TR_R3D_RIG_H

#include "r3d.h"

/* Animation channels (meshes.h has the same values): degrees, except
 * TR_ANIM_ROOT_Y (world units). Per side: TR_ANIM_SIDE0 + TR_ANIM_SIDE_N *
 * side (0 left, 1 right) + TR_ANIM_S_*. */
#define TR_ANIM_CH      25
#define TR_ANIM_ROOT_Y  0
#define TR_ANIM_P_PITCH 1
#define TR_ANIM_P_YAW   2
#define TR_ANIM_P_ROLL  3
#define TR_ANIM_SIDE0   9
#define TR_ANIM_SIDE_N  8

/* Mesh parts per character (meshes.h: body, head, arms, legs, gear) and
 * levels of detail (0 high: drawn; 1 low: the TR_LOD_NEAR bench bit). */
#define TR_RIG_PARTS 5
#define TR_RIG_LODS  2

/* Skinned vertex budget per mesh (uint8 indices). */
#define TR_RIG_MAX_V 256

/* The run cycle's channels at `cycle` (fractions of a stride; the left
 * foot touches down at whole numbers), feet locked by tr_rig_foot_lock()
 * at weight `lock`: 1 = the run cycle as drawn, 0 = its harmonics alone
 * (the scene blends poses over them, then locks). */
void tr_rig_run(float cycle, float ch[TR_ANIM_CH], float lock);

/* Foot lock (P3d): a foot on the board stays on the world point it touched
 * down on. Over its stance (TR_ANIM_STANCE of the cycle from touch-down)
 * the ball of the shoe is pinned at x = +-TR_ANIM_FOOT_X, y = 0 (the
 * board), z = TR_ANIM_TD_Z - TR_ANIM_GROUND_V x TR_ANIM_CYCLE x the phase
 * since touch-down -- exactly the board's own travel, whatever the pace,
 * since the cycle runs on game time -- and the leg's splay / thigh / knee /
 * foot channels are solved to it (2-bone IK, knee forward, the shoe rolling
 * TR_ANIM_PITCH_TD -> _TO toe-down). The lock eases in / out over
 * TR_ANIM_LOCK_BLEND of the cycle outside the stance. `w` (0..1) scales it:
 * the scene fades it out under the jump / duck / crash poses. Needs the
 * root and pelvis channels of `ch` already final. */
void tr_rig_foot_lock(float cycle, float ch[TR_ANIM_CH], float w);

/* One key pose (meshes.h TR_ANIM_POSE_*). */
const float *tr_rig_pose(int which);

/* Characters (P16): meshes.h tr_rig_chars[TR_CHARS], selected by the frame
 * packet (tr_mbox.h TR_CHAR_*); all share the legs and the run cycle, each
 * has its own upper-body bones, meshes and palette. A character id out of
 * range is Probe (0). */
#define TR_RIG_FACE  TR_RIG_PARTS           /* tr_rig_skin()'s extra part: the eyes */
#define TR_RIG_DRAWN (TR_RIG_PARTS + 1)     /* body, head, arms, legs, gear, eyes */
#define TR_FACE_COLS 5                      /* columns across an eye: a rounded lens */
#define TR_FACE_V    (2 * 2 * TR_FACE_COLS) /* two eyes x columns x (bottom, top) */
#define TR_FACE_T    (2 * 2 * (TR_FACE_COLS - 1))
int tr_rig_char_id(int chr);

/* Character `chr`'s table entry (meshes.h tr_rig_char_t; out of range:
 * Probe). The one place the tables are referenced from: every TU that
 * named them directly would link its own copy of every mesh. */
struct tr_rig_char;
const struct tr_rig_char *tr_rig_char(int chr);

/* The eyes' expression, all 0..1 but look_* (units on the visor): open 1 =
 * open, 0 = shut (a blink); squint narrows them to a determined slit
 * (inner corners down); wide widens them (a crash); happy bends them into
 * ^ ^ arcs. r3d_rig.c shapes TR_FACE_V vertices on the visor from it. */
typedef struct {
	float open, squint, wide, happy;
	float look_x, look_y;
} tr_face_t;

/*
 * Poses character `chr`'s bind meshes by `ch` and writes every part's
 * skinned vertices (xyz, float) and normals (int8, 127 == 1.0) into caller
 * buffers of TR_RIG_MAX_V entries: parts 0..TR_RIG_PARTS-1 are the
 * character's meshes at level of detail `lod` (body, head, arms, legs,
 * gear), part TR_RIG_FACE the eyes shaped
 * by `face` (NULL: open, neutral) and carried by the head bone. out[p] are
 * the meshes with vf / vn pointed at the buffers, ready for
 * tr_r3d_emit_mesh(). Their face normals `n` stay the BIND pose's: stale
 * once posed. The Gouraud z-band path shades from vn only; a flat or
 * painter (tr_r3d_draw) path would light the runner wrong.
 */
void tr_rig_skin(int              chr,
                 int              lod,
                 const float      ch[TR_ANIM_CH],
                 const tr_face_t *face,
                 float            xyz[TR_RIG_DRAWN][TR_RIG_MAX_V * 3],
                 int8_t           vn[TR_RIG_DRAWN][TR_RIG_MAX_V * 3],
                 tr_mesh_t        out[TR_RIG_DRAWN]);

/* World position of bone `b`'s joint posed by `ch`, carried by its PARENT
 * bone (the root: by itself) -- where the child must stay attached. */
void tr_rig_joint(int chr, const float ch[TR_ANIM_CH], int b, float out[3]);

/* Bind-pose points p[0..n) (world units) carried by bone `b` of character
 * `chr`, posed by `ch`: the scarf's anchor and collider (r3d_scene.c). */
void tr_rig_points(int         chr,
                   const float ch[TR_ANIM_CH],
                   int         b,
                   int         n,
                   const float (*p)[3],
                   float (*out)[3]);

/* Bone index per vertex of part `part` at `lod` (TR_RIG_FACE the eyes:
 * all TR_RIG_HEAD), for tests. */
const uint8_t *tr_rig_bones(int chr, int lod, int part);

#endif /* TR_R3D_RIG_H */
