/*
 * Copyright (c) 2026 Alp Lab AB
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * vendor-ext / build-bridge.  Custom fixed MPU region table for the Alif
 * Ensemble E8 (AE822FA0E5597), REPLACING (not appending to) the generic
 * 2-region table Zephyr falls back to (arm_mpu_regions.c: FLASH_0/SRAM_0).
 *
 * ROOT CAUSE this replaces (alp-advisor 2026-07-28, superseding the
 * zephyr,memory-region-node approach from commit 4ad5e941): PMSAv8-M (the
 * E8's MPU architecture; CONFIG_MPU_REQUIRES_NON_OVERLAPPING_REGIONS=y in
 * this build) treats an address matching MULTIPLE enabled regions as an
 * ACCESS VIOLATION -- ARMv7-M's "higher index wins" resolution rule does not
 * apply here. mpu_configure_regions_from_dt() (arch/arm/core/mpu/arm_mpu.c:
 * 110-183, invoked :562-568) APPENDS `zephyr,memory-region` DT nodes AFTER
 * the static table; it does not split overlaps (that logic,
 * arch/arm/core/mpu/arm_mpu_v8_internal.h:532-658, runs only for the
 * app/kernel static-partition path). So two DT-appended MRAM regions
 * stacked on top of a generic FLASH_0 that ALSO covers all of MRAM
 * (CONFIG_XIP + `zephyr,flash` resolving to `mram_storage`) triple-matched
 * every MRAM address, including the first slot0 instruction fetch -- a
 * self-bricking image on Flow D (production MRAM boot).
 *
 * THE FIX: stop having a generic whole-flash "FLASH_0" region exist AT ALL
 * when the flash target is MRAM. This table REPLACES arm_mpu_regions.c
 * (via `select CPU_HAS_CUSTOM_FIXED_SOC_MPU_REGIONS` in the board's
 * hand-maintained `Kconfig`, see the placement note below) and, instead of
 * one "whole flash" region, always defines the two disjoint MRAM windows
 * (MRAM_EXEC / MRAM_DEVICE) plus the two other CPU-local memories (ITCM /
 * DTCM) as FOUR static regions, plus a FIFTH conditional region
 * (MRAM_RESERVED, see below) that appears only when this board's own
 * boot/slot0/storage partitions leave a span of mram_storage that neither
 * MRAM_EXEC nor MRAM_DEVICE covers. This is flow-aware WITHOUT any
 * `#if`-on-flow branching, because ITCM ([0x0, 0x40000)) and MRAM
 * ([0x80000000, 0x80580000)) are disjoint address ranges by construction:
 *
 *   - Flow C (bench ITCM RAM-run, `zephyr,flash = &itcm`,
 *     CONFIG_FLASH_BASE_ADDRESS=0x0): the ITCM region below already covers
 *     the running code as flash-attr+executable. MRAM_EXEC/MRAM_DEVICE are
 *     also present (SoC-fixed, not flow-conditional) but sit at
 *     0x80000000+ -- no overlap with ITCM's 0x0-0x40000.
 *   - Flow D (production MRAM boot via MCUboot slot0,
 *     CONFIG_FLASH_BASE_ADDRESS=0x80000000): MRAM_EXEC *is* the flash
 *     region (REGION_FLASH_ATTR, matching what a generic FLASH_0 would have
 *     been) -- there is no SEPARATE FLASH_0 to duplicate it, so nothing
 *     collides with MRAM_DEVICE either.
 *
 * The BUILD_ASSERT at the bottom makes that flow-awareness a checked
 * invariant instead of an implicit assumption: whichever memory
 * `zephyr,flash` currently designates (CONFIG_FLASH_BASE_ADDRESS) must
 * already be covered by ITCM or MRAM_EXEC below, or the build fails loudly
 * instead of silently producing an unprotected/uncovered image.
 *
 * MRAM_EXEC / MRAM_DEVICE boundaries mirror the Apache-2.0 zephyr_alif
 * fork's soc/alif/ensemble/common/mpu_regions.c:27-92 (FLASH_MRAM_*
 * / DEVICE_MRAM_* under the same CONFIG_MCUBOOT / CONFIG_BOOTLOADER_MCUBOOT
 * / else three-way split, computed from the boot/slot0/slot1/scratch/storage
 * DT_NODELABELs on `mram_storage`) -- same math, renamed to match the
 * region names commit 4ad5e941 already introduced (MRAM_EXEC/MRAM_DEVICE)
 * so nothing downstream (docs, the mram-flash-validate prj.conf comment)
 * needs to change. ITCM / DTCM mirror the fork's Region 2/3
 * (mpu_regions.c:94-100), reading their reg/size from
 * DT_NODELABEL(itcm)/DT_NODELABEL(dtcm) so the same file is correct on BOTH
 * the M55-HE (DTCM 256 KiB) and M55-HP (DTCM 1024 KiB) cores without a
 * per-core variant -- reg values are upstream Zephyr's own
 * dts/arm/alif/ensemble/common/ensemble_rtss_{he,hp}.dtsi:30-38 (itcm@0,
 * 256 KiB both cores; dtcm@0x20000000, 256 KiB HE / 1024 KiB HP), so no
 * value here is invented.
 *
 * PLACEMENT (the load-bearing part, per the 4ad5e941 postmortem): this file
 * is compiled from the hand-maintained top-level `zephyr/CMakeLists.txt`
 * (module entry point, NOT a generated file -- see its existing
 * CONFIG_SOC_SERIES_E8-gated precedents: the GPIO clock-enable glue and the
 * OSPI_XIP_SER compile-definition, both applied "before the CONFIG_ALP_SDK
 * early-return... needed for any Ensemble-E8 build, not just alp-feature
 * builds"), gated on CONFIG_CPU_HAS_CUSTOM_FIXED_SOC_MPU_REGIONS (itself
 * `select`ed from a NEW hand-maintained per-board `Kconfig` file --
 * `zephyr/boards/alp/e1m_aen801_m55_{he,hp}/Kconfig` -- picked because
 * `Kconfig.alp_<board>` and `Kconfig.defconfig` in both board dirs ARE
 * generated by scripts/alp_project.py --emit zephyr-board (`DO NOT EDIT BY
 * HAND -- regenerate`), but a bare `Kconfig` is not one of the files that
 * generator emits, and Zephyr's own hwm_v2.cmake unconditionally osources
 * `<board_dir>/Kconfig` (kconfig_gen("boards" "Kconfig" ...) ->
 * `source "boards/Kconfig"` in Kconfig.zephyr) whether or not the file
 * exists -- exactly the same kind of always-sourced, never-generated hook
 * `board.cmake` already is for flash/debug runners in both of these board
 * dirs.  This ONE shared .c file + ONE CMake gate covers BOTH boards
 * automatically (CONFIG_SOC_SERIES_E8 is true for both, and the two new
 * per-board `Kconfig` files each select the shared symbol), so it survives
 * `alp_project.py --emit zephyr-board` regeneration of the .dts/_defconfig/
 * Kconfig.alp_<board>/Kconfig.defconfig files untouched.
 */

#include <zephyr/arch/arm/mpu/arm_mpu.h>
#include <zephyr/devicetree.h>
#include <zephyr/toolchain.h>

#define MRAM_SECTOR_SIZE DT_PROP(DT_NODELABEL(mram_storage), erase_block_size)

#define MRAM_BOOT_PARTITION_ADDR    DT_FIXED_PARTITION_ADDR(DT_NODELABEL(boot_partition))
#define MRAM_BOOT_PARTITION_SIZE    DT_REG_SIZE(DT_NODELABEL(boot_partition))
#define MRAM_SLOT0_PARTITION_ADDR   DT_FIXED_PARTITION_ADDR(DT_NODELABEL(slot0_partition))
#define MRAM_SLOT0_PARTITION_SIZE   DT_REG_SIZE(DT_NODELABEL(slot0_partition))
#define MRAM_STORAGE_PARTITION_ADDR DT_FIXED_PARTITION_ADDR(DT_NODELABEL(storage_partition))
#define MRAM_STORAGE_PARTITION_SIZE DT_REG_SIZE(DT_NODELABEL(storage_partition))

#if defined(CONFIG_MCUBOOT)
/* MCUboot bootloader build: MCUboot executes from the boot partition only.
 * Writable: slot0, slot1, scratch, storage (fork mpu_regions.c:40-50). */
#define MRAM_EXEC_BASE_ADDR   MRAM_BOOT_PARTITION_ADDR
#define MRAM_EXEC_SIZE        MRAM_BOOT_PARTITION_SIZE
#define MRAM_DEVICE_BASE_ADDR MRAM_SLOT0_PARTITION_ADDR
#define MRAM_DEVICE_SIZE \
	(MRAM_STORAGE_PARTITION_ADDR + MRAM_STORAGE_PARTITION_SIZE - MRAM_SLOT0_PARTITION_ADDR)
#elif defined(CONFIG_BOOTLOADER_MCUBOOT)
/* MCUboot-chainloaded app build (Flow C and Flow D both build this app;
 * they differ only in WHERE it links/runs, not in this Kconfig combo):
 * boot + slot0 (minus the last, trailer, sector) are executable; the
 * trailer sector + slot1 + scratch + storage are the writable device
 * window (fork mpu_regions.c:51-68). */
#define MRAM_EXEC_BASE_ADDR MRAM_BOOT_PARTITION_ADDR
#define MRAM_EXEC_SIZE \
	(MRAM_SLOT0_PARTITION_ADDR + MRAM_SLOT0_PARTITION_SIZE - MRAM_BOOT_PARTITION_ADDR - \
	 MRAM_SECTOR_SIZE)
#define MRAM_DEVICE_BASE_ADDR \
	(MRAM_SLOT0_PARTITION_ADDR + MRAM_SLOT0_PARTITION_SIZE - MRAM_SECTOR_SIZE)
#define MRAM_DEVICE_SIZE \
	(MRAM_STORAGE_PARTITION_ADDR + MRAM_STORAGE_PARTITION_SIZE - MRAM_DEVICE_BASE_ADDR)
#else
/* Non-MCUboot app build: the whole non-storage MRAM span is executable;
 * only `storage` needs device/write access (fork mpu_regions.c:69-79). */
#define MRAM_EXEC_BASE_ADDR   MRAM_BOOT_PARTITION_ADDR
#define MRAM_EXEC_SIZE        (MRAM_STORAGE_PARTITION_ADDR - MRAM_BOOT_PARTITION_ADDR)
#define MRAM_DEVICE_BASE_ADDR MRAM_STORAGE_PARTITION_ADDR
#define MRAM_DEVICE_SIZE      MRAM_STORAGE_PARTITION_SIZE
#endif

/* All three branches above converge on the same "top of coverage" address:
 * MRAM_DEVICE_BASE_ADDR + MRAM_DEVICE_SIZE == MRAM_STORAGE_PARTITION_ADDR +
 * MRAM_STORAGE_PARTITION_SIZE. The fork's own model (and the three branches
 * above, mirroring it) assumes `storage_partition` is the LAST partition in
 * `mram_storage`, so that sum lands exactly on top-of-flash and MRAM_EXEC +
 * MRAM_DEVICE tile the whole part. Where that assumption holds (every board
 * default: e.g. this board's own alp_e1m_aen801_m55_{he,hp}*.dts has
 * storage_partition@0x560000 sized to run to 0x580000), MRAM_RESERVED_SIZE
 * below is 0 and the extra region compiles out. Where a board overlay places
 * `storage_partition` somewhere in the MIDDLE of mram_storage instead (see
 * examples/connectivity/firmware-update-log's log_mram.dtsi: ulog/storage at
 * 0x90000, with the Alif SE ATOC package fixed at 0x560000 above it),
 * MRAM_EXEC/MRAM_DEVICE alone leave that upper span -- ATOC included --
 * covered by no region at all, which falls through to the ARMv8-M default
 * map (PRIVDEFENA, arch/arm/core/mpu/arm_mpu.c): Normal memory, privileged
 * RW *and* executable. For an example whose subject is application
 * immutability that is a silent write hole over the ATOC package, so this
 * table closes it generically instead of leaving it to each overlay. */
#define MRAM_RESERVED_BASE_ADDR (MRAM_DEVICE_BASE_ADDR + MRAM_DEVICE_SIZE)
#define MRAM_RESERVED_SIZE \
	(DT_REG_ADDR(DT_NODELABEL(mram_storage)) + DT_REG_SIZE(DT_NODELABEL(mram_storage)) - \
	 MRAM_RESERVED_BASE_ADDR)

/* RO *and* non-executable, which no stock `(base, size)` attr macro gives:
 * REGION_FLASH_ATTR is RO under CONFIG_MPU_ALLOW_FLASH_WRITE=n but omits
 * NOT_EXEC (arm_mpu_v8.h:325-331 -- `.rbar = RO_Msk | NON_SHAREABLE_Msk`),
 * because for MRAM_EXEC/ITCM being executable is the whole point. Reusing it
 * here would close the write hole and leave an execute hole: the ATOC package
 * and any stale image bytes in this span would stay fetchable as code. There
 * is a NOT_EXEC + RO pairing in the `(limit)`-form family
 * (REGION_RAM_RO_ATTR, arm_mpu_v8.h:193-198) but not in the `(base, size)`
 * form this table uses, so spell it out rather than reshape the table. MAIR
 * stays MPU_MAIR_INDEX_FLASH: this span IS MRAM, and the index drives
 * cache-ability, not permissions. */
#define REGION_MRAM_RESERVED_ATTR(base, size)                                  \
	{                                                                      \
		.rbar = NOT_EXEC | RO_Msk | NON_SHAREABLE_Msk, /* AP, XN, SH */ \
		.mair_idx = MPU_MAIR_INDEX_FLASH,             /* Cache-ability */ \
		.r_limit = REGION_LIMIT_ADDR(base, size),     /* Region Limit */  \
	}

static const struct arm_mpu_region mpu_regions[] = {
	/* Region 0: executable MRAM (boot + slot0, minus the MCUboot trailer
	 * sector under CONFIG_BOOTLOADER_MCUBOOT). RO even for privileged
	 * code unless CONFIG_MPU_ALLOW_FLASH_WRITE=y widens it to P_RW_U_RW
	 * (arm_mpu_v8.h:316-322) -- that symbol must stay UNSET for this
	 * region to stay non-writable; see the board Kconfig note. */
	MPU_REGION_ENTRY("MRAM_EXEC",
	                 MRAM_EXEC_BASE_ADDR,
	                 REGION_FLASH_ATTR(MRAM_EXEC_BASE_ADDR, MRAM_EXEC_SIZE)),
	/* Region 1: writable MRAM (device-mapped for write access), privileged
	 * only (REGION_DEVICE_ATTR is P_RW_U_NA -- arm_mpu_v8.h:335-340). This
	 * is what flash_mram_alif's direct memory-mapped stores need. */
	MPU_REGION_ENTRY("MRAM_DEVICE",
	                 MRAM_DEVICE_BASE_ADDR,
	                 REGION_DEVICE_ATTR(MRAM_DEVICE_BASE_ADDR, MRAM_DEVICE_SIZE)),
	/* Region 2: ITCM -- executable, flash-attr (fork mpu_regions.c:94-96).
	 * This IS "the flash region" for Flow C (see BUILD_ASSERT below). */
	MPU_REGION_ENTRY(
	    "ITCM",
	    DT_REG_ADDR(DT_NODELABEL(itcm)),
	    REGION_FLASH_ATTR(DT_REG_ADDR(DT_NODELABEL(itcm)), DT_REG_SIZE(DT_NODELABEL(itcm)))),
	/* Region 3: DTCM -- the core's data RAM (== `zephyr,sram` on this
	 * board; fork mpu_regions.c:97-100). Size is per-core (256 KiB HE /
	 * 1024 KiB HP), read from DT, not hardcoded. */
	MPU_REGION_ENTRY(
	    "DTCM",
	    DT_REG_ADDR(DT_NODELABEL(dtcm)),
	    REGION_RAM_ATTR(DT_REG_ADDR(DT_NODELABEL(dtcm)), DT_REG_SIZE(DT_NODELABEL(dtcm)))),
#if MRAM_RESERVED_SIZE > 0
	/* Region 4 (conditional): the part of mram_storage above MRAM_DEVICE
	 * that boot/slot0/storage don't already reach -- see the comment on
	 * MRAM_RESERVED_SIZE above. RO *and* XN: nothing here is meant to be
	 * written OR executed by this image, the ATOC package included. Note
	 * this is deliberately NOT REGION_FLASH_ATTR, which would leave the
	 * span executable -- see REGION_MRAM_RESERVED_ATTR above. */
	MPU_REGION_ENTRY("MRAM_RESERVED",
	                 MRAM_RESERVED_BASE_ADDR,
	                 REGION_MRAM_RESERVED_ATTR(MRAM_RESERVED_BASE_ADDR, MRAM_RESERVED_SIZE)),
#endif
};

const struct arm_mpu_config mpu_config = {
	.num_regions = ARRAY_SIZE(mpu_regions),
	.mpu_regions = mpu_regions,
};

/* Flow-awareness, checked: whichever memory `zephyr,flash` currently
 * designates must already be covered by ITCM (Flow C) or MRAM_EXEC (Flow
 * D/A) above. If a future flow points `zephyr,flash` somewhere else, this
 * fails the build instead of silently shipping an unprotected/uncovered
 * image -- see the file header's "THE FIX" section for why no separate,
 * generic CONFIG_FLASH_BASE_ADDRESS-sized region is added here. */
BUILD_ASSERT(CONFIG_FLASH_BASE_ADDRESS == DT_REG_ADDR(DT_NODELABEL(itcm)) ||
                 CONFIG_FLASH_BASE_ADDRESS == MRAM_EXEC_BASE_ADDR,
             "zephyr,flash targets a memory region this board's custom MPU table "
             "(mpu_regions_e8.c) does not cover -- add it before shipping");
