/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright 2026 Alp Lab AB
 *
 * Auto-generated by scripts/gen_cc3501e_gpio_routes.py from
 * metadata/e1m_modules/aen/hw-revisions.yaml `pad_route_overrides:`.
 * DO NOT EDIT BY HAND -- regenerate:
 *   python3 scripts/gen_cc3501e_gpio_routes.py
 *
 * The E1M pads whose target chip (CC3501E vs the Alif SoC) moves
 * between AEN hw_revs -- IO8/IO10/IO21 today.  ONE copy for every AEN
 * board regardless of hw_rev or carrier (this list names WHICH pads
 * move, not where any one board's route table put them) -- compiled
 * whenever src/backends/gpio/cc3501e_proxy.c itself is
 * (zephyr/CMakeLists.txt), never a per-board override.  Replaced the
 * per-app copy of this same list (originally issue #2144) that
 * triplicated across every board's cc3501e_gpio_routes.c -- the exact
 * pattern issue #1859 already removed once for cc3501e_gpio_routes[]
 * itself.
 *
 * src/backends/gpio/cc3501e_proxy.c's px_open() refuses
 * alp_gpio_open() on a listed pin_id with ALP_ERR_NOSUPPORT unless a
 * CRC-valid identity-EEPROM manifest confirms the running module's
 * hw_rev equals CONFIG_ALP_SDK_SOM_HW_REV -- the hw_rev the CALLING
 * board's OWN cc3501e_gpio_routes[] was built for -- failing CLOSED on
 * a missing/unreadable/mismatched manifest.
 */

#include <stdint.h>
#include <stddef.h>

#include <alp/e1m_pinout.h>

const uint32_t cc3501e_gpio_rev_dependent[] = {
	ALP_E1M_GPIO_IO8,
	ALP_E1M_GPIO_IO10,
	ALP_E1M_GPIO_IO21,
};

const size_t cc3501e_gpio_rev_dependent_count =
    sizeof(cc3501e_gpio_rev_dependent) / sizeof(cc3501e_gpio_rev_dependent[0]);
