/*
 * Copyright 2026 Alp Lab AB
 * SPDX-License-Identifier: Apache-2.0
 *
 * Auto-generated by scripts/gen_power_tree.py from metadata/e1m_modules/v2n/power-tree.yaml.
 * DO NOT EDIT BY HAND -- regenerate:
 *   python3 scripts/gen_power_tree.py
 */

/**
 * @file v2n_power_tree.h
 * @brief Generated runtime guard tables for the V2N-family on-module
 *        PMIC / regulator drivers (ACT88760, DA9292, TPS628640).
 *
 * Brace initialisers only (no storage): instantiate in static storage and
 * install with act8760_set_limits() / da9292_set_limits() /
 * tps628640_set_limits().  See <alp/chips/pmic_rail_limit.h> for the guard
 * semantics and the source YAML for nets, targets and provenance.
 */

#ifndef ALP_CHIPS_V2N_POWER_TREE_H
#define ALP_CHIPS_V2N_POWER_TREE_H

#include "alp/chips/pmic_rail_limit.h"
#include "alp/chips/act8760.h"
#include "alp/chips/da9292.h"
#include "alp/chips/tps628640.h"

/** Expected DA9292 PMC_DEV_ID (0x19). */
#define V2N_POWER_DA9292_DEV_ID 0xEAu
/** Expected DA9292 PMC_REV_ID (0x1A). */
#define V2N_POWER_DA9292_REV_ID 0x42u
/** Expected DA9292 PMC_CFG_REV (0x1B). */
#define V2N_POWER_DA9292_CFG_REV 0x11u

/** ACT88760 GPIOs whose MODEx polarity bit may be written: bit (n-1) = GPIOn. */
#define V2N_POWER_ACT8760_GPIO_POLARITY_WRITABLE_MASK 0x0008u

/** Expected ACT88760 MODE4 byte (GD32_NRST). */
#define V2N_POWER_ACT8760_GPIO4_EXPECTED_MODE 0x08u

/** ACT88760 GPIO net names, index = GPIO number - 1. */
#define V2N_POWER_ACT8760_GPIO_NETS_INIT \
	{ \
		"PMIC_RSTOUT", "PMIC_nINT",        "DDR4_VDDQ_EN", "GD32_NRST", "V2N_BOOT_CPU_SEL", \
		"MODULE_EN",   "DEEPX_PWR_EN_REQ", "SD1_EN",       "PWEN1",     "PWEN2", \
		"MODULE_STBY", \
	}

/** v2n: ACT88760 limits, indexed by act8760_rail_t. */
#define V2N_POWER_ACT8760_RAIL_LIMITS_INIT \
	{ \
		[ACT8760_RAIL_BUCK1] = { .min_mv           = 3150u, \
		                         .max_mv           = 3450u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK2] = { .min_mv           = 1725u, \
		                         .max_mv           = 1875u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK3] = { .min_mv           = 1050u, \
		                         .max_mv           = 1150u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK4] = { .min_mv           = 1725u, \
		                         .max_mv           = 1875u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK5] = { .min_mv           = 725u, \
		                         .max_mv           = 775u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK6] = { .min_mv           = 775u, \
		                         .max_mv           = 825u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK7] = { .min_mv           = 855u, \
		                         .max_mv           = 945u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO1]  = { .min_mv           = 763u, \
		                         .max_mv           = 837u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO2]  = { .min_mv           = 1150u, \
		                         .max_mv           = 1250u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO3]  = { .min_mv           = 3150u, \
		                         .max_mv           = 3450u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO4]  = { .min_mv           = 1750u, \
		                         .max_mv           = 1850u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO5]  = { .min_mv           = 0u, \
		                         .max_mv           = 0u, \
		                         .critical         = true, \
		                         .voltage_writable = false, \
		                         .enable_writable  = true }, \
		[ACT8760_RAIL_LDO6]  = { .min_mv           = 0u, \
		                         .max_mv           = 0u, \
		                         .critical         = true, \
		                         .voltage_writable = false, \
		                         .enable_writable  = true }, \
	}

/** v2n: ACT88760 rail net names, indexed by act8760_rail_t. */
#define V2N_POWER_ACT8760_RAIL_NETS_INIT \
	{ \
		[ACT8760_RAIL_BUCK1] = "VDD_3V3",    [ACT8760_RAIL_BUCK2] = "VDD1G_1P8", \
		[ACT8760_RAIL_BUCK3] = "LPD4x_1V1",  [ACT8760_RAIL_BUCK4] = "LPDDR_1V8", \
		[ACT8760_RAIL_BUCK5] = "TBD",        [ACT8760_RAIL_BUCK6] = "TBD", \
		[ACT8760_RAIL_BUCK7] = "VDD09_CA55", [ACT8760_RAIL_LDO1] = "VDD1G_0P8", \
		[ACT8760_RAIL_LDO2] = "LDO_1V2",     [ACT8760_RAIL_LDO3] = "VDD_eMMC_3V3", \
		[ACT8760_RAIL_LDO4] = "VDD_1V8",     [ACT8760_RAIL_LDO5] = "VDD5G_1P8", \
		[ACT8760_RAIL_LDO6] = "VDD6G_1P2", \
	}

/** v2n: DA9292 limits, indexed by da9292_channel_t. */
#define V2N_POWER_DA9292_CH_LIMITS_INIT \
	{ \
		[DA9292_CH1] = { .min_mv           = 0u, \
		                 .max_mv           = 0u, \
		                 .critical         = true, \
		                 .voltage_writable = false, \
		                 .enable_writable  = false }, \
		[DA9292_CH2] = { .min_mv           = 0u, \
		                 .max_mv           = 0u, \
		                 .critical         = false, \
		                 .voltage_writable = false, \
		                 .enable_writable  = false }, \
	}

/** v2n: DA9292 channel net names, indexed by da9292_channel_t. */
#define V2N_POWER_DA9292_CH_NETS_INIT \
	{ \
		[DA9292_CH1] = "TBD", \
		[DA9292_CH2] = "", \
	}

/** v2n: TPS628640 `LPD4x_0V6` 7-bit address (assembled: optional). */
#define V2N_POWER_TPS628640_LPD4X_0V6_ADDR 0x4Du
/** v2n: TPS628640 `LPD4x_0V6` limit entry. */
#define V2N_POWER_TPS628640_LPD4X_0V6_LIMIT_INIT \
	{ .min_mv           = 570u, \
	  .max_mv           = 630u, \
	  .critical         = true, \
	  .voltage_writable = true, \
	  .enable_writable  = true }
/** v2n: TPS628640 `LPD4x_0V6` net name. */
#define V2N_POWER_TPS628640_LPD4X_0V6_NET "LPD4x_0V6"

/** v2n-m1: ACT88760 limits, indexed by act8760_rail_t. */
#define V2N_M1_POWER_ACT8760_RAIL_LIMITS_INIT \
	{ \
		[ACT8760_RAIL_BUCK1] = { .min_mv           = 3150u, \
		                         .max_mv           = 3450u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK2] = { .min_mv           = 1725u, \
		                         .max_mv           = 1875u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK3] = { .min_mv           = 1050u, \
		                         .max_mv           = 1150u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK4] = { .min_mv           = 1725u, \
		                         .max_mv           = 1875u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK5] = { .min_mv           = 725u, \
		                         .max_mv           = 775u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK6] = { .min_mv           = 775u, \
		                         .max_mv           = 825u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_BUCK7] = { .min_mv           = 855u, \
		                         .max_mv           = 945u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO1]  = { .min_mv           = 763u, \
		                         .max_mv           = 837u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO2]  = { .min_mv           = 1150u, \
		                         .max_mv           = 1250u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO3]  = { .min_mv           = 3150u, \
		                         .max_mv           = 3450u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO4]  = { .min_mv           = 1750u, \
		                         .max_mv           = 1850u, \
		                         .critical         = true, \
		                         .voltage_writable = true, \
		                         .enable_writable  = false }, \
		[ACT8760_RAIL_LDO5]  = { .min_mv           = 0u, \
		                         .max_mv           = 0u, \
		                         .critical         = true, \
		                         .voltage_writable = false, \
		                         .enable_writable  = true }, \
		[ACT8760_RAIL_LDO6]  = { .min_mv           = 0u, \
		                         .max_mv           = 0u, \
		                         .critical         = true, \
		                         .voltage_writable = false, \
		                         .enable_writable  = true }, \
	}

/** v2n-m1: ACT88760 rail net names, indexed by act8760_rail_t. */
#define V2N_M1_POWER_ACT8760_RAIL_NETS_INIT \
	{ \
		[ACT8760_RAIL_BUCK1] = "VDD_3V3",    [ACT8760_RAIL_BUCK2] = "VDD1G_1P8", \
		[ACT8760_RAIL_BUCK3] = "LPD4x_1V1",  [ACT8760_RAIL_BUCK4] = "LPDDR_1V8", \
		[ACT8760_RAIL_BUCK5] = "TBD",        [ACT8760_RAIL_BUCK6] = "TBD", \
		[ACT8760_RAIL_BUCK7] = "VDD09_CA55", [ACT8760_RAIL_LDO1] = "VDD1G_0P8", \
		[ACT8760_RAIL_LDO2] = "LDO_1V2",     [ACT8760_RAIL_LDO3] = "VDD_eMMC_3V3", \
		[ACT8760_RAIL_LDO4] = "VDD_1V8",     [ACT8760_RAIL_LDO5] = "VDD5G_1P8", \
		[ACT8760_RAIL_LDO6] = "VDD6G_1P2", \
	}

/** v2n-m1: DA9292 limits, indexed by da9292_channel_t. */
#define V2N_M1_POWER_DA9292_CH_LIMITS_INIT \
	{ \
		[DA9292_CH1] = { .min_mv           = 0u, \
		                 .max_mv           = 0u, \
		                 .critical         = true, \
		                 .voltage_writable = false, \
		                 .enable_writable  = false }, \
		[DA9292_CH2] = { .min_mv           = 715u, \
		                 .max_mv           = 785u, \
		                 .critical         = false, \
		                 .voltage_writable = true, \
		                 .enable_writable  = true }, \
	}

/** v2n-m1: DA9292 channel net names, indexed by da9292_channel_t. */
#define V2N_M1_POWER_DA9292_CH_NETS_INIT \
	{ \
		[DA9292_CH1] = "TBD", \
		[DA9292_CH2] = "VDD_0P75", \
	}

/** v2n-m1: TPS628640 `DDR5_VDD2H_1V05` 7-bit address. */
#define V2N_M1_POWER_TPS628640_DDR5_VDD2H_1V05_ADDR 0x44u
/** v2n-m1: TPS628640 `DDR5_VDD2H_1V05` limit entry. */
#define V2N_M1_POWER_TPS628640_DDR5_VDD2H_1V05_LIMIT_INIT \
	{ .min_mv           = 1000u, \
	  .max_mv           = 1100u, \
	  .critical         = false, \
	  .voltage_writable = true, \
	  .enable_writable  = true }
/** v2n-m1: TPS628640 `DDR5_VDD2H_1V05` net name. */
#define V2N_M1_POWER_TPS628640_DDR5_VDD2H_1V05_NET "DDR5_VDD2H_1V05"

/** v2n-m1: TPS628640 `VDD0V85_LPDDR` 7-bit address. */
#define V2N_M1_POWER_TPS628640_VDD0V85_LPDDR_ADDR 0x48u
/** v2n-m1: TPS628640 `VDD0V85_LPDDR` limit entry. */
#define V2N_M1_POWER_TPS628640_VDD0V85_LPDDR_LIMIT_INIT \
	{ .min_mv           = 810u, \
	  .max_mv           = 890u, \
	  .critical         = false, \
	  .voltage_writable = true, \
	  .enable_writable  = true }
/** v2n-m1: TPS628640 `VDD0V85_LPDDR` net name. */
#define V2N_M1_POWER_TPS628640_VDD0V85_LPDDR_NET "VDD0V85_LPDDR"

/** v2n-m1: TPS628640 `LPD4x_0V6` 7-bit address (assembled: optional). */
#define V2N_M1_POWER_TPS628640_LPD4X_0V6_ADDR 0x4Du
/** v2n-m1: TPS628640 `LPD4x_0V6` limit entry. */
#define V2N_M1_POWER_TPS628640_LPD4X_0V6_LIMIT_INIT \
	{ .min_mv           = 570u, \
	  .max_mv           = 630u, \
	  .critical         = true, \
	  .voltage_writable = true, \
	  .enable_writable  = true }
/** v2n-m1: TPS628640 `LPD4x_0V6` net name. */
#define V2N_M1_POWER_TPS628640_LPD4X_0V6_NET "LPD4x_0V6"

/** v2n-m1: TPS628640 `DDR5_VDDQ_0V5` 7-bit address. */
#define V2N_M1_POWER_TPS628640_DDR5_VDDQ_0V5_ADDR 0x4Fu
/** v2n-m1: TPS628640 `DDR5_VDDQ_0V5` limit entry. */
#define V2N_M1_POWER_TPS628640_DDR5_VDDQ_0V5_LIMIT_INIT \
	{ .min_mv           = 475u, \
	  .max_mv           = 525u, \
	  .critical         = false, \
	  .voltage_writable = true, \
	  .enable_writable  = true }
/** v2n-m1: TPS628640 `DDR5_VDDQ_0V5` net name. */
#define V2N_M1_POWER_TPS628640_DDR5_VDDQ_0V5_NET "DDR5_VDDQ_0V5"

#endif /* ALP_CHIPS_V2N_POWER_TREE_H */
