#!/usr/bin/env python3
# Copyright 2026 ALP Lab AB
# SPDX-License-Identifier: Apache-2.0
"""
Regenerate gd32-bridge/tests/protocol_vectors.txt.

This script is the authoritative source-of-truth for the canonical
wire vectors consumed by:

  * the host-side driver tests under tests/zephyr/chips/gd32g553/
  * the firmware-side unit tests under gd32-bridge/tests/

It computes the CRC bytes natively (no external dependency) and
emits exactly the format the consumers expect: one `<name> = <hex>`
vector per line, comment lines start with `#`.

Run from the alp-sdk repo root:

    python3 gd32-bridge/tests/gen_protocol_vectors.py

The output file is fully regenerated -- diff against git to spot
unexpected wire changes.
"""

from __future__ import annotations

import argparse
import pathlib
import sys


def crc16_ccitt_false(data: bytes) -> int:
    """CRC-16/CCITT-FALSE (poly 0x1021, init 0xFFFF, non-reflected, xor-out 0)."""
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            if crc & 0x8000:
                crc = ((crc << 1) ^ 0x1021) & 0xFFFF
            else:
                crc = (crc << 1) & 0xFFFF
    return crc


def spi_frame(framing_byte: int, op_or_status: int, payload: bytes = b"") -> bytes:
    """Build a SPI envelope: `SOF | CMD-or-STATUS | PAYLOAD | CRC(MSB,LSB)`."""
    body = bytes([framing_byte, op_or_status]) + payload
    crc = crc16_ccitt_false(body)
    return body + crc.to_bytes(2, "big")


def i2c_write(cmd: int, payload: bytes = b"") -> bytes:
    """Build an I2C write envelope.

    Wire layout per docs/gd32-bridge-protocol.md §5: the host clocks
    `<reg-addr=0x00> CMD PAYLOAD CRC(2)` after the I2C
    `S | ADDR | W` envelope.  CRC covers `CMD | PAYLOAD` only.
    """
    body = bytes([cmd]) + payload
    crc = crc16_ccitt_false(body)
    return bytes([0x00]) + body + crc.to_bytes(2, "big")


def i2c_read(status: int, payload: bytes = b"") -> bytes:
    """Build an I2C read envelope: `STATUS PAYLOAD CRC(2)` (CRC over `STATUS | PAYLOAD`)."""
    body = bytes([status]) + payload
    crc = crc16_ccitt_false(body)
    return body + crc.to_bytes(2, "big")


# ---------------------------------------------------------------------
# Constants -- keep aligned with gd32-bridge/src/protocol.h.
# ---------------------------------------------------------------------

SOF = 0xA5
CMD_PING = 0x00
CMD_GET_VERSION = 0x01
STATUS_OK = 0x00

# Firmware-declared version triple; bump when protocol.h's
# PROTOCOL_VERSION_{MAJOR,MINOR,PATCH} change.
FW_VERSION = (0, 1, 0)


HEADER = """\
# gd32-bridge canonical wire-test vectors
#
# Both the host-side driver tests (tests/zephyr/chips/gd32g553/) and
# the firmware-side unit tests (gd32-bridge/tests/) consume this file
# so the two implementations cannot diverge.
#
# Format: one vector per non-comment line, `<name> = <hex>` where
# <hex> is a sequence of byte values with no separators.  Whitespace
# is ignored; lines beginning with `#` are comments.
#
# Vectors below are regenerated by `python3 tests/gen_protocol_vectors.py`
# any time the framing layer changes.  Re-run the generator and commit
# both this file and the corresponding driver / firmware updates in
# the same change.
"""


def build_vectors() -> list[tuple[str, str, str | None]]:
    """Return [(name, hex_value, comment_or_none)] in emission order."""
    out: list[tuple[str, str, str | None]] = []

    # ----- §1. Foundational CRC-16/CCITT-FALSE vector ----------------
    out.append((
        "crc16_ccitt_false_ref_string",
        b"123456789".hex().upper(),
        '"123456789" (ASCII) -- the canonical CRC-16/CCITT-FALSE test input',
    ))
    crc_ref = crc16_ccitt_false(b"123456789")
    out.append((
        "crc16_ccitt_false_ref_result",
        f"{crc_ref:04X}",
        "expected output: 0x29B1 (universally cited)",
    ))
    out.append((
        "crc16_ccitt_false_test_string",
        b"1234567890".hex().upper(),
        "helper: extra trailing '0' catches truncated walks",
    ))

    # ----- §2. SPI envelopes -----------------------------------------
    out.append((
        "spi_ping_request",
        spi_frame(SOF, CMD_PING).hex().upper(),
        "SOF | CMD=0x00 (PING) | CRC -- empty payload",
    ))
    out.append((
        "spi_ping_reply_ok",
        spi_frame(SOF, STATUS_OK).hex().upper(),
        "SOF | STATUS=0x00 (OK) | CRC -- empty payload",
    ))
    out.append((
        "spi_get_version_request",
        spi_frame(SOF, CMD_GET_VERSION).hex().upper(),
        "SOF | CMD=0x01 (GET_VERSION) | CRC -- empty payload",
    ))
    out.append((
        "spi_get_version_reply_v0_1_0",
        spi_frame(SOF, STATUS_OK, bytes(FW_VERSION)).hex().upper(),
        f"SOF | STATUS=0x00 | major={FW_VERSION[0]} | minor={FW_VERSION[1]}"
        f" | patch={FW_VERSION[2]} | CRC",
    ))

    # ----- §3. I2C envelopes -----------------------------------------
    out.append((
        "i2c_ping_write",
        i2c_write(CMD_PING).hex().upper(),
        "regaddr=0x00 | CMD=0x00 | CRC -- CRC excludes the regaddr byte",
    ))
    out.append((
        "i2c_ping_read_ok",
        i2c_read(STATUS_OK).hex().upper(),
        "STATUS=0x00 | CRC -- empty payload",
    ))

    return out


def emit(vectors: list[tuple[str, str, str | None]]) -> str:
    """Render the vector list back to the on-disk format."""
    chunks: list[str] = [HEADER]

    # ----- §1 block --------------------------------------------------
    chunks.append("\n# ---------------------------------------------------------------------")
    chunks.append("# §1. Foundational CRC-16/CCITT-FALSE vector")
    chunks.append("# ---------------------------------------------------------------------")
    for name, value, comment in vectors[:3]:
        if comment:
            chunks.append(f"# {comment}")
        chunks.append(f"{name:<30} = {value}")

    # ----- §2 block --------------------------------------------------
    chunks.append("\n# ---------------------------------------------------------------------")
    chunks.append("# §2. SPI envelopes -- two-transaction request / reply pattern")
    chunks.append("# ---------------------------------------------------------------------")
    for name, value, comment in vectors[3:7]:
        if comment:
            chunks.append(f"# {comment}")
        chunks.append(f"{name:<30} = {value}")

    # ----- §3 block --------------------------------------------------
    chunks.append("\n# ---------------------------------------------------------------------")
    chunks.append("# §3. I2C envelopes -- register-style framing")
    chunks.append("# ---------------------------------------------------------------------")
    for name, value, comment in vectors[7:]:
        if comment:
            chunks.append(f"# {comment}")
        chunks.append(f"{name:<30} = {value}")

    chunks.append("")  # final newline
    return "\n".join(chunks)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the on-disk file does not match the generated content",
    )
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=pathlib.Path(__file__).parent / "protocol_vectors.txt",
        help="path to the vectors file (default: alongside this script)",
    )
    args = parser.parse_args(argv)

    rendered = emit(build_vectors())

    if args.check:
        if not args.out.exists():
            print(f"missing: {args.out}", file=sys.stderr)
            return 1
        on_disk = args.out.read_text(encoding="utf-8")
        if on_disk != rendered:
            print(
                f"DRIFT: {args.out} does not match generator output. "
                f"Rerun this script without --check.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {args.out} matches generator output.")
        return 0

    args.out.write_text(rendered, encoding="utf-8")
    print(f"wrote {len(rendered)} bytes to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
