# SPDX-License-Identifier: Apache-2.0
"""`validate_metadata._check_npu_ops_semantics` -- the per-NPU op-support
table contract (issue #1801): metadata/schemas/npu-ops-v1.schema.json is the
shape, this gate is the path/content cross-checks a schema can't express.

`metadata/npu_ops/` ships EMPTY on this branch (the data lands separately
with issue #1470) -- so every test here writes its own fixture under
`tmp_path` rather than depending on the live tree, mirroring
`tests/scripts/test_model_perf_metadata.py`'s pattern for the same "contract
before data" situation.

`_BASE` is grounded in a REAL vela 5.1.0 `--supported-ops-report` capture (a
trimmed op list, same provenance shape) -- not an invented table.

Run locally:

    python -m pytest tests/scripts/test_npu_ops_metadata.py -v
"""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

import jsonschema

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))

import validate_metadata as V  # noqa: E402


def _base() -> dict:
    return copy.deepcopy({
        "_generated": "AUTO-GENERATED by scripts/gen_npu_ops.py -- DO NOT EDIT; "
                       "regenerate: python3 scripts/gen_npu_ops.py",
        "applies_to": {
            "variant": "u55-u65",
            "products": ["ethos-u55", "ethos-u65"],
            "toolchain": "vela",
            "toolchain_version": "5.1.0",
        },
        "op_namespace": "tflite",
        "authority": "tool-generated",
        "stance": "screening",
        "provenance": {
            "source": "vela --supported-ops-report, table "
                       "'## Ethos-U55 and Ethos-U65 TFLite Summary Table' (column 1)",
            "tool_version": "vela 5.1.0",
            "content_hash": "md5:93f186ba8653467e46751765d151c3bd",
            "count_expected": 4,
        },
        "supported_ops": ["ABS", "ADD", "CONCATENATION", "CONV_2D"],
    })


def _write(tmp_path: Path, doc: dict, *, family: str = "ethos_u",
           name: str | None = None) -> Path:
    at = doc.get("applies_to") if isinstance(doc.get("applies_to"), dict) else {}
    stem = name if name is not None else (
        f"{at.get('variant')}@{at.get('toolchain')}-{at.get('toolchain_version')}")
    p = tmp_path / family / f"{stem}.json"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(doc), encoding="utf-8")
    return p


def _msgs(tmp_path: Path, doc: dict, **write_kwargs) -> list[str]:
    p = _write(tmp_path, doc, **write_kwargs)
    failures = V._check_npu_ops_semantics([p])
    if not failures:
        return []
    assert len(failures) == 1  # one file in, at most one failure entry out
    return failures[0][1]


# --- positive control -------------------------------------------------

def test_base_fixture_passes_semantic_check(tmp_path):
    assert _msgs(tmp_path, _base()) == []


def test_base_fixture_is_schema_valid():
    schema = json.loads(V.NPU_OPS_SCHEMA.read_text(encoding="utf-8"))
    validator = jsonschema.Draft202012Validator(schema)
    assert list(validator.iter_errors(_base())) == []


def test_vendor_manual_fixture_with_no_banner_is_schema_valid():
    """Positive control for the OTHER authority value: a hand-transcribed
    table carries no `_generated` banner and still validates -- the schema's
    own `required` list must not force one on every table."""
    doc = _base()
    doc["authority"] = "vendor-manual"
    del doc["_generated"]
    doc["op_namespace"] = "onnx"
    doc["supported_ops"] = ["Conv", "Add", "MatMul", "LRN"]
    schema = json.loads(V.NPU_OPS_SCHEMA.read_text(encoding="utf-8"))
    validator = jsonschema.Draft202012Validator(schema)
    assert list(validator.iter_errors(doc)) == []


# --- (1) filename must reproduce applies_to identity ----------------------

def test_rejects_filename_not_matching_applies_to(tmp_path):
    doc = _base()
    msgs = _msgs(tmp_path, doc, name="stale-name@vela-1.0.0")
    assert any("implies filename" in m for m in msgs)


def test_accepts_filename_matching_applies_to_exactly(tmp_path):
    doc = _base()
    assert _msgs(tmp_path, doc) == []  # _write() derives the correct name by default


# --- (2) op_namespace must match the backend family's ingest format -------

def test_rejects_onnx_namespace_under_ethos_u_directory(tmp_path):
    doc = _base()
    doc["op_namespace"] = "onnx"
    doc["supported_ops"] = ["Conv", "Add"]
    msgs = _msgs(tmp_path, doc, family="ethos_u")
    assert any("backend ingests `tflite`" in m for m in msgs)


def test_accepts_onnx_namespace_under_drpai_directory(tmp_path):
    doc = _base()
    doc["applies_to"] = {
        "variant": "onnx-i8", "products": ["v2n"],
        "toolchain": "translator", "toolchain_version": "1.12",
    }
    doc["op_namespace"] = "onnx"
    doc["authority"] = "vendor-manual"
    del doc["_generated"]
    doc["provenance"] = {
        "source": "R20UT5336EJ0112 Rev.1.12", "tool_version": "DRP-AI Translator i8 v1.12",
        "content_hash": "md5:bebb81454e7f9bee2b115e0201516b2b",
    }
    doc["supported_ops"] = ["Conv", "Add", "MatMul"]
    assert _msgs(tmp_path, doc, family="drpai") == []


def test_an_unregistered_family_is_not_namespace_checked(tmp_path):
    """A backend family this cross-check doesn't yet know (not `ethos_u` or
    `drpai`) is unknown territory -- nothing to compare `op_namespace`
    against, so no failure fires on that account alone."""
    doc = _base()
    doc["op_namespace"] = "onnx"
    doc["supported_ops"] = ["Conv", "Add", "MatMul", "Sub"]
    msgs = _msgs(tmp_path, doc, family="some_future_backend")
    assert not any("backend ingests" in m for m in msgs)


# --- (3) count_expected must equal len(supported_ops) ----------------------

def test_rejects_count_expected_mismatch(tmp_path):
    doc = _base()
    doc["provenance"]["count_expected"] = 99
    msgs = _msgs(tmp_path, doc)
    assert any("count_expected=99" in m for m in msgs)


def test_accepts_matching_count_expected(tmp_path):
    doc = _base()
    doc["provenance"]["count_expected"] = len(doc["supported_ops"])
    assert _msgs(tmp_path, doc) == []


def test_count_expected_is_optional(tmp_path):
    doc = _base()
    del doc["provenance"]["count_expected"]
    assert _msgs(tmp_path, doc) == []


# --- (4) supported_ops spelling must match the declared namespace ---------

def test_rejects_lowercase_op_in_a_tflite_table(tmp_path):
    doc = _base()
    doc["supported_ops"] = ["ABS", "conv_2d"]  # wrong case for tflite
    doc["provenance"]["count_expected"] = 2
    msgs = _msgs(tmp_path, doc)
    assert any("wrong vocabulary" in m for m in msgs)


def test_rejects_underscored_op_in_an_onnx_table(tmp_path):
    doc = _base()
    doc["applies_to"] = {
        "variant": "onnx-i8", "products": ["v2n"],
        "toolchain": "translator", "toolchain_version": "1.12",
    }
    doc["op_namespace"] = "onnx"
    doc["authority"] = "vendor-manual"
    del doc["_generated"]
    doc["provenance"] = {
        "source": "s", "tool_version": "v", "content_hash": "md5:00000000000000000000000000000000",
    }
    doc["supported_ops"] = ["Conv", "CONV_2D"]  # CONV_2D is a tflite spelling
    msgs = _msgs(tmp_path, doc, family="drpai")
    assert any("wrong vocabulary" in m for m in msgs)


def test_accepts_allcaps_onnx_acronym_with_no_underscore(tmp_path):
    """LRN/GRU/LSTM are real ONNX operators spelled as short all-caps
    acronyms -- the underscore-based discriminator must not false-flag
    them just for being upper-case (the false positive `op == op.upper()`
    alone would trip)."""
    doc = _base()
    doc["applies_to"] = {
        "variant": "onnx-i8", "products": ["v2n"],
        "toolchain": "translator", "toolchain_version": "1.12",
    }
    doc["op_namespace"] = "onnx"
    doc["authority"] = "vendor-manual"
    del doc["_generated"]
    doc["provenance"] = {
        "source": "s", "tool_version": "v", "content_hash": "md5:00000000000000000000000000000000",
    }
    doc["supported_ops"] = ["LRN", "GRU", "LSTM", "Conv"]
    assert _msgs(tmp_path, doc, family="drpai") == []


# --- (5) authority <-> `_generated` banner pairing --------------------------

def test_rejects_tool_generated_with_no_banner(tmp_path):
    doc = _base()
    del doc["_generated"]
    msgs = _msgs(tmp_path, doc)
    assert any("no `_generated` DO-NOT-EDIT banner" in m for m in msgs)


def test_rejects_vendor_manual_with_a_banner(tmp_path):
    doc = _base()
    doc["authority"] = "vendor-manual"
    # doc["_generated"] left in place from the base fixture -- the misleading case.
    msgs = _msgs(tmp_path, doc)
    assert any("no script to regenerate" in m for m in msgs)
