# SPDX-License-Identifier: Apache-2.0
"""scripts/gen_linux_ownership_dt.py: the Linux ownership fragment follows the
metadata (resolved ownership, hw_blocked, SoC linux_dt PFC codes)."""
import copy
import json
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts"))

import gen_linux_ownership_dt as g  # noqa: E402

DOC, SOC, LINKS = g._load(REPO)


def test_committed_fragment_is_in_sync():
    r = subprocess.run([sys.executable, str(REPO / "scripts" / "gen_linux_ownership_dt.py"), "--check"],
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stderr


def test_default_fragment_enables_uart0_only_and_keeps_spi0_disabled():
    text, labels = g.render(DOC, SOC, LINKS)
    assert "GENERATED by scripts/gen_linux_ownership_dt.py" in text and "DO NOT EDIT" in text
    assert "RZV2N_PORT_PINMUX(5, 0, 1)" in text and "&sci0 {" in text and 'status = "okay"' in text
    assert labels == {"sci0", "cpg"}
    # rspi0: never an enabled node, and the reason is quoted from metadata
    assert "&rspi0 {" not in text and "3.3 V tolerant" in text
    # missing PFC codes are a GAP, not a guessed number
    assert text.count("GAP -- no PFC function code") == 3  # uart1, can0, can1
    assert "&canfd {" not in text and "&sci1 {" not in text


def test_pfc_code_and_label_come_from_the_soc_metadata():
    soc = copy.deepcopy(SOC)
    soc["linux_dt"]["UART0"]["pinmux"] = {"UART0_TXD0": 7, "UART0_RXD0": 7}
    soc["linux_dt"]["UART0"]["label"] = "sciX"
    text, _ = g.render(DOC, soc, LINKS)
    assert "RZV2N_PORT_PINMUX(5, 0, 7)" in text and "&sciX {" in text


def test_m33_owned_instance_is_left_alone_and_can_channel_is_emitted_when_known():
    soc = copy.deepcopy(SOC)
    text, _ = g.render(DOC, soc, LINKS, {**g.resolve_ownership(DOC), "e1m_uart0": "m33"})
    assert "owned by m33; Linux leaves it alone" in text and "&sci0 {" not in text
    soc["linux_dt"]["CANFD3"]["pinmux"] = {"CANFD3_CRX3": 9, "CANFD3_CTX3": 9}
    text, labels = g.render(DOC, soc, LINKS)
    assert "&canfd {" in text and "channel3 {" in text and "canfd/channel3" in labels


def test_hw_blocked_wins_over_an_a55_default():
    doc = copy.deepcopy(DOC)
    soc = copy.deepcopy(SOC)
    soc["linux_dt"]["RSPI0"]["pinmux"] = {r["peripheral"]: 1 for r in doc["assignable"]["e1m_spi0"]["rows"]}
    text, _ = g.render(doc, soc, LINKS)
    assert "&rspi0 {" not in text and "hardware-blocked" in text
    del doc["assignable"]["e1m_spi0"]["hw_blocked"]
    text, _ = g.render(doc, soc, LINKS)
    assert "&rspi0 {" in text


def test_unknown_soc_instance_is_an_error():
    doc = copy.deepcopy(DOC)
    doc["assignable"]["e1m_uart0"]["soc_instance"] = "NOPE"
    with pytest.raises(g.GenError, match="NOPE"):
        g.render(doc, SOC, LINKS)


def test_vendor_dtsi_check_rejects_a_missing_label(tmp_path):
    v = tmp_path / "r9a09g056.dtsi"
    v.write_text("\t\tsci1: serial@12801000 {\n\t\t};\n", encoding="utf-8")
    assert g.check_vendor({"sci0"}, v) == ["label &sci0 is not defined in r9a09g056.dtsi"]
    v.write_text("\t\tsci0: serial@12800c00 {\n\t\t};\n", encoding="utf-8")
    assert g.check_vendor({"sci0"}, v) == []


def test_cm33_owned_clocks_always_hold_sci7_and_follow_the_ownership():
    sci7 = ", ".join(f'"{c}"' for c in SOC["linux_dt"]["SCI7"]["cpg_clocks"])
    text, _ = g.render(DOC, SOC, LINKS)
    assert f"&cpg {{\n\trenesas,cm33-owned-clocks = {sci7};" in text  # a55 defaults: the GD32 link only
    own = {**g.resolve_ownership(DOC), "e1m_uart0": "m33"}
    uart0 = ", ".join(f'"{c}"' for c in SOC["linux_dt"]["UART0"]["cpg_clocks"])
    assert f"= {sci7}, {uart0};" in g.render(DOC, SOC, LINKS, own)[0]
    # a hw_blocked instance never contributes (it is never enabled)
    own = {**g.resolve_ownership(DOC), "e1m_spi0": "m33"}
    assert "rspi_0" not in g.render(DOC, SOC, LINKS, own)[0]


def test_m33_owned_instance_without_cpg_clocks_is_an_error():
    import copy
    soc = copy.deepcopy(SOC)
    del soc["linux_dt"]["UART0"]["cpg_clocks"]
    with pytest.raises(g.GenError, match="no cpg_clocks"):
        g.cm33_clocks(DOC, soc, LINKS, {**g.resolve_ownership(DOC), "e1m_uart0": "m33"})
